/*
	Copyright (c) 2015-2024 Applied Research Laboratories, The University of Texas
	at Austin (ARL:UT).
	
	SALSA is free software: you can redistribute it and/or modify it under the
	terms of the GNU General Public License version 3 (GPL-3.0-only) as published
	by the Free Software Foundation.
	
	SALSA is distributed in the hope that it will be useful, but WITHOUT ANY
	WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
	A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License along with
	SALSA.  If not, see https://www.gnu.org/licenses/.
*/
#include "AboutSalsa.hpp"
#include "ui_AboutSalsa.h"

#include "LSAVersion.hpp"
#include <QPixmap>
#include <QTextStream>
#include <QFile>
#include <QDir>
#include <QCoreApplication>

AboutSalsaDialog::AboutSalsaDialog(QWidget *parent) :
    QDialog(parent),
    ui(new Ui::AboutSalsa)
{
    ui->setupUi(this);

    setWindowTitle("About SALSA");

    QString versionString = QString("SALSA ") + QString::fromStdString( LSAVERSION_MAJOR_MINOR_PATCH );
    if(!LSARELEASE_TYPE.empty())
        versionString += QString(" ") + QString::fromStdString( LSARELEASE_TYPE );
    ui->labelVersion->setText(versionString);

    QString gitShaString = QString("Git Hash: ") + QString::fromStdString(GIT_SHA);
    ui->labelGitSha->setText(gitShaString);

    QString buildString = QString("Built on ") + QString::fromStdString(LSAVERSION_BUILD_DATE) + " at "  + QString::fromStdString(LSAVERSION_BUILD_TIME);
    ui->labelBuild->setText(buildString);

    // This next section determines if this is an FOUO or Public build and adjusts the about menu
    // appropriately. Namely, the public release line is removed in ARL builds
    if( LSABUILD_TYPE == "fouo")
    {
        ui->labelPublicRelease->hide();
    }
    else
    {
        // This text is autogenerated by versions.py. The end of the string will either read
        // as a case number (e.g. 19-198) or TBD. For now, this will have to be manually
        // edited to reflect the current state of public release. It should read TBD
        // until the release is actually approved for public release at which
        // time it should be edited to reflect the correct case number.
        setLabelText(QString::fromStdString(LSAPUBLICRELEASE), ui->labelPublicRelease);
        ui->labelPublicRelease->show();
    }

    setLabelText(QString::fromStdString(LSAADDENDUM), ui->labelAddendum);
    setLabelText(QString::fromStdString(LSACOPYRIGHT), ui->labelCopyright);
    setLabelText(QString::fromStdString(LSALICENSENOTICE), ui->labelLicenseNotice);

    QPixmap pixmap(":/guiIcons/salsa_icon.png");
    ui->labelIcon->setPixmap(pixmap);
}

AboutSalsaDialog::~AboutSalsaDialog()
{
    delete ui;
}

void AboutSalsaDialog::setLabelText(const QString &labelText, QLabel *labelToSet)
{
    if(!labelText.isEmpty())
    {
        labelToSet->setText(labelText);
    }
}
