/*
	Copyright (c) 2015-2024 Applied Research Laboratories, The University of Texas
	at Austin (ARL:UT).
	
	SALSA is free software: you can redistribute it and/or modify it under the
	terms of the GNU General Public License version 3 (GPL-3.0-only) as published
	by the Free Software Foundation.
	
	SALSA is distributed in the hope that it will be useful, but WITHOUT ANY
	WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
	A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License along with
	SALSA.  If not, see https://www.gnu.org/licenses/.
*/

#ifndef INSERTRECORDSCOMMAND_H
#define INSERTRECORDSCOMMAND_H

// Qt
#include <QUndoCommand>
#include <QModelIndex>
#include <LSARecord.hpp>

#include<GuiModelItem.hpp>

class GuiModel;

class InsertRecordsCommand : public QUndoCommand
{
public:
  InsertRecordsCommand(const QPersistentModelIndex& parentIndex,
                       const QList<QPersistentModelIndex>& indexList,
                       int rowPosition,
                       QList<LSAType> recordTypes,
                       QList<std::string> recordStrings,
                       QList<bool> isAutogeneratedList,
                       QList<bool> isCommentedList,
                       GuiModel *model);

  void redo() Q_DECL_OVERRIDE;
  void undo() Q_DECL_OVERRIDE;

private:
  GuiModel *m_model; // Pointer to the gui model
  int m_rowPosition; // Which row was the record inserted on
  bool m_redoAction; // Qt calls redo() automatically. Flag prevents double insertions
  QList<LSAType> m_recordTypes; // List of all inserted record types
  QList<std::string> m_recordStrings; // List of inserted LSA-formatted strings
  QList<bool> m_isAutogeneratedList; // List of which records are autogenerated
  QList<bool> m_isCommentedList; // List of which records are comments
  QList<QPersistentModelIndex> m_indexList; // List of inserted records
  QList<int> m_childRows, m_childColumns; // Lists of rows and columns of inserted indices
  QVector<IndexRowColumnParentChainItem> m_parentChain; // Structure used to map parent->root link
};

#endif // INSERTRECORDSCOMMAND_H
