/*
	Copyright (c) 2015-2024 Applied Research Laboratories, The University of Texas
	at Austin (ARL:UT).
	
	SALSA is free software: you can redistribute it and/or modify it under the
	terms of the GNU General Public License version 3 (GPL-3.0-only) as published
	by the Free Software Foundation.
	
	SALSA is distributed in the hope that it will be useful, but WITHOUT ANY
	WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
	A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License along with
	SALSA.  If not, see https://www.gnu.org/licenses/.
*/
#include "InsertRecordsCommand.hpp"

// Project includes
#include "GuiModel.hpp"

InsertRecordsCommand::InsertRecordsCommand(const QPersistentModelIndex& parentIndex,
                                           const QList<QPersistentModelIndex>& indexList,
                                           int rowPosition,
                                           QList<LSAType> recordTypes,
                                           QList<std::string> recordStrings,
                                           QList<bool> isAutogeneratedList,
                                           QList<bool> isCommentedList,
                                       GuiModel *model) : m_model(model)
{
    m_redoAction = false;
    m_rowPosition = rowPosition;
    m_recordTypes = recordTypes;
    m_recordStrings = recordStrings;
    m_isAutogeneratedList = isAutogeneratedList;
    m_isCommentedList = isCommentedList;
    m_indexList = indexList;

    // Build the index/parent->root chain. Since there is no multi-select in inserting records only the main
    // chain is needed and the matrix is not.
    m_parentChain = m_model->buildSingleIndexChain(parentIndex);

    // Fill out the row trees
    for(int i = 0; i < m_indexList.size(); i++)
    {
        m_childRows.append(m_indexList[i].row());
        m_childColumns.append(m_indexList[i].column());
    }

    setText("InsertRecordsCommand");
}

void InsertRecordsCommand::redo()
{
    // redoAction check is needed because when an undo/redo object is initialized, `redo()` is automatically called.
    // Since the actual change is accomplished in the code before the object is created, this would lead to the action
    // being performed twice and ruining the undo/redo ability.
    if(m_redoAction)
    {
        if (!m_parentChain[0].index.isValid())
        {
            // Refresh the chain to ensure the current index is valid
            m_model->refreshSingleIndexChain(m_parentChain);

            // Don't attempt to remove if index is stil invalid
            if (!m_parentChain[0].index.isValid())
            {
                this->setObsolete(true);
                return;
            }
        }

        QModelIndexList dummyIndices = m_model->insertNewRecords(m_parentChain[0].index, m_rowPosition, m_recordTypes, m_recordStrings, m_isAutogeneratedList, m_isCommentedList, true);

        if (!dummyIndices.isEmpty())
        {
            m_indexList.clear();
            m_childRows.clear();
            m_childColumns.clear();
            for(auto& index : dummyIndices)
            {
                m_indexList.append(index);
                m_childRows.append(index.row());
                m_childColumns.append(index.column());
            }

            // Sync the model and push appropriate signals
            m_model->refreshAfterUndoRedo(m_parentChain[0].index);

            return;
        }
    }

    m_redoAction = true;
    return;
}

void InsertRecordsCommand::undo()
{
    if (!m_parentChain[0].index.isValid())
    {
        // Refresh the chain to ensure the current index is valid
        m_model->refreshSingleIndexChain(m_parentChain);

        // Don't attempt to remove if index is still invalid
        if (!m_parentChain[0].index.isValid())
        {
            this->setObsolete(true);
            return;
        }
    }

    // Verify that each index is still valid
    for(int i = 0; i < m_indexList.size(); i++)
    {
        if(!m_indexList[i].isValid())
        {
            m_indexList[i] = m_model->index(m_childRows[i], m_childColumns[i], m_parentChain[0].index);
            if(!m_indexList[i].isValid())
            {
                this->setObsolete(true);
                return;
            }
        }
        m_model->removeRecord(m_indexList[i], false, false, true);
    }

    if (!m_indexList.isEmpty())
    {
        // Sync the model and push appropriate signals
        m_model->refreshAfterUndoRedo(m_parentChain[0].index);

        return;
    }
}
