/*
	Copyright (c) 2015-2024 Applied Research Laboratories, The University of Texas
	at Austin (ARL:UT).
	
	SALSA is free software: you can redistribute it and/or modify it under the
	terms of the GNU General Public License version 3 (GPL-3.0-only) as published
	by the Free Software Foundation.
	
	SALSA is distributed in the hope that it will be useful, but WITHOUT ANY
	WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
	A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License along with
	SALSA.  If not, see https://www.gnu.org/licenses/.
*/
#ifndef MAPPING_HPP
#define MAPPING_HPP

// Marble Includes
#include <marble/GeoDataDocument.h>
#include <marble/GeoDataIconStyle.h>
#include <marble/GeoDataLineString.h>
#include <marble/GeoDataPlacemark.h>
#include <marble/GeoDataStyle.h>
#include <marble/GeoDataTreeModel.h>
#include <marble/GeoDataLinearRing.h>
#include <marble/GeoDataLineStyle.h>
#include <marble/GeoDataPolyStyle.h>
#include <marble/GeoDataLatLonAltBox.h>
#include <marble/GeoDataLookAt.h>
#include <marble/RemoteIconLoader.h>
#include <marble/MarbleDirs.h>
#include <marble/MarbleModel.h>
#include <marble/MarbleWidget.h>
#include <marble/MarbleWidgetInputHandler.h>
#include <marble/ViewportParams.h>
#include <marble/FileManager.h>
#include <marble/GeoDataFolder.h>
#include <marble/GeoDataContainer.h>

// Qt Includes
#include <QWidget>
#include <QDockWidget>
#include <QFileInfo>
#include <QItemSelection>
#include <QMenu>
#include <QSettings>
#include <qmath.h>
#include <QToolTip>
#include <QRect>
#include <QCloseEvent>
#include <QRegExp>
#include <QTimer>
#include <QStandardItemModel>

// LSA Includes
#include <DebugTimer.hpp>
#include <LSAFile.hpp>
#include "LSAGuiConstants.hpp"
#include <GuiModel.hpp>
#include <lsaUtils.hpp>
#include <AdjustedPositions.hpp>

// QuaZip includes
#include <quazip/JlCompress.h>

// GNSSTk includes
#include "WGS84Ellipsoid.hpp"

using namespace Marble;

/// Enumeration for point icon style
/// FIXED:    the point is fixed in all directions (North, East, and Up)
/// FIXED_1:  the point is fixed in one direction  (North, East, or Up)
/// FIXED_2:  the point is fixed in two directions (chose two: North, East, or Up)
/// FLOATING: the point is not fixed in any direction
/// APRIORI:  the point was an autogenerated a priori point from the solver (parsed in from output file) and not specified in the input file
/// For all of these options there is also a _HIGHLIGHTED version because the not
/// highlighted and highlighted icons are actually different images
//enum FixedStatus {FIXED_ALL, FIXED_ALL_HIGHLIGHTED, FIXED_1, FIXED_1_HIGHLIGHTED, FIXED_2, FIXED_2_HIGHLIGHTED, FLOATING, FLOATING_HIGHLIGHTED, APRIORI, APRIORI_HIGHLIGHTED};
enum IconType {POINT_FIXED_ALL, POINT_FIXED_1, POINT_FIXED_2, POINT_FLOATING, POINT_APRIORI, POINT_CONSTRAIN, UNKNOWN};

/// Enumeration for highlighted status
/// Sets whether the highlight placemark for a given measurement is visible
/// Could be extended in the future for other uses
enum HighlightStatus {DEFAULT, HIGHLIGHTED};

namespace Ui
{
    class Mapping;
}

/// Class Mapping encapsulates a Marble mapping widget with associated
/// standard behaviors.  In addition, Mapping impliments methods that
/// automate plotting measurements
class Mapping : public QDockWidget
{
    Q_OBJECT

    friend class TestLSAGui; ///< Test harness class used to execute gui unit and integration tests
    friend class Benchmarks; ///< Test harness class used to execute gui unit and integration tests

public:

    /// all const static variables set at the top of mapping.cpp
    const static int MEAS_LINE_WIDTH;                      ///< The width (in pixels?) of a line depicting a measurement
    const static int MEAS_LINE_WIDTH_HIGHLIGHTED;           ///< The width (in pixels?) of a measurement line's highlight line. All measurements except reference lines use this value
    const static int MEAS_REF_LINE_WIDTH;             ///< The width (in pixels?) of a reference line.  Reference lines a drawn for horizontal angles between 'from and at' and 'at and to'
    const static int MEAS_REF_LINE_WIDTH_HIGHLIGHTED;  ///< The width (in pixels?) of a reference line's highlight line.
    const static int ELLIPSE_PRECISON;                          ///< The number of line segments used to approximate an ellipse
//    const static qreal ellipseFromCovarianceScaleFactor;        ///< How much larger than the "true" ellipse an ellipse drawn from a covariance matrix is shown
    const static int ANGLE_PRECISION;                            ///< The number of line segments used to approximate the circular part of an angle that measured 360 degrees
    const static qreal ANGLE_SCALE;                              ///< The ratio of the radius of the angle symbol to the shortest distance in the angle
    const static qreal ARROW_ANGLE;                              ///< The angle in radians that the small parts of the arrow make with the main line
    const static qreal ARROW_SCALE_FACTOR;                        ///< How much smaller than the radius of the angle symbol or length of the arrow the small parts of an arrow are drawn
    const static qreal DEFAULT_HEIGHT;                           ///< The arbitrary height given to all generated coordinates because the marbleWidget does not display height information
    const static qreal AZIM_LENGTH_FACTOR;                     ///< The ratio of the length between the from and to points of an azimuth and how long to the north reference line is drawn

    const static qreal MAX_FRACTION_OF_DIAGONAL; ///< the maximum fraction of the viewport diagonal that an ellipse or displacement arrow can be drawn
    const static qreal DEFAULT_FRACTION_OF_DIAGONAL; ///< the default fraction of the viewport diagonal that an ellipse or displacement arrow can be drawn

    const static int SCALE_BAR_WIDTH_PIXELS; ///< the width in pixels of the black scale bar in the resource file scale_bar.png

    const static double ELLIPSE_MIN_RADIUS_THRESHOLD; // minimum threshold for comparision with radius of 0.0
    const static double RECTANGLE_MIN_SIZE_THRESHOLD; // minimum threshold for comparision with NA of 0.0

    //DEFAULT PATHS
    const static QString PATH_FIXED_1;
    const static QString PATH_FIXED_2;
    const static QString PATH_FIXED_ALL;

    const static QString PATH_FIXEDC_1;
    const static QString PATH_FIXEDC_2;
    const static QString PATH_FIXEDAC;

    const static QString PATH_FLOATING;
    const static QString PATH_DERIVED;
    const static QString PATH_CONSTRAIN;
    const static QString PATH_APRIORI;

    //HIGHLIGHTED PATHS
    const static QString PATH_FIXED_1_HIGH;
    const static QString PATH_FIXED_2_HIGH;
    const static QString PATH_FIXED_ALL_HIGH;

    const static QString PATH_FIXEDC_1_HIGH;
    const static QString PATH_FIXEDC_2_HIGH;
    const static QString PATH_FIXEDAC_HIGH;

    const static QString PATH_FLOATING_HIGH;
    const static QString PATH_DERIVED_HIGH;
    const static QString PATH_CONSTRAIN_HIGH;
    const static QString PATH_APRIORI_HIGH;

    const static QString MAP_THEME_BLANK;
    const static QString MAP_THEME_OPENSTREET;

    const static int HANDLE_ROW_REMOVED_TIMEOUT_MS;
    const static int HANDLE_ROW_INSERTED_TIMEOUT_MS;
    const static int HANDLE_DATA_CHANGED_TIMEOUT_MS;
    const static int SET_HOME_TIMEOUT_MS;

    const static int SCROLL_ZOOM_THRESHOLD;

    const static int NUM_SLIDER_DIVISIONS; ///< how many divisions the slider will have

    bool suppressMapWidgetUpdates;
    bool mapIsEnabled;
    qint32 previousZoomLevel;

    explicit Mapping(bool &saveLSARecord, QWidget *parent);

    ~Mapping();

    /// Sets the GuiModel that Mapping gets all of its data from
    /// @param newModel pointer to the new GuiModel object
    void setGuiModel(GuiModel* newModel);

    void setEllipseConfidenceFactor(double confidenceFactor_2d, double confidenceFactor_1d)
    {
        ellipseConfidenceFactor2D = confidenceFactor_2d;
        ellipseBarConfidenceFactor1D = confidenceFactor_1d;
    }

    /// Checks the indexToPlacemarkMap to see if there is a placemark for the position with this label
    /// Used for GUI tests
    /// @param posLabel label corresponding to a POSG or POSC record
    /// @return true if point is displayed in the map false if not
    bool isPointDisplayedInMap(std::string posLabel);

    /// This function sets up the map, reading from an options file if available.
    /// It is meant to be called instead of the first call to update().
    void initialize();

    QPixmap mapScreenShot(); ///< @return a QPixmap object that is a screen shot of the map
    void exportKML(QString, AdjustedPositions*); /// Generate the kmz zipped file in the user specified directory

    /// -----------------------------------------------------------------------------------
    /// -----------------------Getting and Setting Map Styles -----------------------------
    /// -----------------------------------------------------------------------------------
    QSettings qsettings;
    // AZIM
    QColor getColorAZIM()     { return qsettings.value( lsa::QSETTINGS_COLOR_AZIM, lsa::DEFAULT_COLOR_AZIM).value<QColor>(); }
    qint32 getLineWidthAZIM() { return qsettings.value( lsa::QSETTINGS_LINEWIDTH_AZIM, lsa::DEFAULT_LINEWIDTH_AZIM).value<qint32>(); }
    qint32 getPenStyleAZIM()  { return qsettings.value( lsa::QSETTINGS_PENSTYLE_AZIM, lsa::DEFAULT_PENSTYLE_AZIM).value<qint32>(); }
    void   setColorAZIM(QColor color)    { qsettings.setValue( lsa::QSETTINGS_COLOR_AZIM, color ); }
    void   setLineWidthAZIM(int width)   { qsettings.setValue( lsa::QSETTINGS_LINEWIDTH_AZIM, width ); }
    void   setPenStyleAZIM(qint32 style) { qsettings.setValue( lsa::QSETTINGS_PENSTYLE_AZIM, style ); }

    // AZIM Reference Lines
    QColor getColorAZIMReferenceLines()     { return qsettings.value( lsa::QSETTINGS_COLOR_AZIM_REF, lsa::DEFAULT_COLOR_AZIM_REF).value<QColor>(); }
    qint32 getLineWidthAZIMReferenceLines() { return qsettings.value( lsa::QSETTINGS_LINEWIDTH_AZIM_REF, lsa::DEFAULT_LINEWIDTH_AZIM_REF).value<qint32>(); }
    qint32 getPenStyleAZIMReferenceLines()  { return qsettings.value( lsa::QSETTINGS_PENSTYLE_AZIM_REF, lsa::DEFAULT_PENSTYLE_AZIM_REF).value<qint32>(); }
    void   setColorAZIMReferenceLines(QColor color)    { qsettings.setValue( lsa::QSETTINGS_COLOR_AZIM_REF, color ); }
    void   setLineWidthAZIMReferenceLines(int width)   { qsettings.setValue( lsa::QSETTINGS_LINEWIDTH_AZIM_REF, width ); }
    void   setPenStyleAZIMReferenceLines(qint32 style) { qsettings.setValue( lsa::QSETTINGS_PENSTYLE_AZIM_REF, style ); }

    // HANG
    QColor getColorHANG()     { return qsettings.value( lsa::QSETTINGS_COLOR_HANG, lsa::DEFAULT_COLOR_HANG).value<QColor>(); }
    qint32 getLineWidthHANG() { return qsettings.value( lsa::QSETTINGS_LINEWIDTH_HANG, lsa::DEFAULT_LINEWIDTH_HANG).value<qint32>(); }
    qint32 getPenStyleHANG()  { return qsettings.value( lsa::QSETTINGS_PENSTYLE_HANG, lsa::DEFAULT_PENSTYLE_HANG).value<qint32>(); }
    void   setColorHANG(QColor color)    { qsettings.setValue( lsa::QSETTINGS_COLOR_HANG, color ); }
    void   setLineWidthHANG(int width)   { qsettings.setValue( lsa::QSETTINGS_LINEWIDTH_HANG, width ); }
    void   setPenStyleHANG(qint32 style) { qsettings.setValue( lsa::QSETTINGS_PENSTYLE_HANG, style ); }

    // HANG Reference Lines
    QColor getColorHANGReferenceLines()     { return qsettings.value( lsa::QSETTINGS_COLOR_HANG_REF, lsa::DEFAULT_COLOR_HANG_REF).value<QColor>(); }
    qint32 getLineWidthHANGReferenceLines() { return qsettings.value( lsa::QSETTINGS_LINEWIDTH_HANG_REF, lsa::DEFAULT_LINEWIDTH_HANG_REF).value<qint32>(); }
    qint32 getPenStyleHANGReferenceLines()  { return qsettings.value( lsa::QSETTINGS_PENSTYLE_HANG_REF, lsa::DEFAULT_PENSTYLE_HANG_REF).value<qint32>(); }
    void   setColorHANGReferenceLines(QColor color)   { qsettings.setValue( lsa::QSETTINGS_COLOR_HANG_REF, color ); }
    void   setLineWidthHANGReferenceLines(int width)  { qsettings.setValue( lsa::QSETTINGS_LINEWIDTH_HANG_REF, width ); }
    void  setPenStyleHANGReferenceLines(qint32 style) { qsettings.setValue( lsa::QSETTINGS_PENSTYLE_HANG_REF, style ); }

    // ZANG
    QColor getColorZANG()     { return qsettings.value( lsa::QSETTINGS_COLOR_ZANG, lsa::DEFAULT_COLOR_ZANG).value<QColor>(); }
    qint32 getLineWidthZANG() { return qsettings.value( lsa::QSETTINGS_LINEWIDTH_ZANG, lsa::DEFAULT_LINEWIDTH_ZANG).value<qint32>(); }
    qint32 getPenStyleZANG()  { return qsettings.value( lsa::QSETTINGS_PENSTYLE_ZANG, lsa::DEFAULT_PENSTYLE_ZANG).value<qint32>(); }
    void   setColorZANG(QColor color)    { qsettings.setValue( lsa::QSETTINGS_COLOR_ZANG, color ); }
    void   setLineWidthZANG(int width)   { qsettings.setValue( lsa::QSETTINGS_LINEWIDTH_ZANG, width ); }
    void   setPenStyleZANG(qint32 style) { qsettings.setValue( lsa::QSETTINGS_PENSTYLE_ZANG, style ); }

    // DIST
    QColor getColorDIST()     { return qsettings.value( lsa::QSETTINGS_COLOR_DIST, lsa::DEFAULT_COLOR_DIST).value<QColor>(); }
    qint32 getLineWidthDIST() { return qsettings.value( lsa::QSETTINGS_LINEWIDTH_DIST, lsa::DEFAULT_LINEWIDTH_DIST).value<qint32>(); }
    qint32 getPenStyleDIST()  { return qsettings.value( lsa::QSETTINGS_PENSTYLE_DIST, lsa::DEFAULT_PENSTYLE_DIST).value<qint32>(); }
    void   setColorDIST(QColor color)    { qsettings.setValue( lsa::QSETTINGS_COLOR_DIST, color ); }
    void   setLineWidthDIST(int width)   { qsettings.setValue( lsa::QSETTINGS_LINEWIDTH_DIST, width ); }
    void   setPenStyleDIST(qint32 style) { qsettings.setValue( lsa::QSETTINGS_PENSTYLE_DIST, style ); }

    // DXYZ
    QColor getColorDXYZ()     { return qsettings.value( lsa::QSETTINGS_COLOR_DXYZ, lsa::DEFAULT_COLOR_DXYZ).value<QColor>(); }
    qint32 getLineWidthDXYZ() { return qsettings.value( lsa::QSETTINGS_LINEWIDTH_DXYZ, lsa::DEFAULT_LINEWIDTH_DXYZ).value<qint32>(); }
    qint32 getPenStyleDXYZ()  { return qsettings.value( lsa::QSETTINGS_PENSTYLE_DXYZ, lsa::DEFAULT_PENSTYLE_DXYZ).value<qint32>(); }
    void   setColorDXYZ(QColor color)    { qsettings.setValue( lsa::QSETTINGS_COLOR_DXYZ, color ); }
    void   setLineWidthDXYZ(int width)   { qsettings.setValue( lsa::QSETTINGS_LINEWIDTH_DXYZ, width ); }
    void   setPenStyleDXYZ(qint32 style) { qsettings.setValue( lsa::QSETTINGS_PENSTYLE_DXYZ, style ); }

    // HDIR
    QColor getColorHDIR()     { return qsettings.value( lsa::QSETTINGS_COLOR_HDIR, lsa::DEFAULT_COLOR_HDIR).value<QColor>(); }
    qint32 getLineWidthHDIR() { return qsettings.value( lsa::QSETTINGS_LINEWIDTH_HDIR, lsa::DEFAULT_LINEWIDTH_HDIR).value<qint32>(); }
    qint32 getPenStyleHDIR()  { return qsettings.value( lsa::QSETTINGS_PENSTYLE_HDIR, lsa::DEFAULT_PENSTYLE_HDIR).value<qint32>(); }
    void   setColorHDIR(QColor color)    { qsettings.setValue( lsa::QSETTINGS_COLOR_HDIR, color ); }
    void   setLineWidthHDIR(int width)   { qsettings.setValue( lsa::QSETTINGS_LINEWIDTH_HDIR, width ); }
    void   setPenStyleHDIR(qint32 style) { qsettings.setValue( lsa::QSETTINGS_PENSTYLE_HDIR, style ); }

    // HDIF
    QColor getColorHDIF()     { return qsettings.value( lsa::QSETTINGS_COLOR_HDIF, lsa::DEFAULT_COLOR_HDIF).value<QColor>(); }
    qint32 getLineWidthHDIF() { return qsettings.value( lsa::QSETTINGS_LINEWIDTH_HDIF, lsa::DEFAULT_LINEWIDTH_HDIF).value<qint32>(); }
    qint32 getPenStyleHDIF()  { return qsettings.value( lsa::QSETTINGS_PENSTYLE_HDIF, lsa::DEFAULT_PENSTYLE_HDIF).value<qint32>(); }
    void   setColorHDIF(QColor color)    { qsettings.setValue( lsa::QSETTINGS_COLOR_HDIF, color ); }
    void   setLineWidthHDIF(int width)   { qsettings.setValue( lsa::QSETTINGS_LINEWIDTH_HDIF, width ); }
    void   setPenStyleHDIF(qint32 style) { qsettings.setValue( lsa::QSETTINGS_PENSTYLE_HDIF, style ); }

    // VANG
    QColor getColorVANG()     { return qsettings.value( lsa::QSETTINGS_COLOR_VANG, lsa::DEFAULT_COLOR_VANG).value<QColor>(); }
    qint32 getLineWidthVANG() { return qsettings.value( lsa::QSETTINGS_LINEWIDTH_VANG, lsa::DEFAULT_LINEWIDTH_VANG).value<qint32>();; }
    qint32 getPenStyleVANG()  { return qsettings.value( lsa::QSETTINGS_PENSTYLE_VANG, lsa::DEFAULT_PENSTYLE_VANG).value<qint32>(); }
    void   setColorVANG(QColor color)    { qsettings.setValue( lsa::QSETTINGS_COLOR_VANG, color ); }
    void   setLineWidthVANG(int width)   { qsettings.setValue( lsa::QSETTINGS_LINEWIDTH_VANG, width ); }
    void   setPenStyleVANG(qint32 style) { qsettings.setValue( lsa::QSETTINGS_PENSTYLE_VANG, style ); }

    // Ellipse
    QColor getColorEllipse()     { return qsettings.value( lsa::QSETTINGS_COLOR_ELLIPSE, lsa::DEFAULT_COLOR_ELLIPSE).value<QColor>(); }
    qint32 getLineWidthEllipse() { return qsettings.value( lsa::QSETTINGS_LINEWIDTH_ELLIPSE, lsa::DEFAULT_LINEWIDTH_ELLIPSE).value<qint32>(); }
    qint32 getPenStyleEllipse()  { return qsettings.value( lsa::QSETTINGS_PENSTYLE_ELLIPSE, lsa::DEFAULT_PENSTYLE_ELLIPSE).value<qint32>(); }
    void   setColorEllipse(QColor color)    { qsettings.setValue( lsa::QSETTINGS_COLOR_ELLIPSE, color ); }
    void   setLineWidthEllipse(int width)   { qsettings.setValue( lsa::QSETTINGS_LINEWIDTH_ELLIPSE, width ); }
    void   setPenStyleEllipse(qint32 style) { qsettings.setValue( lsa::QSETTINGS_PENSTYLE_ELLIPSE, style ); }

    // Rectangle
    QColor getColorRectangle()     { return qsettings.value( lsa::QSETTINGS_COLOR_RECTANGLE, lsa::DEFAULT_COLOR_RECTANGLE).value<QColor>(); }
    qint32 getLineWidthRectangle() { return qsettings.value( lsa::QSETTINGS_LINEWIDTH_RECTANGLE, lsa::DEFAULT_LINEWIDTH_RECTANGLE).value<qint32>(); }
    qint32 getPenStyleRectangle()  { return qsettings.value( lsa::QSETTINGS_PENSTYLE_RECTANGLE, lsa::DEFAULT_PENSTYLE_RECTANGLE).value<qint32>(); }
    void   setColorRectangle(QColor color)    { qsettings.setValue( lsa::QSETTINGS_COLOR_RECTANGLE, color ); }
    void   setLineWidthRectangle(int width)   { qsettings.setValue( lsa::QSETTINGS_LINEWIDTH_RECTANGLE, width ); }
    void   setPenStyleRectangle(qint32 style) { qsettings.setValue( lsa::QSETTINGS_PENSTYLE_RECTANGLE, style ); }

    // Highlighting
    QColor getColorHighlighting() { return qsettings.value( lsa::QSETTINGS_COLOR_HIGHLIGHT, lsa::DEFAULT_COLOR_HIGHLIGHT).value<QColor>(); }
    void setColorHighlighting(QColor color) { qsettings.setValue( lsa::QSETTINGS_COLOR_HIGHLIGHT, color ); }

    /// Sets all style variables (but not placemark style objects) to the default values
    /// call updateStyles() after this function to push style changes to the style objects
    void useDefaultStyle();

    void copyOutputPositionsFromGuiModel();
    void initMapAdjustedCoordinates();
    void initMapInitialCoodinates();

    /// calculate the center point and zoom level that displays all points on the map and set the home button
    /// behavior accordingly, then go to the home location
    void setHome(bool openingProject=false);

    double calculateEllipseScaling();
    double calculateEllipseScaling(double maxAxisLengthMeters);

public slots:

    void pushOptionsDialog();

    ///< Displays the options dialog
    void handleMapOptionsTriggered();

    void redraw(); ///< Adds and removes the document from the map's tree view in order to refresh the map display

    void handleSelectionChanged(QItemSelection selected = QItemSelection(), QItemSelection deselected = QItemSelection());
    void handleGuiModelRowsInserted(QModelIndex parentIndex, int first, int last);
    void handleGuiModelRowsAboutToBeRemoved(QModelIndex parentIndex, int first, int last);
    void handleGuiModelDataChanged();
    void handleRadioInitialClicked();
    void handleRadioAdjustedClicked();
    void closeEvent(QCloseEvent *event);

signals:

    /// emitted whenever a point or measurement is selected
    void selectionChanged(QItemSelection,QItemSelection);

    /// emitted whenever a point's location is moved on the map by the user
    void pointCoordinatesChanged(QModelIndex);

    void signalSuppressGuiUpdates(bool);

    void pushWarning(QString message);

    void closing();

private slots:

    void lmbHandler(qreal, qreal, GeoDataCoordinates::Unit);  ///< determines whether a left click on the map should be used for selecting a new point or setting the coordinates of an a priori point

    /// Given a left mouse click at a certain point, determine what measurement the user meant to click and highlight that: if there are multiple such measurements display a menu with them listed
    /// @param centerPoint the point that the user clicked on in coordinates relative to the marbleWidget (ui->map)
    void updateSelection(const QPointF& centerPoint);

    /// When the user right clicks on a point, display a context menu asking the user if they want to move the given point
    /// @todo only allow the user to move a prori points
    void showContextMenu(const QPoint& pos);

    /// These slots call update() when a checkbox hiding or showing measurements is clicked
    void handlePOSG_Clicked() { updatePlacemarkHighlighting(); updatePlacemarkVisibility(); redraw(); setHomeKeepCurrentView(); }
    void handlePOSC_Clicked() { updatePlacemarkHighlighting(); updatePlacemarkVisibility(); redraw(); setHomeKeepCurrentView(); }

    void handleDXYZ_Clicked() { updatePlacemarkHighlighting(); updatePlacemarkVisibility(); redraw(); }
    void handleDIST_Clicked() { updatePlacemarkHighlighting(); updatePlacemarkVisibility(); redraw(); }
    void handleHANG_Clicked() { updatePlacemarkHighlighting(); updatePlacemarkVisibility(); redraw(); }
    void handleHDIR_Clicked() { updatePlacemarkHighlighting(); updatePlacemarkVisibility(); redraw(); }
    void handleZANG_Clicked() { updatePlacemarkHighlighting(); updatePlacemarkVisibility(); redraw(); }
    void handleAZIM_Clicked() { updatePlacemarkHighlighting(); updatePlacemarkVisibility(); redraw(); }
    void handleHDIF_Clicked() { updatePlacemarkHighlighting(); updatePlacemarkVisibility(); redraw(); }
    void handleVANG_Clicked() { updatePlacemarkHighlighting(); updatePlacemarkVisibility(); redraw(); }
    void handleRR_Clicked();
    void handleEllipses_Clicked();


    /// toggles the map layer
    void handleCheckDisplayMapLayerClicked();


    /// Redraws ellipses.  Called every time update() is called and when the zoom level is changed
    /// Automatically draws ellipses to a constant pixel size independent of map zoom leveladdPlacemark_Point
    /// Returns true if ellipses were redrawn
    bool redrawEllipses(bool exportingKML = false);

    /// Redraws rectangles.  Called every time update() is called and when the zoom level is changed
    /// Automatically draws rectangles to a constant pixel size independent of map zoom leveladdPlacemark_Point
    /// Returns true if rectangles were redrawn
    bool redrawRectangles(bool exportingKML = false);

    /// Event handler for map zoom change which will call the appropriate slots
    void handleZoomChange();

    /// Called by handleZoomChange to check whether the theme should be switched for zooming
    void adaptiveZoomThemeHandler();

    /// This is a workaround to fix the following bugs:
    /// Bug 1010 - Calculating Adjustment incorrectly jumbles point labels/icons
    /// Bug 998 - TP point icons and labels rendered incorrectly when alternating between "Initial" and "Adjustment" views
    /// This toggles the map layer and then resets it
    void refreshMapLayer();

    void on_checkEllipseAutoscale_clicked();                ///< enables or disables ellipse autoscaling
    void on_doubleEllipseScale_valueChanged(double arg1);   ///< updates the ellipse scaling when a new scale is entered
    void handleSliderMoved(int action);
    void handleSliderReleased();

    void handleEnableDisableClicked();

    void resizeEvent(QResizeEvent *event);

private:

    GuiModel* guiModel; ///< the current GuiModel, set using setModel()
    bool &modelIsSaved; ///< whether the GuiModel has been saved, set in the constructor
    double ellipseConfidenceFactor2D;  /// 2D confidence factor based on F distribution lookup and other things
    double ellipseBarConfidenceFactor1D;  /// 1D confidence factor based on F distribution lookup and other things

    bool isTypeVisible(LSAType lsaType);
    int lastPointsSize; ///used to determine whether or not to call setHome when adding points

    bool suppressZoomUpdates;
    bool currentlyShowingInitialCoordinates;

    bool suppressGuiUpdates(bool value);


    /// Clears all of Mapping's internal data structures and recreates
    /// them from the current lsaModel
    void initModel();
    void initPlacemarks();
    void initFolders();
    void initModelPreserveZoom();

    void updateIconPathsKML(QString); /// Updates the icon paths to relative paths inside of the exported KML file
    void createKMZDir(QString); /// Creates the KMZ directory structure for exporting a KML with embedded icons
    void addLabelsKML(); /// Adds labels to the measurements and the ellipse parts for the KML file
    void addDescriptionsToPoints(AdjustedPositions*); /// Adds descriptions to the points for the KML file
    QString generateDescriptionText(AdjustedPositions * adjustedPositions, const QStandardItemModel *pointsModel,
                                    const GeoDataPlacemark *specPointFolder) const; /// Generates text description for points (POSG, POSC, and derived)
    void resetLabels(); /// Removes the measurement and ellipse part labels after exporting the KML file
    void resetDescriptionsForPoints(); /// Removes the descriptions from the points after exporting the KML file

    /// Adds a point with the given label, coordiante, and status and associated with the specified record
    /// @param label        The name associated with the point; will be displayed on the map
    /// @param coordiante   The latitude and longitude of the point
    /// @param index        The QModelIndex assocated with the created placemark in the QMap placemarkToRecordIndex
    /// @param pointStatus  Describes how fixed in place the point is along with whether it is highlighted or not
    /// @see FixedStatus
    void addPlacemark_Point(QString label, const GeoDataCoordinates &coordiante, const QModelIndex &index, IconType fixedStatus, HighlightStatus highlightStatus);

    /// Adds a line between the specified coordiantes and status associated with the specified record
    /// @param from     The coordiante the line begins at
    /// @param to       The coordiante the line ends at
    /// @param index    The QModelIndex associated with the created placemark in the QMap placemarkToRecordIndex
    /// @param status   Whether the line should have its highlight visible or not initially
    void addPlacemark_Line(const GeoDataCoordinates &from, const GeoDataCoordinates& to, const QModelIndex &index, HighlightStatus status);

    /// Adds an ellipse with the given center positoin calculated from the given covariance matrix
    /// @param centerPosition   The center point of the ellipse given in latitude and longitude
    /// @param cov              The covariance matrix
    /// @note This function should only be called from redrawEllipses()
    void addPlacemark_EllipseFromCovariance(std::string ellipseName, QModelIndex index, const GeoDataCoordinates &centerPosition, qreal covNN, qreal covNE, qreal covNU,
                                            qreal covEE, qreal covEU, qreal covUU, qreal scale);

    /// Adds a rectangle with the given center position
    /// @param centerPosition The center point of the rectangle given in lat & lon
    /// @param maj2Drr        The length of the semi-major axis (length = 2*maj2Drr)
    /// @param min2Drr        The length of the semi-minor axis (width = 2*min2Drr)
    /// @param verticalRR     The vertical (U in ENU) component of the the reliability rectangle
    /// @param angle          The angle of rotation of the rectangle
    void addPlacemark_Rectangle(std::string rectangleName, QModelIndex pointIndex, const GeoDataCoordinates &centerPosition, qreal maj2Drr,
                                         qreal min2Drr, qreal verticalRR, qreal angle, qreal scale);

    /// Adds an angle with vertex at 'at' and an angle symbol (arc) with an arrow pointing from 'from' to 'to', associated with the given record and having the given status
    /// @param from     The coordinate where the angle starts at
    /// @param at       The coordinate the of the angle's vertex
    /// @param to       The coordinate where the angle ends at
    /// @param index    The QModelIndex associated with the created placemarks in the QMap placemarkToRecordIndex
    /// Note: addAngle() creates two placemarks: an arc as previously described, and reference lines beginning at 'from' and ending at 'to'. Each placemark has its own highlight placemark.
    void addPlacemark_Angle(const GeoDataCoordinates &from, const GeoDataCoordinates &at, const GeoDataCoordinates &to, const QModelIndex &index, HighlightStatus status);

    /// A static method that creates the geometry of an angle's arc
    /// @param from     The coordinate where the angle starts at
    /// @param at       The coordinate the of the angle's vertex
    /// @param to       The coordinate where the angle ends at
    /// @return A pointer to the line string geometry representing the ellipse.  This pointer is created on the heap,
    ///         but if the geometry is added to a placemark the pointer is deleted automatically whenever document->clear() is called
    static GeoDataLineString* createAngle(const GeoDataCoordinates &from, const GeoDataCoordinates &at, const GeoDataCoordinates &to);

    /// A static method that creates the geometry of an ellipse
    /// @param centerPosition   The center point of the ellipse given in latitude and longitude
    /// @param width            The length of the axis of the ellipse in the x (longitude) direction before it is rotated, must be in the same linear unit as height
    /// @param height           The length of the axis of the ellipse in the y (latitude) direction before it is rotated, must be in the same linear unit as width
    /// @param angle            The standard position angle in radians through which the ellipse is rotated
    /// @return A pointer to the line string geometry representing the ellipse.  This pointer is created on the heap,
    ///         but if the geometry is added to a placemark the pointer is deleted automatically whenever document->clear() is called
    static GeoDataLinearRing* createEllipse(const GeoDataCoordinates &centerPosition, qreal width, qreal height, qreal angle);

    /// A static method that creates the geometry of a rectangle
    /// @param centerPosition   The center point of the rectangle in latitude and longitude
    /// @param maj2Drr          The length of the rectangle (length=2*NA or 2*maj2Drr)
    /// @param min2Drr          The width of the rectangle (width = 2*NB or 2*point.min2Drr)
    /// @param angle            The standard position angle in radians through which the ellipse is rotated
    /// @return A pointer to the line string geometry representing the ellipse.  This pointer is created on the heap,
    ///         but if the geometry is added to a placemark the pointer is deleted automatically whenever document->clear() is called
    static GeoDataLinearRing* createRectangle(const GeoDataCoordinates &centerPosition, qreal maj2Drr, qreal min2Drr, qreal angle, qreal scale);

    /// A static method that creates the geometry of an ellipse
    /// @param centerPosition   The center point of the ellipse given in latitude and longitude
    /// @param Cnn              The covariance matrix
    /// @param Cne              The covariance matrix
    /// @param Cee              The covariance matrix
    /// @param scale            The conversion between the linear unit of the covariance to degrees latitude
    /// @return A pointer to the line string geometry representing the ellipse.  This pointer is created on the heap,
    ///         but if the geometry is added to a placemark the pointer is deleted automatically whenever document->clear() is called
    static GeoDataLinearRing* createEllipseFromCovariance(const GeoDataCoordinates &centerPosition, qreal Cnn, qreal Cne, qreal Cnu,
                                                          qreal Cee, qreal Ceu, qreal Cuu, qreal scaleDegreesPerMeter);

    /// A static method that creates the geometry of an ellipse
    /// @param centerPosition   The center point of the ellipse given in latitude and longitude
    /// @param Cuu              The covariance matrix
    /// @param scale            The conversion between the linear unit of the covariance to degrees latitude
    /// @return A pointer to the Placemark to be added to the ellipse to signify vertical uncertainty
    GeoDataLineString* createEllipseHeightFromCovariance(const GeoDataCoordinates &centerPosition, qreal Cuu, qreal scale);

    /// A static method that creates the geometry of a rectangle
    /// @param centerPosition   The center point of the ellipse given in latitude and longitude
    /// @param vertRR           The vertical component of the reliability rectnagle
    /// @param scale            The conversion between the linear unit of the covariance to degrees latitude
    /// @return A pointer to the Placemark to be added to the ellipse to signify vertical uncertainty
    GeoDataLineString* createRectangleHeight(const GeoDataCoordinates &centerPosition, qreal vertRR, qreal scale);

    /// A static method that returns the major axis length of an error ellipse generated with the given covariance matrix elements
    /// @param covNN The square of the sigma in the north direction
    /// @param covNE The product of the sigma in the north direction and the sigma in the east direction
    /// @param covEE The square of the sigma in the east direction
    /// @return The length of the major axis of the error ellipse from the given covariance matrix
    qreal majorAxisLength(qreal covNN, qreal covNE, qreal covEE);

    /// The following methods add a given record to the map
    void addDerived(QModelIndex index);
    void addPOSG(QModelIndex index);
    void addPOSC(QModelIndex index);
    void addDIST(QModelIndex index);
    void addDXYZ(QModelIndex index);
    void addHANG(QModelIndex index);
    void addAZIM(QModelIndex index);
    void addZANG(QModelIndex index);
    void addHDIF(QModelIndex index);
    void addHDIR(QModelIndex index);
    void addVANG(QModelIndex index);
    void addDGRP(QModelIndex index);

    IconType getPointFixedStatus(QModelIndex index);    ///< @return the fixed status of a point
    HighlightStatus getHighlightStatus(QModelIndex index); ///< @return whether a given measurement should be highlighted initially

    /// Clears all points and lines from the map, ass well as all other internal data structures
    /// If any container class is filled in update(), it should be cleared here
    void clear();

    /// Unhighlights all points and measurements
    void unHighlightAll();
    void unHighlightPlacemarksForIndex(QModelIndex index);

    /// Highlight the given placemark
    void highlight(QModelIndex index, GeoDataPlacemark* placemark);
    void updatePlacemarkVisibility();
    void updatePlacemarkHighlighting();
    void updatePlacemarksForIndex(QModelIndex index);

    void updatePlacemarksReferencingPosition(QModelIndex index);

    /// Finds all placemarks "near" to the given point
    /// @param centerPoint          The point around which the method looks for placemarks
    /// @param givePointsPriority   An optional parameter (defaults to false) that if set to true only searches for points if any points are in range of centerPoint
    /// @return A QVector (possibly empty) of all of the placemarks found near centerPoint
    QMap<QModelIndex, GeoDataPlacemark *> findAllNear(const QPointF &centerPoint, bool givePointsPriority=false);

    /// Returns true if one segment the line string geometry of the given placemark is within radius pixels of centerPoint, false otherwise
    /// @param centerPoint The test point
    /// @param placemark A pointer to the placemark with a line string geometry
    /// @param radius The radius in pixels around centerPoint that a segment of placemark's line string geometry must be in order for the method to return true
    /// @return Whether centerPoint is within radius pixes of any segment of placemark's line string geometry
    bool isNearEnough_Line(const QPointF &centerPoint, GeoDataPlacemark* placemark, qreal radius);

    static qreal distance(qreal x1, qreal y1, qreal x2, qreal y2);  ///< @return The cartesian distance between the points (x1, y1) and (x2, y2)
    static qreal distance(const QPointF &point1, const QPointF &point2);          ///< @return The cartesian distance between the points point1 and point2

    void appendPlacemark(GeoDataPlacemark* placemark, GeoDataDocument *doc); ///< Removes the document from the tree model, appends a placemark to the document, and adds the document to the tree model

    static GeoDataCoordinates getCoordinateFromPOSG(LSAPosG* point);  ///< @return the GeoDataCoordiante from the given POSG record
    static GeoDataCoordinates getCoordinateFromPOSC(LSAPosC* point);  ///< @return the GeoDataCoordiante from the given POSC record

    /// Returns whether or not an initial coordinate exists for the given point label.  This should be true before calling getInitialCoordinateFromLabel() with the given string.
    /// @param str The label of the point
    /// @return True if an initial coordinate exists for the given label, False if it does not exist.
    bool initialCoordinateExists(std::string str);

    /// Returns whether or not a final coordinate exists for the given point label.  This should be true before calling getFinalCoordinateFromLabel() with the given string.
    /// @param str The label of the point
    /// @return True if an final coordinate exists for the given label, False if it does not exist.
    bool adjustedCoordinateExists(std::string str);

    /// Returns whether or not a final OR intial coordinate exists for the given point label.  This should be true before calling getCoordinateFromLabel() with the given string.
    /// @param str The label of the point
    /// @return True if an final coordinate exists for the given label, False if it does not exist.
    /// @note This is equivalent to initialCoordinateExists() || finalCoordinateExists()
    bool coordinateExists(std::string label);

    /// Returns the coordinate corresponding to the given point label, prioritizing final coordinates if ui->radioDisplayOutput is checked
    /// This function is the prefered way to get coordinates for a point because it follows the user's choice of output vs. input
    /// @param str The label of the point
    /// @return The coordinate cooresponding to the given point label
    /// @note The coordinate will only be vaild if a coordinate exists, call coordinateExists() to check
    GeoDataCoordinates getCoordinatesFromLabel(std::string str);

    GeoDataCoordinates getCoordinatesFromIndex(QModelIndex index);

    /// Returns the initial coordinate corresponding to the given point label
    /// @param str The label of the point
    /// @return The initial coordinate cooresponding to the given point label
    /// @note The coordinate will only be vaild if an initial coordinate exists, call initialCoordinateExists() to check
    GeoDataCoordinates getInitialCoordinateFromLabel(std::string str);

    /// Returns the final coordinate corresponding to the given point label
    /// @param str The label of the point
    /// @return The final coordinate cooresponding to the given point label
    /// @note The coordinate will only be vaild if a final coordinate exists, call finalCoordinateExists() to check
    GeoDataCoordinates getFinalCoordinateFromLabel(std::string str);

    /// Converts a latitude and direction into a signed latitude and normalizes it (puts it in the correct range)
    /// @param lat The latitude to have its sign set
    /// @param latDir The direction of lat
    /// @return The normalization of -lat if the first character of latDir is 'S', the normalization of lat otherwise
    static qreal latFromLatDir(qreal lat, std::string latDir);

    /// Converts a longitude and direction into a signed longitude and normalizes it (puts it in the correct range)
    /// @param lon The longitude to have its sign set
    /// @param lonDir The direction of lon
    /// @return The normalization of -lon if the first character of lonDir is 'W', the normalization of lon otherwise
    static qreal lonFromLonDir(qreal lon, std::string lonDir);

    QPointF pointFromCoordinate(const GeoDataCoordinates &coor);   ///< @return the point on the screen corresponding to the given point on the map
    GeoDataCoordinates coordinateFromPoint(const QPointF &point);  ///< @return the point on the map corresponding to the given point on the screen

    static qreal lonScaleFactor(qreal lat, GeoDataCoordinates::Unit unit);  ///< @return the scale factor that when multiplied by degrees latitude gives degrees longitude at a given latitude

    /// sets the map theme to a theme that has map tiles
    void showBackgroundMap();

    /// sets the map theme to a theme that does not have map tiles
    void hideBackgroundMap();

    /// Hides controls on the Marble Widget we don't use
    /// Should be called after every time the map theme is set
    void configureMap();

    qreal getDegLatPerPixel(); ///< @return the average number of pixels in one degree of latitude for the current map location and zoom level

    qreal getMapDiagonalPixels(); ///< @return the length of the map's diagonal in pixels

    void setHomeKeepCurrentView(); ///< calculate the center point and zoom level that displays all points on the map and set the home button behavior accordingly, but keep the current center location and zoom

    qreal getMaxAxisLengthMeters(); ///< @return the maximum axis length (in meters) of all error ellipses before scaling

    void updateStyles(); ///< Sets all style objects (GeoDataSyle) to match the color, line width, and pen style member variables for each style

    /// Calculates the appropriate width of a highlight placemark given the width of the placemark to be highlighted.
    /// This function exists to force consistent highlight widths.
    qint32 getHighlightWidth(qint32 width) { return width * 2 + 1; }

    /// Sets the visible property of all scale control widgets to the value of visible.
    /// @param visible Whether the scale control widgets are to be visible.
    void setScaleControlsVisible(bool visible);

    void insertPlacemarkFromIndex(QModelIndex index);
    void removePlacemark(QModelIndex index);

    /// Disable the map and push a warning to the status window
    void disableMap();

    static bool sortManner(GeoDataFeature *lhPlacemark, GeoDataFeature *rhPlacemark);
    void sortPointsInFolders();

    /// holds the MarbleWidget and associated widgets
    Ui::Mapping *ui;

    /// holds point and measurement placemarks for display
    GeoDataDocument mainDocument;

    /// these variables hold the styles for fixed, partially fixed, and
    /// floating points (the survey term, not the type)
    QSharedPointer<Marble::GeoDataStyle> styleFixed1;
    QSharedPointer<Marble::GeoDataStyle> styleFixed2;
    QSharedPointer<Marble::GeoDataStyle> styleFixedAll;
    QSharedPointer<Marble::GeoDataStyle> styleFloating;
    QSharedPointer<Marble::GeoDataStyle> styleDerived ;
    QSharedPointer<Marble::GeoDataStyle> styleConstrain;
    QSharedPointer<Marble::GeoDataStyle> styleAPriori;

    QSharedPointer<Marble::GeoDataStyle> styleFixed1Highlighted;
    QSharedPointer<Marble::GeoDataStyle> styleFixed2Highlighted;
    QSharedPointer<Marble::GeoDataStyle> styleFixedAllHighlighted;
    QSharedPointer<Marble::GeoDataStyle> styleFloatingHighlighted;
    QSharedPointer<Marble::GeoDataStyle> styleDerivedHighlighted;
    QSharedPointer<Marble::GeoDataStyle> styleConstrainHighlighted;
    QSharedPointer<Marble::GeoDataStyle> styleAPrioriHighlighted;

    /// these variables hold the icon styles for fixed, partially fixed, and
    /// floating points (the survey term, not the type)
    GeoDataIconStyle iconStyleFixed1;
    GeoDataIconStyle iconStyleFixed2;
    GeoDataIconStyle iconStyleFixedAll;
    GeoDataIconStyle iconStyleFloating;
    GeoDataIconStyle iconStyleDerived;
    GeoDataIconStyle iconStyleConstrain;
    GeoDataIconStyle iconStyleAPriori;

    GeoDataIconStyle iconStyleFixed1Highlighted;
    GeoDataIconStyle iconStyleFixed2Highlighted;
    GeoDataIconStyle iconStyleFixedAllHighlighted;
    GeoDataIconStyle iconStyleFloatingHighlighted;
    GeoDataIconStyle iconStyleDerivedHighlighted;
    GeoDataIconStyle iconStyleConstrainHighlighted;
    GeoDataIconStyle iconStyleAPrioriHighlighted;

    /// measurement styles
    QSharedPointer<Marble::GeoDataStyle> DISTStyle;
    QSharedPointer<Marble::GeoDataStyle> DISTStyleHighlighted;
    QSharedPointer<Marble::GeoDataStyle> DXYZStyle;
    QSharedPointer<Marble::GeoDataStyle> DXYZStyleHighlighted;
    QSharedPointer<Marble::GeoDataStyle> ZANGStyle;
    QSharedPointer<Marble::GeoDataStyle> ZANGStyleHighlighted;
    QSharedPointer<Marble::GeoDataStyle> HDIRStyle;
    QSharedPointer<Marble::GeoDataStyle> HDIRStyleHighlighted;
    QSharedPointer<Marble::GeoDataStyle> HDIFStyle;
    QSharedPointer<Marble::GeoDataStyle> HDIFStyleHighlighted;
    QSharedPointer<Marble::GeoDataStyle> VANGStyle;
    QSharedPointer<Marble::GeoDataStyle> VANGStyleHighlighted;

    QSharedPointer<Marble::GeoDataStyle> AZIMStyle;
    QSharedPointer<Marble::GeoDataStyle> AZIMStyleHighlighted;
    QSharedPointer<Marble::GeoDataStyle> AZIMReferenceLineStyle;
    QSharedPointer<Marble::GeoDataStyle> AZIMReferenceLineStyleHighlighted;
    QSharedPointer<Marble::GeoDataStyle> HANGStyle;
    QSharedPointer<Marble::GeoDataStyle> HANGStyleHighlighted;
    QSharedPointer<Marble::GeoDataStyle> HANGReferenceLineStyle;
    QSharedPointer<Marble::GeoDataStyle> HANGReferenceLineStyleHighlighted;
    QSharedPointer<Marble::GeoDataStyle> ellipseStyle;
    QSharedPointer<Marble::GeoDataStyle> rectangleStyle;

    /// measurement line styles
    GeoDataLineStyle DISTLineStyle;
    GeoDataLineStyle DISTLineStyleHighlighted;
    GeoDataLineStyle DXYZLineStyle;
    GeoDataLineStyle DXYZLineStyleHighlighted;
    GeoDataLineStyle ZANGLineStyle;
    GeoDataLineStyle ZANGLineStyleHighlighted;
    GeoDataLineStyle HDIRLineStyle;
    GeoDataLineStyle HDIRLineStyleHighlighted;
    GeoDataLineStyle HDIFLineStyle;
    GeoDataLineStyle HDIFLineStyleHighlighted;
    GeoDataLineStyle VANGLineStyle;
    GeoDataLineStyle VANGLineStyleHighlighted;

    GeoDataLineStyle AZIMLineStyle;
    GeoDataLineStyle AZIMLineStyleHighlighted;
    GeoDataLineStyle AZIMReferenceLineLineStyle;
    GeoDataLineStyle AZIMReferenceLineLineStyleHighlighted;
    GeoDataLineStyle HANGLineStyle;
    GeoDataLineStyle HANGLineStyleHighlighted;
    GeoDataLineStyle HANGReferenceLineLineStyle;
    GeoDataLineStyle HANGReferenceLineLineStyleHighlighted;

    GeoDataLineStyle ellipseLineStyle;
    GeoDataPolyStyle ellipsePolyStyle;

    GeoDataLineStyle rectangleLineStyle;
    GeoDataPolyStyle rectanglePolyStyle;

    /// Containers for all of the different types of placemarks so they can be queried independently
    QMap<QPersistentModelIndex, GeoDataPlacemark*> points; // all enabled points in the project
    QMap<QPersistentModelIndex, GeoDataPlacemark*> lines;
    QMap<QPersistentModelIndex, GeoDataPlacemark*> lineHighlights; // container for features added temporarily, such as a result of element highlighting
    QMap<QPersistentModelIndex, GeoDataPlacemark*> angles;
    QMap<QPersistentModelIndex, GeoDataPlacemark*> angleHighlights;
    QMap<QPersistentModelIndex, GeoDataPlacemark*> angleReferenceLines;
    QMap<QPersistentModelIndex, GeoDataPlacemark*> angleReferenceLineHighlights;
    QMap<QPersistentModelIndex, GeoDataPlacemark*> ellipses;
    QMap<QPersistentModelIndex, GeoDataPlacemark*> ellipseVerticalBars;
    QMap<QPersistentModelIndex, GeoDataPlacemark*> rectangles;
    QMap<QPersistentModelIndex, GeoDataPlacemark*> rectangleVerticalBars;

    /// Containers for KML export
    Marble::GeoDataFolder *pointsFolder;
    Marble::GeoDataFolder *POSGFolder;
    Marble::GeoDataFolder *POSCFolder;
    Marble::GeoDataFolder *derivedPointsFolder;
    Marble::GeoDataFolder *meanFolder;
    Marble::GeoDataFolder *enuoFolder;
    Marble::GeoDataFolder *ellipseFolder;
    Marble::GeoDataFolder *measurementFolder;
    Marble::GeoDataFolder *DISTFolder;
    Marble::GeoDataFolder *DXYZFolder;
    Marble::GeoDataFolder *HANGFolder;
    Marble::GeoDataFolder *VANGFolder;
    Marble::GeoDataFolder *ZANGFolder;
    Marble::GeoDataFolder *AZIMFolder;
    Marble::GeoDataFolder *HDIFFolder;
    Marble::GeoDataFolder *HDIRFolder;
    Marble::GeoDataFolder *AnglesFolder;
    Marble::GeoDataFolder *highlightsFolder;///this folder will be removed before kml export
    Marble::GeoDataFolder *rectangleFolder;

    QMap<GeoDataPlacemark*, QPersistentModelIndex>      placemarkToIndexMap; ///< One-to-Many map of placemarks to indexes
    QMultiMap<QPersistentModelIndex, GeoDataPlacemark*> indexToPlacemarkMap; ///< Many-to-One map of indexes to placemarks

    bool isPointMoving;                 ///< Whether the next left mouse click should be associated with moving a point
    GeoDataPlacemark* movingPlacemark;  ///< The placemark affected by a left mouse click while isPointMoving is true

    QMap<QString, QPersistentModelIndex> pointIndexMap;          ///< A map between a point's label and its QModelIndex (only for enabled points)
    QMap<QString, QPersistentModelIndex> dirGroupIndexMap;       ///< A map between a dirGroup's label and its QModelIndex
    QMap<QString, FinalAdjustedPosition> finalPointMap;          ///< A map between a point's label and its FinalAdjustedPosition struct

    qreal currentEllipseFractionOfDiagonal; ///< The current fraction of the window diagonal at which the largest error ellipse major axis is displayed

    QString configPath;

    bool highScrollZoomEnabled;

};

#endif // MAPPING_HPP
