/*
	Copyright (c) 2015-2024 Applied Research Laboratories, The University of Texas
	at Austin (ARL:UT).
	
	SALSA is free software: you can redistribute it and/or modify it under the
	terms of the GNU General Public License version 3 (GPL-3.0-only) as published
	by the Free Software Foundation.
	
	SALSA is distributed in the hope that it will be useful, but WITHOUT ANY
	WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
	A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License along with
	SALSA.  If not, see https://www.gnu.org/licenses/.
*/
#ifndef RECORDEDITOR_H
#define RECORDEDITOR_H

// disable some MSVC compiler warnings
#pragma warning(disable:4290)

// GNSSTk
#include <exception>

// Qt
#include <QComboBox>
#include <QDockWidget>
#include <QDoubleSpinBox>
#include <QFileDialog>
#include <QKeyEvent>
#include <QSettings>
#include <QSpinBox>
#include <QCloseEvent>

// lsa
#include <GuiModel.hpp>
#include <LSAFile.hpp>
#include <LSAGuiConstants.hpp>
#include <LSAOperationType.hpp>
#include <ChangeValueCommand.hpp>
#include <QtUtilityMethods.hpp>

namespace Ui
{
    class RecordEditor;
}

/// Class MouseWheelEventFilter filters Qt:Wheel events
class MouseWheelEventFilter : public QObject
{
    Q_OBJECT
protected:
    bool eventFilter(QObject *obj, QEvent *event);  ///< Method which performs filter
};

/// Class RecordEditor displays and edits the data contained in an individual LSARecord.
class RecordEditor : public QDockWidget
{
    Q_OBJECT

     friend class TestLSAGui; ///< Test harness class used to execute gui unit and integration tests
     friend class Benchmarks; ///< Test harness class used to execute gui unit and integration tests

public:

    // Constructor and Destructor
    /// Constructor given an lsaModel, reference to saveLSAFlag and parent
    /// @param lsaModel point to the current LSAModel used by the MainWindow
    /// @param saveLSARecord reference to bool member in MainWindow that indicates the LSA file needs to be saved before running the solver
    /// @param parent parent widget for this widget
    explicit RecordEditor(GuiModel* guiModel, QWidget *parent = 0);

    /// Destructor
    ~RecordEditor();

    /// Set the current lsamodel used by the MainWindow.  Also sets some child pointers to items inside the LSAModrl
    /// @param newModel pointer to the new LSAModel object
    void setGuiModel(GuiModel* newModel);

    // Detail Widget methods
    /// Update the widget based on the current contents of the MainWindow GuiModel
    void update();

    /// Push values that the user has changed in controls back into the current LSARecord.  The MainWindow calls this method
    /// when focus changes from a widget that is a child of RecordEditor to a widget that is not a child of RecordEditor.
    void pushChangesToGuiModel();

    bool suppressRecordEditorUpdates; ///< used to ignore changed controls when binding refreshing the RecordEditor

    void prepareToEditNewRecord();
    void prepareToEditSeparatorBar();
    bool hasPendingChanges();

private:
    Ui::RecordEditor *ui; ///< pointer to ui containing designer controls generated by the Qt framework

    GuiModel *guiModel; ///< pointer to the current Gui Model in use by the MainWindow

    // Current LSA Record, type and modifier
    QModelIndex     currentIndex;     ///< index for the currently selected record
    QModelIndexList selectedRows;
    LSARecord      *currentLSARecord; ///< pointer to the current LSARecord selected in the treeview and map widget
    LSAType         currentLSAType;          ///< LSAType for currentLSARecord
    LSAModifier    *currentModifier;  ///< Pointer to the LSAModifier object associated with currentLSARecord

    // Maps to various record types
    LSARecordMap   *pointMap;    ///< Pointer to map of lsa points
    LSAHGHTMap     *heightMap;   ///< Pointer to map of LSAHeights
    LSAUNCRMap     *uncrMap;     ///< Pointer to map of LSAUncrs
    LSAVSCAMap     *varMap;      ///< Pointer to map of LSAVarScalings
    LSADirGroupMap *dirGroupMap; ///< Pointer to map of LSA direction groups

    MouseWheelEventFilter *wheelFilter;

    // GUI config parameters
    int numDec_DecDeg; ///< Number of digits after decimal to display in decimal degree values
    int numDec_DMS;    ///< Number of digits after decunak to display in DMS values

    // Title of Record Editor window
    const QString baseWindowName = " Record Details";

    void keyPressEvent(QKeyEvent* event);

    bool suppressGuiUpdates(bool value);

    // Top level setup methods
    void configureForSingleRecord();
    void configureForMultipleRecords();
    void configureEnableCheckboxesForMultipleRecords();
    void configureModifierForMultipleRecords();
    void configureConstraintControls();
    void configureHeightStateControl();
    void configureVSCAForMultipleRecords();
    void configureDGRPForMultipleRecords();
    void configureUNCRForMultipleRecords();

    // Control management
    void setControlRanges();    ///< Set the min and max values for numeric controls
    void resetControlStates();  ///< Reset all control states to their initial values
    void setupControls();       ///< Setup all controls based on the contents of currentLSARecord
    void hideControls();        ///< Hide all the controls in the widget

    // Height control methods
    void configureHeightTo();   ///< Configure the HeightTo   controls based on the contents of currentModifier
    void configureHeightFrom(); ///< Configure the HeightFrom controls based on the contents of currentModifier

    void updateHeightTo();      ///< Push values changed in HeightTo   controls back into currentModifier
    void updateHeightFrom();    ///< Push values changed in HeightFrom controls back into currentModifier
    void updateHeightControls(QDoubleSpinBox* doubleValue, QComboBox *comboUnits, const QString &arg1);

    void updateDYXZ_CovENU(double e, double n, double u);
    void modifyLabels(LSAType lsaType, QString oldLabel, QString newLabel);

    void updateUNCR();

    void updateVSCA();
    void updateVSCAControls(const QString &label);

    void handleHeightToChanged();
    void handleHeightFromChanged();

    void handleComboVSCAChanged();

    bool posgControlChanged();
    void checkForEditedAutoGenPoints();

    // Sigma control methods
    void setupHeightControlLabels(QComboBox *selectorControl);
    bool setupMultiHeightControlLabels(QComboBox *selectorControl, std::string Label);
    void setupUncrControlLabels(std::string currentLabel = "");
    void setupCovModControlLabels();
    void setupVSCAControlLabels(std::string currentLabel = "");
    void setupDirGroupControlLabels(std::string dirGroupLabel);

    void configureVSCAControls();
    void configureRefractionControls();
    void configureUNCRControls(std::string uncrLabel = "");

    void configureNumDigits(QDoubleSpinBox *control, LSAType currentLSAType, QString units);

    // DMS to Decimal Degrees conversions
    bool useDMS;
    void convertDMSControlToDecimalDegrees(bool DMSIsNeg, QSpinBox *dmsDeg, QSpinBox *dmsMin, QDoubleSpinBox *dmsSec, QDoubleSpinBox *decimalDegrees);
    void convertDecimalDegreeControlToDMS(QDoubleSpinBox *decDegControl, bool &dmsIsNeg, QPushButton *dmsSignControl, QSpinBox *dmsDegControl, QSpinBox *dmsMinControl, QDoubleSpinBox *dmsSecControl);
    void convertLatLonDMSToDecDeg();
    void convertLatLonDecDegToDMS();
    void convertAngleDMSToDecDeg();
    void convertAngleDecDegToDMS();
    void showLatLonControls();
    void hideAllLatLonControls();

    gnsstk::Triple getLonLatHeightRads(LSARecord* posRec);

    // Configure methods
    void configurePOSC();
    void configurePOSG();
    void configureDXYZ();
    void configureENUO();
    void configureDIST();
    void configureZANG();
    void configureVANG();
    void configureHANG();
    void configureAZIM();
    void configureHDIF();
    void configureDGRP();
    void configureHDIR();
    void configureUNCR();
    void configureVSCA();
    void configureHGHT();
    void configureINCLUDE();
    void configureCOMMENT();
    void configureCONFIG();
    void configureMEAN();


    // Save methods
    void pushChangesToPOSC();
    void pushChangesToPOSG();
    void pushChangesToDXYZ();
    void pushChangesToDIST();
    void pushChangesToZANG();
    void pushChangesToVANG();
    void pushChangesToHANG();
    void pushChangesToAZIM();
    void pushChangesToCOMMENT();
    void pushChangesToCONFIG();
    void pushChangesToHDIF();
    void pushChangesToDGRP();
    void pushChangesToHDIR();
    void pushChangesToUNCR();
    void pushChangesToVSCA();
    void pushChangesToHGHT();
    void pushChangesToINCLUDE();
    void pushChangesToMEAN();
    void pushChangesToENUO();

    void setParentIsModifiedFlag();
    void resetChangeStateTrackers();

    void enableCOVControls(bool enable);
    void enableAllPOSGControls(bool enable);

    // bools to track the state of DMS sign buttons
    bool dmsAngleIsNeg;
    bool latDMSIsNeg;
    bool lonDMSIsNeg;

    // Control state tracking
    bool checkEnabled_Changed;

    bool lineStationA_Changed;
    bool lineStationB_Changed;
    bool lineStationC_Changed;

    bool comboDirGroup_Changed;

    bool useDMS_Changed;

    bool btnLatDMSNeg_Changed;
    bool intLatDMSDeg_Changed;
    bool intLatDMSMin_Changed;
    bool doubleLatDMSSec_Changed;
    bool comboLatDMSNS_Changed;

    bool doubleLatDecDeg_Changed;
    bool comboLatDecDegNS_Changed;

    bool btnLonDMSNeg_Changed;
    bool intLonDMSDeg_Changed;
    bool intLonDMSMin_Changed;
    bool doubleLonDMSSec_Changed;
    bool comboLonDMSEW_Changed;

    bool doubleLonDecDeg_Changed;
    bool comboLonDecDegEW_Changed;

    bool btnAngleNegDMS_Changed;
    bool intAngleDMSDeg_Changed;
    bool intAngleDMSMin_Changed;
    bool doubleAngleDMSSec_Changed;
    bool doubleAngleDecDeg_Changed;

    bool doubleValueA_Changed;
    bool doubleValueB_Changed;
    bool doubleValueC_Changed;
    bool doubleValueD_Changed;

    bool doubleValueA1_Changed;
    bool doubleValueB1_Changed;
    bool doubleValueC1_Changed;

    bool comboValueAUnits_Changed;
    bool comboValueBUnits_Changed;
    bool comboValueCUnits_Changed;

    bool doubleSigma_Changed;
    bool comboSigmaUnits_Changed;
    bool doubleSigmaMEAN_Changed;
    bool comboSigmaUnitsMEAN_Changed;

    bool doubleCovAA_Changed;
    bool doubleCovAB_Changed;
    bool doubleCovAC_Changed;
    bool doubleCovBB_Changed;
    bool doubleCovBC_Changed;
    bool doubleCovCC_Changed;

    bool comboFixedFloat_Changed;
    bool comboPosgHeight_Changed;

    bool checkNorthFixed_Changed;
    bool checkEastFixed_Changed;
    bool checkUpFixed_Changed;

    bool comboHeightTo_Changed;
    bool doubleHeightToValue_Changed;
    bool comboHeightToUnits_Changed;

    bool comboHeightFrom_Changed;
    bool doubleHeightFromValue_Changed;
    bool comboHeightFromUnits_Changed;

    bool doubleVSCA_Changed;
    bool comboVSCA_Changed;

    bool comboUncrModifier_Changed;
    bool checkApplyRefraction_Changed;
    bool doubleRefractiveIndex_Changed;
    bool checkReduced_Changed;
    bool checkCurvature_Changed;
    bool checkOHC_Changed;

    bool textInputPoints_Changed;
    
    bool generalTextNotes_Changed;

signals:
    void exceptionCaught(QString);
    void giveFocusToTreeView();
    void signalSuppressGuiUpdates(bool);
    void replaceInclude(QModelIndex index, QStringList filenames);
    void reloadAfterParseWarning();
    void closing();

public slots:
    void handleGuiModelDataChanged(QModelIndex first, QModelIndex last, QVector<int> roles);
    void handleBtnBrowseClicked();
    void closeEvent (QCloseEvent *event);

private slots:
    // enabled checkbox
    void checkEnabledChanged() { if (!suppressRecordEditorUpdates) {checkEnabled_Changed = true; pushChangesToGuiModel(); } }

    // Station (and other) labels
    void lineStationAChanged() { if (!suppressRecordEditorUpdates) {lineStationA_Changed = true; } }
    void lineStationBChanged() { if (!suppressRecordEditorUpdates) {lineStationB_Changed = true; } }
    void lineStationCChanged() { if (!suppressRecordEditorUpdates) {lineStationC_Changed = true; } }

    // Value A, Value B, Value C
    void doubleValueAChanged() { if (!suppressRecordEditorUpdates) {doubleValueA_Changed = true; } }
    void doubleValueBChanged() { if (!suppressRecordEditorUpdates) {doubleValueB_Changed = true; } }
    void doubleValueCChanged() { if (!suppressRecordEditorUpdates) {doubleValueC_Changed = true; } }
    void doubleValueDChanged() { if (!suppressRecordEditorUpdates) {doubleValueD_Changed = true; } }

    void doubleValueA1Changed() { if (!suppressRecordEditorUpdates) {doubleValueA1_Changed = true; } }
    void doubleValueB1Changed() { if (!suppressRecordEditorUpdates) {doubleValueB1_Changed = true; } }
    void doubleValueC1Changed() { if (!suppressRecordEditorUpdates) {doubleValueC1_Changed = true; } }

    void comboValueUnitsChanged(const QString &arg1);

    // Covariance
    void doubleCovAAChanged() { if (!suppressRecordEditorUpdates) {doubleCovAA_Changed = true; } }
    void doubleCovABChanged() { if (!suppressRecordEditorUpdates) {doubleCovAB_Changed = true; } }
    void doubleCovACChanged() { if (!suppressRecordEditorUpdates) {doubleCovAC_Changed = true; } }
    void doubleCovBBChanged() { if (!suppressRecordEditorUpdates) {doubleCovBB_Changed = true; } }
    void doubleCovBCChanged() { if (!suppressRecordEditorUpdates) {doubleCovBC_Changed = true; } }
    void doubleCovCCChanged() { if (!suppressRecordEditorUpdates) {doubleCovCC_Changed = true; } }
    void comboFixedFloatChanged(QString comboContents);

    // Sigma
    void doubleSigmaChanged()     { if (!suppressRecordEditorUpdates) {doubleSigma_Changed = true;     } }
    void comboSigmaUnitsChanged() { if (!suppressRecordEditorUpdates) {comboSigmaUnits_Changed = true; pushChangesToGuiModel(); } }

    // SigmaMEAN
    void doubleSigmaMEANChanged()     { if (!suppressRecordEditorUpdates) {doubleSigmaMEAN_Changed = true;     } }
    void comboSigmaUnitsMEANChanged() { if (!suppressRecordEditorUpdates) {comboSigmaUnitsMEAN_Changed = true; pushChangesToGuiModel(); } }

    // North, East, Up fixed
    void checkNorthFixedChanged(int);
    void checkEastFixedChanged(int);
    void checkUpFixedChanged(int);

    // Latitude DMS
    void handleBtnLatNegDMSClicked();
    void btnLatDMSNegChanged()    { if (!suppressRecordEditorUpdates) {btnLatDMSNeg_Changed = true ;   } }
    void intLatDMSDegChanged()    { if (!suppressRecordEditorUpdates) {intLatDMSDeg_Changed = true ;   } }
    void intLatDMSMinChanged()    { if (!suppressRecordEditorUpdates) {intLatDMSMin_Changed = true ;   } }
    void doubleLatDMSSecChanged() { if (!suppressRecordEditorUpdates) {doubleLatDMSSec_Changed = true; } }
    void comboLatDMSNSChanged();

    // Latitude decimal degrees
    void doubleLatDecDegChanged()  { if (!suppressRecordEditorUpdates) {doubleLatDecDeg_Changed = true;  } }
    void comboLatDecDegNSChanged();

    // Longitude DMS
    void handleBtnLonNegDMSClicked();
    void btnLonDMSNegChanged()    { if (!suppressRecordEditorUpdates) {btnLonDMSNeg_Changed = true ;   } }
    void intLonDMSDegChanged()    { if (!suppressRecordEditorUpdates) {intLonDMSDeg_Changed = true;    } }
    void intLonDMSMinChanged()    { if (!suppressRecordEditorUpdates) {intLonDMSMin_Changed = true;    } }

    void doubleLonDMSSecChanged() { if (!suppressRecordEditorUpdates) {doubleLonDMSSec_Changed = true; } }
    void comboLonDMSEWChanged();

    // Longitude decimal degrees
    void doubleLonDecDegChanged()  { if (!suppressRecordEditorUpdates) {doubleLonDecDeg_Changed = true;  } }
    void comboLonDecDegEWChanged();

    // Angle DMS and decimal decrees
    void handleBtnAngleNegDMSClicked();
    void intAngleDMSDegChanged()       { if (!suppressRecordEditorUpdates) {intAngleDMSDeg_Changed = true;    } }
    void intAngleDMSMinChanged()       { if (!suppressRecordEditorUpdates) {intAngleDMSMin_Changed = true;    } }
    void doubleAngleDMSSecChanged()    { if (!suppressRecordEditorUpdates) {doubleAngleDMSSec_Changed = true; } }
    void doubleAngleDecDegChanged()    { if (!suppressRecordEditorUpdates) {doubleAngleDecDeg_Changed = true; } }

    // DMS to decimal degrees radio buttons
    void radioUseDMSChanged(bool checked);

    // Height Modifiers
    void comboHeightToChanged()       { if (!suppressRecordEditorUpdates) handleHeightToChanged(); pushChangesToGuiModel();}
    void doubleHeightToValueChanged() { if (!suppressRecordEditorUpdates) handleHeightToChanged(); }
    void comboHeightToUnitsChanged()  { if (!suppressRecordEditorUpdates) { handleHeightToChanged(); pushChangesToGuiModel(); }}

    void comboHeightFromChanged()       { if (!suppressRecordEditorUpdates) handleHeightFromChanged(); pushChangesToGuiModel();}
    void doubleHeightFromValueChanged() { if (!suppressRecordEditorUpdates) handleHeightFromChanged(); }
    void comboHeightFromUnitsChanged()  { if (!suppressRecordEditorUpdates) { handleHeightFromChanged(); pushChangesToGuiModel(); } }

    // Other Modifiers

    void comboUncrModifierChanged()     { if (!suppressRecordEditorUpdates) {comboUncrModifier_Changed = true; pushChangesToGuiModel();} }
    void checkRefractiveIndexChanged(bool isChecked);
    void doubleRefractiveIndexChanged() { if (!suppressRecordEditorUpdates) {doubleRefractiveIndex_Changed = true; pushChangesToGuiModel();} }
    void comboVarianceScalingChanged()  { if (!suppressRecordEditorUpdates) {handleComboVSCAChanged(); } }
    void doubleVSCAChanged()            { if (!suppressRecordEditorUpdates) {doubleVSCA_Changed = true;            } }
    void checkReducedChanged()          { if (!suppressRecordEditorUpdates) {checkReduced_Changed = true; pushChangesToGuiModel();} }
    void checkCurvatureChanged()        { if (!suppressRecordEditorUpdates) {checkCurvature_Changed = true; pushChangesToGuiModel();} }
    void checkOHCChanged()              { if (!suppressRecordEditorUpdates) {checkOHC_Changed = true; pushChangesToGuiModel();} }

    // Points text edit
    void textInputPointsChanged()        { if (!suppressRecordEditorUpdates) {textInputPoints_Changed = true;        } }

    // DirGroup and HDir(point)
    void comboDirGroupChanged() { if (!suppressRecordEditorUpdates) {comboDirGroup_Changed = true; } pushChangesToGuiModel(); }

    // Modifies Record Editor State
    void handleChangeHeightState(QString);
    
    void handleGeneralTextNotesChanged() { generalTextNotes_Changed = true; }
};

#endif // RECORDEDITOR_H
