/*
	Copyright (c) 2015-2024 Applied Research Laboratories, The University of Texas
	at Austin (ARL:UT).
	
	SALSA is free software: you can redistribute it and/or modify it under the
	terms of the GNU General Public License version 3 (GPL-3.0-only) as published
	by the Free Software Foundation.
	
	SALSA is distributed in the hope that it will be useful, but WITHOUT ANY
	WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
	A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License along with
	SALSA.  If not, see https://www.gnu.org/licenses/.
*/
#include "RemoveRecordsCommand.hpp"

// Project includes
#include "GuiModel.hpp"

RemoveRecordsCommand::RemoveRecordsCommand(const QPersistentModelIndex& removeIndex,
                                           bool deleteReferences,
                                           bool moving_initial_coords,
                                           QVector<QVector<IndexRowColumnParentChainItem>> removedIndicesChain,
                                           GuiModel *model) : m_model(model)
{
    m_redoAction = false;
    m_deleteReferences = deleteReferences;
    m_moving_initial_coords = moving_initial_coords;
    m_removedIndicesChain = removedIndicesChain;

    // Build the index/parent->root chain. The matrix for multiple selected records has to be passed in
    // BEFORE record deletion starts or else it tree will no longer be valid
    m_parentChain = m_model->buildSingleIndexChain(removeIndex);

    // Create list of multiple removed indices
    for(auto vectorItem : m_removedIndicesChain)
    {
        m_removedIndices.append(vectorItem[0].index);
    }

    // Assign LSARecord values
    LSARecord* lsaRecord = m_model->getLSARecord(m_parentChain[0].index);
    m_recordType = lsaRecord->getRecType();
    m_isAutogenerated = lsaRecord->isAutogenerated;
    m_isCommented = lsaRecord->isCommented;
    m_recordString = lsaRecord->getSingleLSAString();

    // Include record type handing requires some extra work
    if(m_recordType == LSAType::INCLUDE)
    {
        std::string newString;
        m_model->parseIncludeFilename(m_recordString, newString, m_modifierStrings);
        m_recordString = newString;

        // Save all of the children still in the include record
        LSARecord *includeLSARecord = m_model->getLSARecord(m_parentChain[0].index);
        auto parentInclude = dynamic_cast<LSAInclude*>(includeLSARecord);
        if(parentInclude != NULL)
        {
            auto children = parentInclude->childRecords;
            for(auto child : children)
            {
                m_children.append(child);
            }
        }
    }

    setText("RemoveRecordsCommand");
}

void RemoveRecordsCommand::redo()
{
    // redoAction check is needed because when an undo/redo object is initialized, `redo()` is automatically called.
    // Since the actual change is accomplished in the code before the object is created, this would lead to the action
    // being performed twice and ruining the undo/redo ability.
    if(m_redoAction)
    {
        if (!m_parentChain[0].index.isValid())
        {
            // Refresh the chain to ensure the current index is valid
            m_model->refreshSingleIndexChain(m_parentChain);

            // Don't attempt to remove if index is stil invalid
            if (!m_parentChain[0].index.isValid())
            {
                this->setObsolete(true);
                return;
            }
        }

        // Actually remove the record
        m_model->removeRecord(m_parentChain[0].index, m_deleteReferences, m_moving_initial_coords, true);

        // Sync the model and push appropriate signals
        m_model->refreshAfterUndoRedo(m_parentChain[0].index);

        return;
    }

    m_redoAction = true;
    return;

}

void RemoveRecordsCommand::undo()
{
    if (!m_parentChain[0].parentIndex.isValid())
    {
        // Refresh the chain to ensure the current index is valid
        m_model->refreshSingleIndexChain(m_parentChain);

        // Don't attempt to remove if index is stil invalid
        if (!m_parentChain[0].parentIndex.isValid())
        {
            this->setObsolete(true);
            return;
        }
    }

    m_parentChain[0].index = m_model->insertNewRecord(m_parentChain[0].parentIndex, m_parentChain[0].row, m_recordType, m_recordString, m_isAutogenerated, m_isCommented, true);

    // Check to make sure that the include retains previous modifications
    if(m_recordType == LSAType::INCLUDE)
    {
        LSARecord *lsaRecord = m_model->getLSARecord(m_parentChain[0].index);
        auto parentInclude = static_cast<LSAInclude*>(lsaRecord);
        parentInclude->parseModifiers(m_modifierStrings);
        auto children = parentInclude->childRecords;

        // Remove unmodified versions
        for(auto child : children)
        {
            QModelIndex removeIndex = m_model->getIndexForRecord(child);
            m_model->removeRecord(removeIndex,false,false,true);
        }

        // Add in saved versions
        m_model->insertNewRecords(m_parentChain[0].index, 0, m_children, true);
    }

    if(m_removedIndices.size() > 1)
    {
        QModelIndexList indicesToSelect;
        m_model->refreshMultipleIndicesChain(m_removedIndicesChain);
        for(int i = 0; i < m_removedIndices.size(); i++)
        {
            m_removedIndices[i] = m_removedIndicesChain[i][0].index;
            indicesToSelect.append(m_removedIndices[i]);
        }
        m_model->select(indicesToSelect);
    }
    else
    {
        m_model->select(m_parentChain[0].index);
    }

    m_model->setIsRootModified(true);

    // Sync the model and push appropriate signals
    m_model->refreshAfterUndoRedo(m_parentChain[0].index);

    return;
}
