/*
	Copyright (c) 2015-2024 Applied Research Laboratories, The University of Texas
	at Austin (ARL:UT).
	
	SALSA is free software: you can redistribute it and/or modify it under the
	terms of the GNU General Public License version 3 (GPL-3.0-only) as published
	by the Free Software Foundation.
	
	SALSA is distributed in the hope that it will be useful, but WITHOUT ANY
	WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
	A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License along with
	SALSA.  If not, see https://www.gnu.org/licenses/.
*/

#ifndef REMOVERECORDSCOMMAND_H
#define REMOVERECORDSCOMMAND_H

// Qt
#include <QUndoCommand>
#include <QModelIndex>
#include <LSARecord.hpp>

#include<GuiModelItem.hpp>

class GuiModel;

class RemoveRecordsCommand : public QUndoCommand
{
public:
  RemoveRecordsCommand(const QPersistentModelIndex& removeIndex,
                       bool deleteReferences,
                       bool moving_initial_coords,
                       QVector<QVector<IndexRowColumnParentChainItem>> removedIndicesChain,
                       GuiModel *model);

  void redo() Q_DECL_OVERRIDE;
  void undo() Q_DECL_OVERRIDE;

private:
  GuiModel *m_model; // Pointer to our gui model
  bool m_deleteReferences; // Do we delete any references to this record found elsewhere
  bool m_moving_initial_coords; // Is this record being deleted because we moved initial coordinates from autogen
  LSAType m_recordType; // What is the record type of the removed index
  std::string m_recordString; // LSA-formatted record string
  std::vector<std::string> m_modifierStrings; // Modifier string (should be length 1)
  QVector<LSARecord*> m_children; // If the removed index is an include, save the children here
  bool m_isAutogenerated; // Is the record an autogen or "real" record
  bool m_isCommented; // Is the record a comment/disabled

  // Flag that is needed because we already did the removal action and Qt automatically calls redo.
  // Without this it would try to do the remove action twice
  bool m_redoAction;

  // Structures used to map the index->parent->root links
  // Needed to:
  // 1. Validate/refresh the removed index
  // 2. Select all of the removed records upon undo
  // Note: Each RemoveRecordsCommand only removes/inserts a single record,
  // but it keeps an accounting of all record(s) that were removed/inserted for multi-select purposes
  QVector<IndexRowColumnParentChainItem> m_parentChain; // Used to validate the actual removed index
  QVector<QVector<IndexRowColumnParentChainItem>> m_removedIndicesChain; // Used to validate all removed indices for selection
  QList<QPersistentModelIndex> m_removedIndices; // Used to select all removed indices upon undo
};

#endif // REMOVERECORDSCOMMAND_H
