/*
	Copyright (c) 2015-2024 Applied Research Laboratories, The University of Texas
	at Austin (ARL:UT).
	
	SALSA is free software: you can redistribute it and/or modify it under the
	terms of the GNU General Public License version 3 (GPL-3.0-only) as published
	by the Free Software Foundation.
	
	SALSA is distributed in the hope that it will be useful, but WITHOUT ANY
	WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
	A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License along with
	SALSA.  If not, see https://www.gnu.org/licenses/.
*/
#include <limits>
#include <string>
#include <QString>
#ifndef LSACONSTANTS_HPP
#define LSACONSTANTS_HPP

namespace lsa
{
// Set some data required by QSettings
const QString salsaOrgName("ARLUT");
const QString salsaApplicationName("SALSA");
const QString salsaOrgDomain("arlut.utexas.edu");

const std::string CONTROLVALUE_NONE  = "None";
const std::string CONTROLVALUE_VALUE = "Value";
const std::string CONTROLVALUE_FROM  = "From: ";
const std::string CONTROLVALUE_AT    = "At: ";
const std::string CONTROLVALUE_TO    = "To: ";
const std::string CONTROLVALUE_LABEL = "Label: ";
const std::string CONTROLVALUE_MIXED = "(mixed)";

const std::string UNITS_KM = "km";
const std::string UNITS_M = "m";
const std::string UNITS_CM = "cm";
const std::string UNITS_FT = "ft";
const std::string UNITS_SOA = "soa";
const std::string UNITS_DEG = "deg";
const std::string UNITS_RAD = "rad";

const std::string OPTION_ELLIPSOID = "Ellipsoidal";
const std::string OPTION_ORTHOMETRIC = "Orthometric";
const std::string FLAG_ORTHOMETRIC = "ortho";

const std::string PARSE_WARNING = "Parse Warning";

/*
 * Some values have been corrected and others
 * added to correspond to the Salsa Precision Table
 * in correspondence with Issues 31 and 118
 */

const int NUM_DECIMALS_VARIANCE_SCALING = 3;
const int NUM_DECIMALS_COVARIANCE = 3;
const int NUM_DECIMALS_COV_SIGMAS = 1;
const int NUM_DECIMALS_UNCR_PPM = 2;

const int DEFAULT_NUM_DECIMALS_LINEAR_POSITION_METERS = 4;
const int DEFAULT_NUM_DECIMALS_LINEAR_POSITION_KM   = 7;
const int DEFAULT_NUM_DECIMALS_LINEAR_POSITION_CM   = 2;
const int DEFAULT_NUM_DECIMALS_LINEAR_POSITION_FEET = 2;

const int DEFAULT_NUM_DECIMALS_LINEAR_MEASUREMENT_METERS = 5;
const int DEFAULT_NUM_DECIMALS_LINEAR_MEASUREMENT_KM   = 8;
const int DEFAULT_NUM_DECIMALS_LINEAR_MEASUREMENT_CM   = 3;
const int DEFAULT_NUM_DECIMALS_LINEAR_MEASUREMENT_FEET = 3;

const int DEFAULT_NUM_DECIMALS_ANGLE_POSITION_SOA     = 5;
const int DEFAULT_NUM_DECIMALS_ANGLE_POSITION_DEGREES = 9;
const int DEFAULT_NUM_DECIMALS_ANGLE_POSITION_RADIANS = 10;

const int DEFAULT_NUM_DECIMALS_ANGLE_MEASUREMENT_SOA     = 1;
const int DEFAULT_NUM_DECIMALS_ANGLE_MEASUREMENT_DEGREES = 4;
const int DEFAULT_NUM_DECIMALS_ANGLE_MEASUREMENT_RADIANS = 6;

const QString QSETTINGS_NUM_DECIMALS_LINEAR_MEASUREMENT_METERS      = "QSETTINGS_NUM_DECIMALS_LINEAR_MEASUREMENT_METERS";
const QString QSETTINGS_NUM_DECIMALS_LINEAR_MEASUREMENT_KILOMETERS  = "QSETTINGS_NUM_DECIMALS_LINEAR_MEASUREMENT_KILOMETERS";
const QString QSETTINGS_NUM_DECIMALS_LINEAR_MEASUREMENT_CENTIMETERS = "QSETTINGS_NUM_DECIMALS_LINEAR_MEASUREMENT_CENTIMETERS";
const QString QSETTINGS_NUM_DECIMALS_LINEAR_MEASUREMENT_FEET        = "QSETTINGS_NUM_DECIMALS_LINEAR_MEASUREMENT_FEET";

const QString QSETTINGS_NUM_DECIMALS_LINEAR_POSITION_METERS         = "QSETTINGS_NUM_DECIMALS_LINEAR_POSITION_METERS";
const QString QSETTINGS_NUM_DECIMALS_LINEAR_POSITION_KILOMETERS     = "QSETTINGS_NUM_DECIMALS_LINEAR_POSITION_KILOMETERS";
const QString QSETTINGS_NUM_DECIMALS_LINEAR_POSITION_CENTIMETERS    = "QSETTINGS_NUM_DECIMALS_LINEAR_POSITION_CENTIMETERS";
const QString QSETTINGS_NUM_DECIMALS_LINEAR_POSITION_FEET           = "QSETTINGS_NUM_DECIMALS_LINEAR_POSITION_FEET";

const QString QSETTINGS_NUM_DECIMALS_ANGLE_MEASUREMENT_SOA          = "QSETTINGS_NUM_DECIMALS_ANGLE_MEASUREMENT_SOA";
const QString QSETTINGS_NUM_DECIMALS_ANGLE_MEASUREMENT_DEGREES      = "QSETTINGS_NUM_DECIMALS_ANGLE_MEASUREMENT_DEGREES";
const QString QSETTINGS_NUM_DECIMALS_ANGLE_MEASUREMENT_RADIANS      = "QSETTINGS_NUM_DECIMALS_ANGLE_MEASUREMENT_RADIANS";

const QString QSETTINGS_NUM_DECIMALS_ANGLE_POSITION_SOA             = "QSETTINGS_NUM_DECIMALS_ANGLE_POSITION_SOA";
const QString QSETTINGS_NUM_DECIMALS_ANGLE_POSITION_DEGREES         = "QSETTINGS_NUM_DECIMALS_ANGLE_POSITION_DEGREES";
const QString QSETTINGS_NUM_DECIMALS_ANGLE_POSITION_RADIANS         = "QSETTINGS_NUM_DECIMALS_ANGLE_POSITION_RADIANS";

const double ZERO_BOUND = std::numeric_limits<double>::epsilon()*1000.;

const std::string FASTSOLVER_ERRORSTRING = "Error - fast Solver failed ";
const std::string FASTSOLVER_ERRORMEMORYALLOCATE = " Error - failed to allocate memory due to ";

const double DEFAULT_MAX_EXT_MAG_WARNING = 0.15;
const double DEFAULT_MAX_EXT_MAG_ERROR = 0.25;
const int DEFAULT_REDUNDANCY_PRECISION = 4;
const double MIN_VARIANCE_SCALE = 0.01;
const double MAX_VARIANCE_SCALE = 100.0;

const double DEFAULT_SETUPERROR_TRIPOD_STANDARDPLUMMET_M = 0.001;
const double DEFAULT_SETUPERROR_TRIPOD_VERTCOLLIMATOR_M = 0.0005;
const double DEFAULT_SETUPERROR_TRIPOD_FORCEDCENTERINGPLATE_M = 0.0;
const double DEFAULT_SETUPERROR_RANGEPOLE_M = 0.004;
const double DEFAULT_SIGMA_TOTALSTATION_DISTANCE_INFRARED_M = 0.001;
const double DEFAULT_SIGMA_TOTALSTATION_DISTANCE_REDLASER_M = 0.002;
const double DEFAULT_SIGMA_TOTALSTATION_DISTANCE_UNKNOWNPRISM_M = 0.003;
const double DEFAULT_SIGMA_TOTALSTATION_DISTANCE_REFLECTORLESS_M = 0.005;
const double DEFAULT_SIGMA_TOTALSTATION_HORZANGLES_SOA = 5.0;
const double DEFAULT_SIGMA_TOTALSTATION_VERTANGLES_SOA = 10.0;
const double DEFAULT_SIGMA_TOTALSTATION_ELEVDIFFS_M = 0.01;
const double DEFAULT_SIGMA_TOTALSTATION_INSTR_HGHT_M = 0.00;
const double MEASURE_ROD_SIGMA_TOTALSTATION_INSTR_HGHT_M = 0.001;
const double MEASURE_TAPE_SIGMA_TOTALSTATION_INSTR_HGHT_M = 0.001;
const double DEFAULT_PPM_TOTALSTATION_DISTANCE_PRISM = 1.0;
const double DEFAULT_PPM_TOTALSTATION_DISTANCE_REFLECTORLESS = 2.0;
const double DEFAULT_SIGMA_DIGITALLEVELS_STANDARDRODS_M = 0.0006;
const double DEFAULT_SIGMA_DIGITALLEVELS_PRECISERODS_M = 0.0003;
const double DEFAULT_SIGMA_SPIRITLEVELS_STANDARDRODS_M = 0.001;
const double EPSILON = 1E-10;
const double MIN_LATITUDE_BOUNDARY = -90. + EPSILON;
const double MAX_LATITUDE_BOUNDARY = 90. - EPSILON;

//This enum is intended to match the iret-->msg mapping near the end of lsasolver.cpp main()
enum enum_solver_return_code {CMDINVALID=-3, UNKNOWN=-2, NOOUTFILE=-1, NORMAL=0, CMDLINEUSAGE, CMDLINERRRORS,
                              USERVALIDATION, INPUTINVALID, OUTPUTFILEFAIL,INPUTFILEFAIL=7, EARLYEXIT,
                              PROBLEMUNDERDETERMINED, PROBLEMSINGULAR, UNABLEAPRIORI, NODATA, NOSTATE,
                              SINGULARCOV, SINGULARMEASCOV, SOLUTIONSINGULAR, INVALIDDIRSET, GEOIDFILEFAIL,
                              EIGENFAIL, MEMORYALLOCATEFAIL, COMPFILEFAIL=90, DATFILEFAIL, BINFILEFAIL, BINFILEOBSOLELE};

const std::string AUTO_HGHT_PREPEND_TAG = "HGHT#";//full prepend tag is "HGHT#N_", where N is variable

enum SOLVER_RETURNS
{
    INVALID_CMD_LINE_DEF = -3,
    LSASOLVER_ERROR = -1,
    LSASOLVER_OK,
    COMMAND_LINE_USAGE,
    COMMAND_LINE_ERRORS,
    USER_VALIDATION,
    INVALID_INPUT,
    UNOPENED_LOG_FILE,
    UNOPENED_INPUT_FILE = 7,
    EARLY_EXIT,
    PROBLEM_UNDERDETERMINED,
    SINGULAR_PROBLEM,
    PROBLEM_APRIORI,
    INVALID_NO_DATA,
    INVALID_NO_STATE,
    PROBLEM_INCONSISTENT_CONSTRAINTS,
    SINGULAR_COVARIANCE,
    SINGULAR_LS_SOLUTION,
    INVALID_DIR_SETS,
    UNOPENED_GEOID_FILE,
    PROBLEM_EIGEN,
    PROBLEM_MEM_ALLOC,
    PROBLEM_NAN_DETECTED,
    UNOPENED_COMP_FILE = 90,
    UNOPENED_DAT_FILE,
    UNOPENED_BIN_FILE,
    INVALID_BIN_FILE_VER,
    EIGEN_CHOLESKY_FAIL
};

enum CONVERTER_TYPE
{
    CONVERTER_TYPE_NULL, // Unknown
    CONVERTER_TYPE_NONE, // It doesn't need converted
    CONVERTER_TYPE_IOB,
    CONVERTER_TYPE_SETSOFANGLES,
    CONVERTER_TYPE_TRIMBLETDEF,
    CONVERTER_TYPE_TRIMBLEROUNDS,
    CONVERTER_TYPE_PPP,
    CONVERTER_TYPE_OPUS,
    CONVERTER_TYPE_GSI,
    CONVERTER_TYPE_LEICAGNSS,
    CONVERTER_TYPE_CUSTOM
};

// enum class to determine why we are parsing the .cfg file
enum CFG_PARSE_TYPE
{
    CFG_PARSE_USING_WEST_LON,
    CFG_PARSE_IS_SCALE_BY_APV,
    CFG_PARSE_INCLUDE_UNUSED,
    CFG_PARSE_IS_ALLOW_FAST,
    CFG_PARSE_IS_GEOID_USED,
    CFG_PARSE_IS_PROJ_DIR_GEOID,
    CFG_PARSE_GET_CONFIDENCE_INTERVAL,
    CFG_PARSE_GET_CHI_SQUARED
};

}

#endif // LSACONSTANTS_HPP
