/*
	Copyright (c) 2015-2024 Applied Research Laboratories, The University of Texas
	at Austin (ARL:UT).
	
	SALSA is free software: you can redistribute it and/or modify it under the
	terms of the GNU General Public License version 3 (GPL-3.0-only) as published
	by the Free Software Foundation.
	
	SALSA is distributed in the hope that it will be useful, but WITHOUT ANY
	WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
	A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License along with
	SALSA.  If not, see https://www.gnu.org/licenses/.
*/
#ifndef LSA_ENUO_INCLUDE
#define LSA_ENUO_INCLUDE

#include <string>
#include <map>
#include "Matrix.hpp"

#include "LSARecord.hpp"
#include "LSAModifier.hpp"
#include "DATDelta.hpp"

class LSAEnuo : public LSARecord {
public:
   // member data ------------------------------------------------------

   // labels
   std::string From;  ///< string label for the "From" Point
   std::string To; ///< string label for the "To" Point

   // coordinate differences
   double de;             ///< E-coordinate difference (label - From)
   double dn;             ///< N-coordinate difference (label - From)
   double du;             ///< U-coordinate difference (label - From)
   std::string linUnits;  ///< Units used for linear measurements

   // components of the UT portion of the covariances matrix.
   double se;     ///< measurement sigma in the E direction
   double sn;     ///< measurement sigma in the N direction
   double su;     ///< measurement sigma in the U direction

   // UI display
   static const int NUM_UI_DISPLAY_COLUMNS;

   // member functions -------------------------------------------------

   /// constructor
   LSAEnuo() : LSARecord(LSAType::ENUO),
       From("from"), To("unknown"), de(0.0), dn(0.0), du(0.0),
       se(0.0), sn(0.0), su(0.0), linUnits("M") {}

   /// destructor
   virtual ~LSAEnuo() { }

   LSAEnuo(std::string from, std::string label, double de, double dn, double du, std::string units,
                                           double se, double sn, double su)
      : LSARecord(LSAType::ENUO),
        From(from), To(label), de(de), dn(dn), du(du), linUnits(units),
            se(se), sn(sn), su(su) { }

   /// Parse a string from a single line in the LSA file.
   /// @param line single line read from LSA file
   /// @return true if successful
   virtual void fromString(const std::string& line);

   /// write the object as a string for the LSA file.
   /// param out, an ostream reference to the output filestream or stringstream
   virtual void writeLSAString(std::ostream & out) const;

   /// Get the number of columns used to display this record type in the Project Navigator
   /// @return the number of columns to display
   virtual int getNumDisplayColumns() const { return NUM_UI_DISPLAY_COLUMNS; }

   /// Get a string to display in a given column in the Project Navigator
   /// @param the column number to display
   /// @return the string to display in the UI
   virtual std::string getUIColumnData(int columnNumber) const;

   /// If this record refers to a height modifier with label oldLabel, change the reference to refer to newLabel instead
   /// @param oldLabel the old label
   /// @param newLabel the new label
   virtual void renameModifierLabel(LSAType type, std::string oldLabel, std::string newLabel);

   std::string  getLabel() const { return To; }
   virtual bool referencesPosition(const std::string& input) const { return From == input; }
   virtual void renamePosition(std::string oldLabel, std::string newLabel);

   // Note: ENUO records can never cause position estimates to be autogenerated, so return nothing here
   virtual std::vector<std::string> getReferencedPositions() const {return std::vector<std::string>();}
   void validatePositions(std::set<std::string> allPositionsIncludingAutogen, std::list<std::string> derivedPoints);

   virtual bool referencesModifier(LSAType modifierType, std::string label) const { return false; }
   virtual bool supportsModifier(ModifierKeyword keyword) const { return false; }
   virtual std::string getModifierLabel(ModifierKeyword keyword) const { return ""; }
   virtual bool vscaIsNumeric() const { return false; }

   bool hasValidCovariance() const { return true; }
   virtual LSAModifier* getModifiers() { return NULL; }

   std::string getSingleDATString() const;

private:
   /// Output as a string (one line) to display in the UI. Pure virtual
   /// @return a string to display in the UI
   virtual std::string getUIName() const;

   /// Output as a string (one line) to display in the UI. Pure virtual
   /// @return a string to display in the UI
   virtual std::string getUIDetails() const;

}; // end class LSAEnuo

#endif   // LSA_ENUO_INCLUDE
