/*
	Copyright (c) 2015-2024 Applied Research Laboratories, The University of Texas
	at Austin (ARL:UT).
	
	SALSA is free software: you can redistribute it and/or modify it under the
	terms of the GNU General Public License version 3 (GPL-3.0-only) as published
	by the Free Software Foundation.
	
	SALSA is distributed in the hope that it will be useful, but WITHOUT ANY
	WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
	A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License along with
	SALSA.  If not, see https://www.gnu.org/licenses/.
*/
/// @file LSAfile.hpp  Include file for *.LSA file: read and parse, write, and fill
///                    LSA* objects.

#include <ostream>
#include <string>
#include <vector>
#include <set>
#include <map>
#include "Exception.hpp"

#include "LSAAzimuth.hpp"
#include "LSAComment.hpp"
#include "LSAConfig.hpp"
#include "LSADelta.hpp"
#include "LSAEnuo.hpp"
#include "LSADirGroup.hpp"
#include "LSADist.hpp"
#include "LSAHAngle.hpp"
#include "LSAHDir.hpp"
#include "LSAHeightDiff.hpp"
#include "LSAInclude.hpp"
#include "LSAMaps.hpp"
#include "LSAMean.hpp"
#include "LSAPosG.hpp"
#include "LSAPosC.hpp"
#include "LSAVAngle.hpp"
#include "LSAZAngle.hpp"

#include "geoid.hpp"

#include <QList>


#ifndef LSA_LSA_FILE_PARSER_WRITER_INCLUDE
#define LSA_LSA_FILE_PARSER_WRITER_INCLUDE

/**
\verbatim

TODO: update documentation

\endverbatim
*/

/// Class LSAfile encapsulates reading, parsing, writing and data storage for all
/// records in *.LSA files.
class LSAFile {
public:

    // Constructor and Destructor
    LSAFile(bool applicationIsGui);
    ~LSAFile();

    // static constants
    static const std::string MESSAGE_FILE_NOT_FOUND;
    static const std::string MESSAGE_PARSE_WARNING;

    // member functions
   /// Open and read a .LSA file, parse the contents and fill the data vectors.
   /// @param filename input file name
   /// @param badrecs return vector<string> of records that could not be parsed
   /// @return true if filename can be opened
   bool read(const std::string& absolutePath);

   /// Save the contents of the lsa file using filenames contained in include records
   /// @param filename file name
   /// @return the number of records successfully written.
   int save();
   /// Recursive method to save the contents of a LSAIncludeRecord
   void saveLSAIncludeRecord(LSAInclude *parent);

   /// Open and write a .dat file, writing dat records for all the data vectors.
   /// param filename file name
   /// return the number of records successfully written.
   int writeDatFile(std::string filename);

   /// Generate an order-dependent, record-by-record hash of the contents to be written to
   /// a .dat file.
   /// return the hash
   unsigned int hashDatFile();

   /// static helper method to get the modifier for a given lsaRecord
   /// Note: this is a static method on LSAFile to work around a circular
   /// dependency issue with LSARecord, LSAModifer, LSAHeight, LSAUncr and LSACovariance
   /// @param lsaRecord a pointer to an LSARecord
   /// @return a pointer to the modifier for the record.  NULL if the record has no modifiers.
   static LSAModifier* getModifiersForLSARecord(LSARecord* lsaRecord);

   LSARecord* insertNewRecord(LSAType recordType, std::string line, LSAInclude* parentIncludeRecord,
                              bool recordIsCommented, bool parentIsActive,
                              int position = -1 , bool isAutogenerated = false,
                              std::vector<std::string> modifierStringsForInclude = std::vector<std::string>(),
                              std::string genNotes = std::string());

   /// Attempts to insert a new label into a map
   /// @param type the type of the LSARecord.  Only POSG, POSC, UNCR, VSCA and DGRP have maps.
   /// @param the label to insert
   /// @param the record to insert into the map
   /// @return NULL on succesfull insert, on failed insert, return pointer the duplicate record
   LSARecord* insertMapValue(LSAType type, std::string label, LSARecord *lsaRecord, bool recordIsCommented, bool parentIsActive);

   // Refactored addition and insertion of label, dgrp data so that dgrpMap and dgrpMapComplete are in sync. Issue 215
   void addDGRPpair(const std::string &label, LSADirGroup *dgrp);
   void removeDGRPLabel(const std::string &label);

   void removeRecord(LSAInclude* parentInclude, int childNum);

   std::string              getProjectDirectory() { return projectDirectory; }
   std::vector<std::string> getErrorsAndWarnings()       { return errorsAndWarnings; }
   void clearErrorsAndWarnings() {errorsAndWarnings.clear(); }

   LSARecord* getRootRecord() const { return rootInclude; }

   //Created with SALSA version
   std::string createdWithSalsaVersion;
   bool isFileVersionCurrent(std::string salsaVersion);

   // Point and Measurements
   LSARecordMap            pointMap;     ///< map of <label, LSARecord*> containing all the points in the LSAFile
   std::vector<LSARecord*> measurements; ///< map of <label, LSARecord*> containing all the measurements in the LSAFile

   // Modifier Maps
   LSAUNCRMap uncrMap; ///< map of <label, LSAUncr*>
   LSAHGHTMap hghtMap; ///< map of <label, LSAHeight*>
   LSAVSCAMap vscaMap; ///< map of <label, LSAVarScaling*>

   // DirGroupMap
   LSADirGroupMap dgrpMap; ///< map of <label, LSADirGroup>
   LSADirGroupMap dgrpMapComplete; ///< map of <label, LSADirGroup> including disabled records

   // Orthometric POSG container
   std::vector<LSAPosG *> allOrthoPos;

   Geoid geoid;
   std::map<std::string, double> labelToUndMap;

   void clearRootIncludeUIWarnings() { rootInclude->warningMessages_generated.clear(); }

   // Modifier Methods
   double          getVSCAValue(LSARecord *lsaRecord) const;
   bool            isValidSigma(LSARecord *lsaRecord) const;
   bool            hasNonzeroPPMSigma(LSARecord *lsaRecord) const;
   LSAUncertainty* getUNCRRecord(LSARecord *lsaRecord) const;
   void            getHeightDataByLabel(std::string label, double & value, std::string & units, double & sigma, std::string & sigmaUnits);
   bool            getHeightFromData(LSARecord *lsaRecord, std::string &label, double & value, std::string & units, double & sigma, std::string & sigmaUnits, bool & isNumeric) const;
   bool            getHeightToData(LSARecord *lsaRecord, std::string &label, double & value, std::string & units, double & sigma, std::string & sigmaUnits, bool & isNumeric) const;
   bool            getRefractData(LSARecord *lsaRecord, double & value) const;

   std::string     getParentDGRPFromStation(LSAHDir *lsaHDir) const;
   std::set<std::string> getIncludedLSAFiles () const { return includedLSAFiles; }

   bool isApplicationGui() const { return applicationIsGui; }
   std::string getRootAbsolutePath() const { return rootInclude->getAbsolutePath(); }

   /// Takes a stringstream (of a file or just text), and tries to read it in as records.
   /// @param ss the stringstream with all of the data
   /// @param currentInclude the include to be adding things into (nullptr is for root include)
   /// @param currentIsActive the current include is active (not commented)
   /// @param childPosition where to place the new records under the parent (-1 will place at the end)
   /// @param newRecords the newly created records
   /// @return which line number of the stream we are exiting at (for errors)
   int parseLSAStream(std::stringstream& ss, LSAInclude* currentInclude = nullptr, bool currentIsActive = true,
                      int childPosition = -1, QList<LSARecord*>* newRecords = nullptr);

private:

    bool applicationIsGui; ///< indicates this LSAFile object is part of the lsa gui application (as opposed to the preprocessor or some other CLI)

    // member data
    LSAInclude* rootInclude;       ///< the top parent (root) record for the LSARecord tree
    LSAInclude *autogenInclude;   ///< pointer to special autogenerated include record containing apriori POSG records
    std::string projectDirectory;  ///< directory where the top level parent include is located

    std::vector<std::string> errorsAndWarnings;       ///< vector of lines parser was unable to process
    std::set<std::string>    includedLSAFiles; ///< set of lsa files in the project, used to prevent duplicate included files


    void parseIncludeFilename(std::string line, std::string &newFile, std::vector<std::string> &modifierStrings);
    QList<std::string> getDescendantIncludes(LSAInclude* parentInclude);

    /// Add another entry to the BadRecords vector
    /// @param line the line that couldn't be parsed
    /// @oaram filename currently being parsed
    /// @param lineNum currently being parsed
    void pushBadRecord(std::string filename, int lineNum, std::string line);
    void pushBadRecord(std::string filename, std::string line);
    void pushWarning(std::string message);

    /// Open, read and parse a .LSA file, filling a vector of pointers to LSArecord.
    /// @param filename - relative path from the parent include to the current include
    /// @param currentInclude - the current include record whose children are being parsed
    /// @param parentInclude - the parent include of the current include (NULL if no parent)
    /// @param recordIsCommented
    /// @param currentIsActive - boolean indicating whether or not the currentInclude record is active
    /// @return true if the include filename can be opened and is not already included in the project
    bool readAndParseLSAfile(std::string filename, LSAInclude* currentInclude, LSAInclude* parentInclude, bool recordIsCommented, bool currentIsActive);

    /// Write all of the child records for an LSAInclude record to an output datFile
    /// param datFile fstream for the output dat file
    /// param parentRecord the LSAInclude parent record
    /// param recordCounter tree index of current measurement record
    /// param groupVSCAFactor cummulate scaling factor for child records
    /// param hash - the hash from records hash up until this point
    /// param hashInsteadOfWrite whether to write the dat record or just generate the hash on it
    /// return the number of records successfully written.
    unsigned int writeDATChildRecords(std::fstream &datFile, LSAInclude* parent, unsigned int &recordCounter,
                                      double groupVSCAFactor = 1.0, unsigned int hash = 0, bool hashInsteadOfWrite=false);

    /// Generate a hash for all .dat records to be generated from an include file's contents
    /// param parent - the include file containing the child records
    /// param hash - the hash from records hash up until this point
    /// param groupVSCAFactor - cummulative scaling factor to be applied to all children
    /// return the cummulative hash included the hashed child records
    unsigned int hashDATChildRecords(LSAInclude* parent, unsigned int hash, double groupVSCAFactor = 1.0);

    /// Method to recursively append continued lines onto the current record
    /// @param istrm the current stream being read
    /// @param line the current line being parsed
    void handleLineContinuation(std::ifstream & istrm, std::string & line, int lineCounter, bool prevLineIsCommented, std::string filename = "");
    void handleLineContinuation(std::stringstream & istrm, std::string & line, int lineCounter, bool prevLineIsCommented, std::string filename = "");
    
    /// Method to keep getting lines from <TXNS> till </TXNS>, preserving format of contents.
    /// @param istrm the current stream being read
    /// @param line the current line being parsed
    /// @param filename the name of the file being read (for printing errors)
    /// @param lineCounter the line for when reading fails
    void handleTextNotes(std::stringstream & istrm, std::string & line, std::string filename, int lineCounter);

    /// Method get the version of SALSA with which the file was created.
    /// @param inString the line at the top of the file with the version information
    /// @return the version of SALSA with which the file was created was successfully parsed, else ""
    std::string parseCreatedWithVersionFromString(const std::string& inString) const;

    /// Method get the oldest version of SALSA with which the file can be opened.
    /// @param inString the line at the top of the file with the version information
    /// @return the oldest version of SALSA with which the file can be opened was created was successfully parsed, else ""
    std::string parseBackwardCompatibilityVersionFromString(const std::string& inString) const;

    DATAzimuth convertToDAT(LSAAzimuth    *lsaAzim,       double groupVSCAFactor = 1.0);
    DATDelta   convertToDAT(LSADelta      *lsaDelta,      double groupVSCAFactor = 1.0);
    DATDirSet  convertToDAT(LSADirGroup   *lsaDirGroup,   double groupVSCAFactor = 1.0);
    DATDist    convertToDAT(LSADist       *lsaDist,       double groupVSCAFactor = 1.0);
    DATHAngle  convertToDAT(LSAHAngle     *lsaHAngle,     double groupVSCAFactor = 1.0);
    DATDir     convertToDAT(LSAHDir       *lsaHDir,     std::string & errorMessage, double groupVSCAFactor = 1.0);
    DATHeight  convertToDAT(LSAHeightDiff *lsaHeightDiff, double groupVSCAFactor = 1.0);
    DATPoint   convertToDAT(LSAPosC       *lsaPosC,       double groupVSCAFactor = 1.0);
    DATPoint   convertToDAT(LSAPosG       *lsaPosG, bool &initialCall,      double groupVSCAFactor = 1.0);
    DATVAngle  convertToDAT(LSAVAngle     *lsaVAngle,     double groupVSCAFactor = 1.0);
    DATZAngle  convertToDAT(LSAZAngle     *lsaZAngle,     double groupVSCAFactor = 1.0);


    // UNCR methods
    double      getAddSigma(LSARecord *lsaRecord, const std::string& measUnits) const;
    std::string getAddSigmaUnits(LSARecord *lsaRecord) const;
    double      getPPMSigma(LSARecord *lsaRecord) const;
    bool        hasToCentError(LSARecord *lsaRecord) const;
    double      getToCentError(LSARecord *lsaRecord, const std::string &measUnits="m") const;
    bool        hasFromCentError(LSARecord *lsaRecord) const;
    double      getFromCentError(LSARecord *lsaRecord, const std::string &measUnits="m") const;
    bool        hasAtCentError(LSARecord *lsaRecord) const;
    double      getAtCentError(LSARecord *lsaRecord, const std::string &measUnits="m") const;

    // HGHT methods
    double getHeightFromInMeters(LSARecord *lsaRecord);
    double getHeightToInMeters(LSARecord *lsaRecord);
    double getHeightFromSigmaInMeters(LSARecord *lsaRecord);
    double getHeightToSigmaInMeters(LSARecord *lsaRecord);

    bool sigmIsMissing(LSARecord *lsaRecord);
    bool vscaIsMissing(LSARecord *lsaRecord);
    bool htoIsMissing(LSARecord *lsaRecord);
    bool hfromIsMissing(LSARecord *lsaRecord);

    bool isProjectDirGeoid(const std::string &fileName) const;
    QString getGeoidFileName(const std::string &fileName);
    QString getGeoidFileName(const QString& fileName);

    QString getConfigName(const std::string &fileName) const;
    QString getConfigName(const QString &fileName) const;

    bool validGeoidName = true;

}; // end class LSAfile

#endif // LSA_LSA_FILE_PARSER_WRITER_INCLUDE
