/*
	Copyright (c) 2015-2024 Applied Research Laboratories, The University of Texas
	at Austin (ARL:UT).
	
	SALSA is free software: you can redistribute it and/or modify it under the
	terms of the GNU General Public License version 3 (GPL-3.0-only) as published
	by the Free Software Foundation.
	
	SALSA is distributed in the hope that it will be useful, but WITHOUT ANY
	WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
	A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License along with
	SALSA.  If not, see https://www.gnu.org/licenses/.
*/
/// @file lsabinary.hpp
/// Implement binary output file for lsasolver, including input output and dump.

#ifndef LSA_OUTPUT_FILE_INCLUDE
#define LSA_OUTPUT_FILE_INCLUDE
#pragma warning(disable:4251)//H5::Exception::detail_message needs dll-interface. Not used.

#define CPTR(VAR,CONST) ((VAR)=(CONST),&(VAR))//needed for hdf5 enum data types

// system includes
#include <iostream>
#include <iomanip>
#include <fstream>
#include <string>
#include <vector>
#include <map>
#include <memory>
// GNSSTk
#include "StringUtils.hpp"
// geomatics
#include "Namelist.hpp"
// lsa
#include "MatrixVector.hpp"
#include "LSAConstants.hpp" //for enum_solver_return_code
#include <LSAFixedState.hpp>
#include "LSAVersion.hpp"
//HDF5 C++ library
#include "H5Cpp.h"

///// ENUMS
enum enum_bool_type {BOOL_FALSE, BOOL_TRUE};
enum enum_source_type {PROVIDED, DERIVED_MEAN, DERIVED_ENUO, AUTOGENERATED};
enum enum_solver_run_type {FAST, STABLE, FALLBACK_TO_STABLE};
enum enum_binary_file_status
{
    BIN_FILE_PARSING_FAILURE = -6,
    BIN_FILE_STALE = -5,
    BIN_FILE_FORMAT_OBSOLETE = -4,
    BIN_FILE_UNABLE_TO_OPEN = -3,
    BIN_FILE_NOT_PARSED = -2,
    BIN_FILE_NOT_FOUND = -1,
    BIN_FILE_NO_SOLUTION = 0,
    BIN_FILE_FOUND_SOLUTION = 1,
    BIN_FILE_VALID = 2
};

////// struct to hold all information needed for the Project_Configuration data set
struct projConfigExternal {
    double converge;                      ///< convergence criterion
    int iterMax;                          ///< iteration max
    std::string geoint;                   ///< geoid interpolator
    std::string geoFileName;              ///< geoid file name
    std::string confidence;               ///< confidence region (percent or 1sig)
    double alpha;                         ///< chi-sqr significance
    enum_bool_type calcExtRelVect;        ///< flag that points to if external reliability is calculated
};

////// struct to hold all information needed for the Post_Processor_Input data set
struct postProcInputExternal {
    std::string binFileName;    ///< bin file name
    int binVersion;             ///< bin file version
    std::string datFileName;    ///< dat file name
    std::string outFileName;    ///< out file name
    std::string hashString;     ///< hash string
    enum_binary_file_status binFileStatus; ///< binary file status
};

////// struct to hold all information needed for the problem_description data set
struct probDescriptExternal {
    int degOfFreed;             ///< Degrees of freedom
    int unknownCount;           ///< number of unknowns
    int dataCount;              ///< number of data
    int NMeas;                  ///< number of meas - 3 * nConstrainedPts
    int constraintCount;        ///< number of constraints
    int dims;                   ///< dimensions
};

////// struct to hold all information needed for the LLH data set
struct llhExternal {
    std::string label;                                 ///< Point label
    double lat,lon,ht;                                 ///< coordinates lat, lon E, ht
    double oht;                                        ///< oht (m)
    double adjN,adjE,adjU;                             ///< delta NEU
    double sigN,sigE,sigU;                             ///< sigmas NEU
    double Cnn,Cne,Cnu,Cee,Ceu,Cuu;                    ///< covariance matrix
    double dovN,dovE;                                  ///< DoV(SOA) for this point, if available
    double maj2D, min2D;                               ///< 2D major axis, 2D Minor axis
    double maj3D;                                      ///< 3D major axis
    double azim;                                       ///< azimith angle
    double vert;                                       ///< veritcal
    double maj2Drr, min2Drr, maj3Drr, vertrr, azrr;    ///< Reliability rectangle values


    enum_source_type sourceType ;    ///< source type
    bool utilized;                   ///< is the point adjusted
    LSAFixedState fixedType;         ///< is the point fixed
    std::string constraints;         ///< one or more characters of E,N,U
};

////// struct to hold all information needed for the XYZ data set
struct xyzExternal {
    std::string label;                  ///< Point label
    double x,y,z;                       ///< coordinates lat, lon E, ht
    double adjX,adjY,adjZ;              ///< delta XYZ
    double sigX,sigY,sigZ;              ///< sigmas XYZ
    double Cxx,Cxy,Cxz,Cyy,Cyz,Czz;     ///< covariance matrix
    enum_source_type sourceType;        ///< source type
    bool utilized;                      ///< is the point adjusted
    LSAFixedState fixedType ;           ///< is the point fixed
    std::string constraints;            ///< constraintm
};

////// struct to hold all information needed for the measurements data set
struct measurementsExternal {
    std::string measType;   ///< measurment type
    std::string from;       ///< from point name
    std::string at;         ///< at point name
    std::string to;         ///< to point name
    std::string tag;        ///< Tag
    double initMeas;        ///< initial measurement
    double adjMeas;         ///< adjusted mesurment
    double rawResid;        ///< raw residual
    double relResid;        ///< relative residual
    double stdResid;        ///< standard residual
    double redund;          ///< redundancy
    double minDectBias;     ///< minimum detectable bias
    double extVectMag;      ///< external reliability vector magnitude
    bool isBlunder;         ///< blunders present?
    bool redundancyZero;    ///< is redundancy equal to zero?
    bool isDerived;         ///< is measuremnt derived?
};

////// struct to hold all information needed for the Convergence_histroy data set
struct convergenceHistExternal {
    int iterationNum;
    double RMSadj;
    double delta;
    double RMSrelResid;
    std::string status;
};

////// struct to hold all information needed for the statistics data set
struct statisticsExternal {
    double relRMSresid;         ///< MS post-fit relative residual
    double stdDevUnitWieght;    ///< standard deviation of unit weight, sqrt(APV)
    double APV;                 ///< APV
    double angRMSresidSOA;      ///< angular RMS residual (soa)
    double lenRMSresid;         ///< linear RMS residual (m)
    double lowerChiSq;          ///< lower limit in chi squared test
    double upperChiSq;          ///< upper limit in chi squared test

};

////// struct to hold all information needed for the solution_covariance data set
struct solCovar {
    std::vector<std::vector<double> > covar;              ///< 2D covariance array
    std::vector<std::string> axisLabels;     ///< array of strings for labeling x|y axis of covariance table
};

////// struct to hold all information needed for the Solver_Error data set
struct solverErrorExternal {
    std::string errorString;    ///< error message
};

////// struct to hold all information needed to read the Project_Configuration data set
struct projConfigInternal {
    double converge;            ///< convergence criterion
    int iterMax;                ///< iteration max
    const char* geoint;         ///< geoid interpolator
    const char* geoFileName;    ///< geoid file name
    const char* confidence;     ///< confidence region (percent or 1sig)
    double alpha;               ///< chi-sqr significance
    enum_bool_type calcExtRelVect;        ///< flag that points to if external relibility is calculated
};

////// struct to hold all information needed to read the Post_Processor_Input data set
struct postProcInputInternal {
    const char* binFileName;    ///< bin file name
    int binVersion;             ///< bin file version
    const char* datFileName;    ///< dat file name
    const char* outFileName;    ///< out file name
    const char* hashString;     ///< hash string
    enum_binary_file_status binFileStatus; ///< binary file status
};

////// struct to hold all information needed to read the LLH data set
struct llhInternal {
    const char* label;          ///< Point label
    double lat,lon,ht;          ///< coordinates lat, lon E, ht
    double oht;                 ///< oht (m)
    double adjN,adjE,adjU;      ///< delta NEU
    double sigN,sigE,sigU;      ///< sigmas NEU
    double Cnn,Cne,Cnu,Cee,Ceu,Cuu;     ///< covariance matrix
    double dovN,dovE;           ///< DoV(SOA) for this point, if available
    double maj2D, min2D;        ///< 2D major axis, 2D Minor axis
    double maj3D;               ///< 3D major axis
    double azim;                ///< azimith angle
    double vert;                ///< vertical
    double maj2Drr, min2Drr, maj3Drr, vertrr, azrr;
    enum_source_type sourceType ;    ///< source type
    enum_bool_type utilized;           ///< is the point adjusted
    LSAFixedState fixedType;       ///< is the point fixed
    const char* constraints;     ///< one or more characters of E,N,U
};

////// struct to hold all information needed to write/read one data point in the XYZ data set
struct xyzInternal {
    const char* label;          ///< Point label
    double x,y,z;               ///< coordinates lat, lon E, ht
    double adjX,adjY,adjZ;      ///< delta XYZ
    double sigX,sigY,sigZ;      ///< sigmas XYZ
    double Cxx,Cxy,Cxz,Cyy,Cyz,Czz;     ///< covariance matrix
    enum_source_type sourceType;     ///< source type
    enum_bool_type utilized;           ///< is the point adjusted
    LSAFixedState fixedType ;      ///< is the point fixed
    const char* constraints;     ///< constraints
};

////// struct to hold all information needed to read the measurements data set
struct measurementsInternal {
    const char* measType;   ///< measurment type
    const char* from;       ///< from point name
    const char* at;         ///< at point name
    const char* to;         ///< to point name
    const char* tag;        ///< Tag
    double initMeas;        ///< initial measurement
    double adjMeas;         ///< adjusted mesurment
    double rawResid;        ///< raw residual
    double relResid;        ///< relative residual
    double stdResid;        ///< standard residual
    double redund;          ///< redundancy
    double minDectBias;
    double extVectMag;
    enum_bool_type isBlunder;         ///< blunders present?
    enum_bool_type redundancyZero;    ///< is redundancy equal to zero?
    enum_bool_type isDerived;         ///< is measuremnt derived?
};

////// struct to hold all information needed to read the Convergence_history data set
struct convergenceHistInternal {
    int iterationNum;
    double RMSadj;
    double delta;
    double RMSrelResid;
    const char* status;
};

////// struct to hold all information needed to read the Solver_Warning data set
struct solverWarningInternal {
    const char* warningString;
};

////// struct to hold all information needed to read the Solver_Errors data set
struct solverErrorsInternal {
    const char* errorString;
};

////// class definitions for datasets
class ProjCfgDataSet
{
private:
    hid_t projCfgMemoryType;
    hid_t projCfgFileType;
    projConfigExternal dataContainer;
public:

    ProjCfgDataSet(){
        InitprojCfgDataType();
    }

    void addDataPoint(double converge, int niterMax, std::string geoInt, std::string geoidFile, std::string confidence, double alpha, bool calcExtRelVect);

    void addDataPoint(projConfigExternal dataPoint);

    int writeToFile(H5::H5File writeFile);

    int readDataSetFromFile(H5::H5File readFile);

    //readDataSetFromGroup must be called before this function to work
    projConfigExternal getDataPoint();

private:

    projConfigInternal ProjConfigExternalToInternal();

    void readToDataContainer(projConfigInternal dataPoint);

    //init the compound datatype for xyz dataset
    void InitprojCfgDataType();
};

class PostProcInputDataSet
{
private:
    hid_t postProcInputMemoryType;
    hid_t postProcInputFileType;
    postProcInputExternal dataContainer;
public:

    PostProcInputDataSet(){
        InitpostProcInputDataType();
        initDataContainer();
    }

    void addDataPoint(std::string binFileName, int binVersion, std::string datFileName, std::string outFileName, std::string hashString, enum_binary_file_status binFileStatus);

    void addDataPoint(postProcInputExternal dataPoint);

    int writeToFile(H5::H5File writeFile);

    int readDataSetFromFile(H5::H5File readFile);

    //readDataSetFromGroup must be called before this function to work
    postProcInputExternal getDataPoint();

private:

    postProcInputInternal postProcInputExternalToInternal();

    void readToDataContainer(postProcInputInternal dataPoint);

    //init the compound datatype for xyz dataset
    void InitpostProcInputDataType();

    void initDataContainer();
};

class ProbDescriptDataSet
{
private:
    hid_t probDescriptMemoryType;
    hid_t probDescriptFileType;
    probDescriptExternal dataContainer;
    int size;
public:

    ProbDescriptDataSet():size(0){
        InitpostProcInputDataType();\
        initContainer();
    }

    void addDataPoint(int degOfFreed, int unknownCount, int dataCount, int NMeas, int constraintCount, int dims);

    void addDataPoint(probDescriptExternal dataPoint);

    int writeToGroup(H5::Group adjustmentResultsGroup);

    int readDataSetFromGroup(H5::Group adjustmentResultsGroup);

    int getSize();

    //readDataSetFromGroup must be called before this function to work
    probDescriptExternal getDataPoint();

private:

    void InitpostProcInputDataType();

    void initContainer();
};

class LlhDataSet
{
protected:
    hid_t llhMemoryType;
    hid_t llhFileType;
    std::vector<llhExternal> dataContainer;
    H5::H5File file;
    H5::Group group;
public:

    LlhDataSet(){
        InitLlhDataType();
    }

    void setGroup(H5::Group assignedGroup);

    int getSize();

    void addDataPoint(std::string label, double lat, double lon, double ht, enum_source_type sourceType, bool is_adjusted,
                          LSAFixedState fixedType, std::string constraint, double oht=0.0, double dovN=0.0,double dovE=0.0, double adjN=0.0, double adjE=0.0, double adjU=0.0, double sigN=0.0,
                          double sigE=0.0, double sigU=0.0, double Cnn=0.0, double Cne=0.0, double Cnu=0.0, double Cee=0.0, double Ceu=0.0, double Cuu=0.0,
                          double maj3D=0.0, double maj2D=0.0, double min2D=0.0, double azim=90.0, double vert=0.0, double maj2Drr=0.0, double min2Drr=0.0,
                          double maj3Drr=0.0, double vertrr=0.0, double azrr=0.0);

    void addDataPoint(llhExternal dataPoint);

    virtual int writeToGroup(H5::Group assignedGroup);

    virtual int readDataSetFromGroup(H5::Group pointsGroup);

    //readDataSetFromGroup must be called before this function to work
    llhExternal getDataPoint(int index);

protected:

    void writeToBuffer(llhInternal *buffer);

    void readToDataContainer(llhInternal *buffer, hssize_t numberOfDataPointsInSet);

    //init the compound datatype for xyz dataset
    void InitLlhDataType();
};

class InitialLlhDataSet : public LlhDataSet
{
public:
    int writeToGroup(H5::Group assignedGroup);

    int readDataSetFromGroup(H5::Group pointsGroup);
};

class XyxDataSet
{
private:
    hid_t xyzMemoryType;
    hid_t xyzFileType;
    std::vector<xyzExternal> dataContainer;
    H5::H5File file;
    H5::Group group;
public:

    XyxDataSet(){
        InitXyzDataType();
    }

    void setGroup(H5::Group assignedGroup);

    int getSize();

    void addDataPoint(std::string label, double x, double y, double z, enum_source_type sourceType, bool utilized,
                      LSAFixedState fixedType, std::string constraint, double adjX=0.0, double adjY=0.0, double adjZ=0.0, double sigX=0.0,
                     double sigY=0.0, double sigZ=0.0, double Cxx=0.0, double Cxy=0.0, double Cxz=0.0, double Cyy=0.0, double Cyz=0.0, double Czz=0.0);

    void addDataPoint(xyzExternal dataStruct);

    int writeToGroup(H5::Group assignedGroup);

    int readDataSetFromGroup(H5::Group pointsGroup);

    xyzExternal getDataPoint(int index);

private:

    void writeToBuffer(xyzInternal *buffer);

    void readToDataContainer(xyzInternal *buffer, hssize_t numberOfDataPointsInSet);

    //init the compound datatype for xyz dataset
    void InitXyzDataType();
};

class MeasurementsDataSet
{
private:
    hid_t measurementsMemoryType;
    hid_t measurementsFileType;
    std::vector<measurementsExternal> dataContainer;
    H5::H5File file;
    H5::Group group;
public:

    MeasurementsDataSet(){
        InitMeasurementDataType();
    }

    const int getSize();

    void addDataPoint(std::string measType, std::string from, std::string to, std::string tag,
                      double initMeas, double adjMeas, double rawResid, double relResid, double stdResid,
                      double redund, double minDectBias, double extVectMag, bool isBlunder, bool redundancyZero, bool isDerived, std::string at);

    void addDataPoint(measurementsExternal dataStruct);

    int writeToGroup(H5::Group measurementsGroup);

    int readDataSetFromGroup(H5::Group measurementsGroup);

    //readDataSetFromGroup must be called before this function to work
    const measurementsExternal getDataPoint(int index);

private:

    void writeToBuffer(measurementsInternal *buffer);

    void readToDataContainer(measurementsInternal *buffer, hssize_t numberOfDataPointsInSet);

    //init the compound datatype for xyz dataset
    void InitMeasurementDataType();
};

class LowestRedundDataSet
{
private:
    double dataContainer;
    H5::H5File file;
    H5::Group group;
public:

    LowestRedundDataSet():dataContainer(0){}

    void addDataPoint(double lowestRedundancy);

    int writeToGroup(H5::Group measurementsGroup);

    int readDataSetFromGroup(H5::Group measurementsGroup);

    //readDataSetFromGroup must be called before this function to work
    const double getDataPoint();
};

class BlundersExistDataSet
{
private:
    hid_t ENUMBOOLMEMORY;
    hid_t ENUMBOOLFILE;
    bool dataContainer;
    H5::H5File file;
    H5::Group group;
public:

    BlundersExistDataSet(){
        InitBlunderDataType();
    }

    void addDataPoint(bool blundersExist);

    int writeToGroup(H5::Group measurementsGroup);

    int readDataSetFromGroup(H5::Group measurementsGroup);

    //readDataSetFromGroup must be called before this function to work
    const bool getDataPoint();
private:

    //init the compound datatype for xyz dataset
    void InitBlunderDataType();

};

class ConvergenceHistDataSet
{
private:
    hid_t convergenceHistMemoryType;
    hid_t convergenceHistFileType;
    std::vector<convergenceHistExternal> dataContainer;
    H5::H5File file;
    H5::Group group;
public:

    ConvergenceHistDataSet(){
        InitconvergenceHistDataType();
    }

    const int getSize();

    void addDataPoint(int iterationNum, double RMSadj, double delta, double RMSrelResid, std::string status);

    void addDataPoint(convergenceHistExternal dataStruct);

    int writeToGroup(H5::Group adjustmentResultsGroup);

    int readDataSetFromGroup(H5::Group adjustmentResultsGroup);

    //readDataSetFromGroup must be called before this function to work
    const convergenceHistExternal getDataPoint(int index);

    const convergenceHistExternal back();

private:

    void writeToBuffer(convergenceHistInternal *buffer);

    void readToDataContainer(convergenceHistInternal *buffer, hssize_t numberOfDataPointsInSet);

    //init the compound datatype for xyz dataset
    void InitconvergenceHistDataType();
};

class SolverWariningsDataSet
{
private:
    hid_t solverWarningMemoryType;
    hid_t solverWarningFileType;
    std::vector<std::string> dataContainer;
    H5::H5File file;
    H5::Group group;
public:

    SolverWariningsDataSet(){
        initSolverWariningsDataType();
    }

    const int getSize();

    void addDataPoint(std::string warningString);

    int writeToGroup(H5::Group adjustmentResultsGroup);

    int readDataSetFromGroup(H5::Group adjustmentResultsGroup);

    //readDataSetFromGroup must be called before this function to work
    const std::string getDataPoint(int index);

    const std::string back();

private:

    void writeToBuffer(char **buffer);

    void readToDataContainer(solverWarningInternal *buffer, hssize_t numberOfDataPointsInSet);

    //init the compound datatype for xyz dataset
    void initSolverWariningsDataType();
};

class SolverErrorsDataSet
{
private:
    hid_t solverErrorMemoryType;
    hid_t solverErrorFileType;
    std::vector<std::string> dataContainer;
    H5::H5File file;
    H5::Group group;
public:

    SolverErrorsDataSet(){
        initSolverErrorsDataType();
    }

    int getSize() const;

    void addDataPoint(std::string warningString);

    int writeToGroup(H5::Group adjustmentResultsGroup);

    int readDataSetFromGroup(H5::Group adjustmentResultsGroup);

    //readDataSetFromGroup must be called before this function to work
    const std::string getDataPoint(int index);

    const std::string back();

private:

    void writeToBuffer(char **buffer);

    void readToDataContainer(solverErrorsInternal *buffer, hssize_t numberOfDataPointsInSet);

    //init the compound datatype for xyz dataset
    void initSolverErrorsDataType();
};

class SolverRunTypeDataSet
{
private:
    hid_t ENUMSOLVERMEMORY;
    hid_t ENUMSOLVERFILE;
    enum_solver_run_type dataContainer;
    H5::H5File file;
    H5::Group group;
public:

    SolverRunTypeDataSet():dataContainer(FALLBACK_TO_STABLE){
        InitSolverRunType();
    }

    void addDataPoint(enum_solver_run_type runType);

    int writeToGroup(H5::Group adjustmentResultsGroup);

    int readDataSetFromGroup(H5::Group adjustmentResultsGroup);

    //readDataSetFromGroup must be called before this function to work
    enum_solver_run_type getDataPoint() const;
private:

    //init the compound datatype for xyz dataset
    void InitSolverRunType();

};

class SolverExitTypeDataSet
{
private:
    hid_t ENUMSOLVEREXITMEMORY;
    hid_t ENUMSOLVEREXITFILE;
    lsa::enum_solver_return_code dataContainer;
    H5::H5File file;
    H5::Group group;
public:

    SolverExitTypeDataSet():dataContainer(lsa::UNKNOWN){
        InitSolverRunType();
    }

    void addDataPoint(lsa::enum_solver_return_code exitType);

    int writeToGroup(H5::Group adjustmentResultsGroup);

    int readDataSetFromGroup(H5::Group adjustmentResultsGroup);

    //readDataSetFromGroup must be called before this function to work
    lsa::enum_solver_return_code getDataPoint() const;
private:

    //init the compound datatype for xyz dataset
    void InitSolverRunType();

};

class StatisticsDataSet
{
private:
    hid_t statMemoryType;
    hid_t statFileType;
    statisticsExternal dataContainer;
public:

    StatisticsDataSet(){
        initStatisticsDataType();
        initContainer();
    }

    void addDataPoint(double relRMSresid, double stdDevUnitWieght, double APV, double angRMSresidSOA, double lenRMSresid, double lowerChiSq, double upperChiSq);

    void addDataPoint(statisticsExternal dataPoint);

    int writeToGroup(H5::Group adjustmentResultsGroup);

    int readDataSetFromGroup(H5::Group adjustmentResultsGroup);

    //readDataSetFromGroup must be called before this function to work
    statisticsExternal getDataPoint();

private:

    void initStatisticsDataType();
    void initContainer();
};

class SolutionCovarDataSet
{
private:
    H5::StrType STRING;
    std::vector<std::string> axisLabels;
    std::vector<std::vector<double> > covarianceMatrix;
    H5::H5File file;
    H5::Group group;
public:

    SolutionCovarDataSet():STRING(H5::StrType(H5::PredType::C_S1, H5T_VARIABLE)){}

    int getCovarRowCount() const;

    int getNumOfLabels() const;

    void addRowToMatrix(std::vector<double> newRow);

    void setMatrix(std::vector<std::vector<double> > matrix);

    void addAxisLabel(std::string newLabel);

    void setAllLabels(std::vector<std::string> labels);

    int writeToGroup(H5::Group adjustmentResultsGroup);

    int readDataSetFromGroup(H5::Group adjustmentResultsGroup);

    //readDataSetFromGroup must be called before this function to work
    const std::vector<double> getMatrixRow(int index);

    const std::string getLabel(int index);

private:

    void writeToBuffer(double *buffer);

    void readToMatrix(double *buffer, hssize_t numberOfRowsInMaxtrix);
};

/// Class to hold data and implement read write and dump of binary file.
class LSAH5File
{
private:
/// member data
    std::string fileName;      ///< name of H5 file
    H5::H5File readFile;
    H5::H5File writeFile;
    H5::Group adjustmentResultsGroup;
    H5::Group pointsGroup;
    H5::Group measurementsGroup;
    //every row in a data set relates to exactly one struct, every column in data set relates to a member of a struct
    int numOfStructsPerRow;
    ///Define Variable length string type for H5
    H5::StrType STRING;
    hid_t strType;
    ///Define Enum type for H5
    hid_t ENUMBOOLMEMORY;
    hid_t ENUMBOOLFILE;
    hid_t ENUMFIXEDMEMORY;
    hid_t ENUMSOURCEMEMORY;
    hid_t ENUMSOLVERMEMORY;
    hid_t ENUMSOLVERFILE;
    hid_t ENUMSOLVEREXITMEMORY;
    hid_t ENUMSOLVEREXITFILE;
    hid_t ENUMBINFILESTATUSMEMORY;
    enum_bool_type enumBool;
    LSAFixedState enumFixed;
    enum_source_type enumSource;
    enum_solver_run_type enumSolverRun;
    lsa::enum_solver_return_code enumSolverExit;
    enum_binary_file_status enumBinFileStat;

    void initDataTypes()
    {
        //define the number of structs per row. Should always be 1.
        numOfStructsPerRow = 1;
        //define the h5 version
        h5VersionContainer = HDF5_FILE_VERSION;
        //Define the LSA Version
        LSAVersionContainer = LSAVERSION_MAJOR_MINOR_PATCH;
        //init enum data types
        InitEnumDataTypes();
    }

public:
    //structs/variables used to hold data to be (written to/read from) the HDF5 file
    static const std::string HDF5_FILE_VERSION;

    std::string h5VersionContainer;
    std::string LSAVersionContainer;
    std::string dateCreatedContainer;
    //data set classes declared below
    std::unique_ptr<ProjCfgDataSet> projCfg;
    std::unique_ptr<PostProcInputDataSet> postProcInput;
    std::unique_ptr<ProbDescriptDataSet> probDescript;
    std::unique_ptr<LlhDataSet> llh;
    std::unique_ptr<InitialLlhDataSet> initialLlh;
    std::unique_ptr<XyxDataSet> xyz;
    std::unique_ptr<MeasurementsDataSet> measurements;
    std::unique_ptr<LowestRedundDataSet> lowestRedundancy;
    std::unique_ptr<BlundersExistDataSet> blundersExist;
    std::unique_ptr<ConvergenceHistDataSet> convergenceHist;
    std::unique_ptr<SolverWariningsDataSet> solverWarnings;
    std::unique_ptr<SolverErrorsDataSet> solverErrors;
    std::unique_ptr<SolverRunTypeDataSet> solverRunType;
    std::unique_ptr<SolverExitTypeDataSet> solverExitType;
    std::unique_ptr<StatisticsDataSet> statistics;
    std::unique_ptr<SolutionCovarDataSet> solutionCovariance;


    /// member functions
    LSAH5File(/*std::string fileName*/): STRING(H5::StrType(H5::PredType::C_S1, H5T_VARIABLE))
    {
        initContainers();
        strType = H5Tcopy(H5T_C_S1);
        H5Tset_size(strType, H5T_VARIABLE);
    }

    void createFile(std::string inputFileName);

    /// Write the binary file using this object; must strictly parallel ReadH5File.
    /// @return 0 ok, -1 if error occured
    int WriteH5File();

    /// Reads the file attributes (Version, LSA version, and date created) from the H5 file
    /// @return 0 ok, -1 if error occured
    int ReadFileAttributes();

    /// Read and print out the HDF5 file using this object; must strictly parallel WriteH5File.
    /// @return 0 ok, -1 if error occured
    int ReadH5File(std::string filename);
    
    /// Close the previously opened HDF5 file.
    void closeH5File();

    ///clear contents from existing data structures, free previously allocated memory,
    ///initialize to default values.  Do this before calling external fillers or populating
    ///from reading an hdf5 file.
    void initContainers();

private:
    /// Writes the file attributes (Version, LSA version, and date created) to the H5 file
    /// @return 0 ok, -1 if error occured
    int WriteFileAttributes();

    //init enum data types to be used in the .H5 files
    void InitEnumDataTypes(){
        ENUMBOOLMEMORY = H5Tenum_create(H5T_NATIVE_INT);
        H5Tenum_insert(ENUMBOOLMEMORY,            "FALSE",                    CPTR(enumBool, BOOL_FALSE));
        H5Tenum_insert(ENUMBOOLMEMORY,            "TRUE",                     CPTR(enumBool, BOOL_TRUE));

        ENUMBOOLFILE = H5Tcopy(ENUMBOOLMEMORY);

        ENUMFIXEDMEMORY = H5Tenum_create(H5T_NATIVE_INT);
        H5Tenum_insert(ENUMFIXEDMEMORY,           "FLOAT",                    CPTR(enumFixed, LSAFixedState::FLOATING));
        H5Tenum_insert(ENUMFIXEDMEMORY,           "FIXED",                    CPTR(enumFixed, LSAFixedState::FIXED));
        H5Tenum_insert(ENUMFIXEDMEMORY,           "CONSTRAINED",              CPTR(enumFixed, LSAFixedState::CONSTRAINED));

        ENUMSOURCEMEMORY = H5Tenum_create(H5T_NATIVE_INT);
        H5Tenum_insert(ENUMSOURCEMEMORY,          "PROVIDED",                 CPTR(enumSource, PROVIDED));
        H5Tenum_insert(ENUMSOURCEMEMORY,          "DERIVED_MEAN",             CPTR(enumSource, DERIVED_MEAN));
        H5Tenum_insert(ENUMSOURCEMEMORY,          "DERIVED_ENUO",             CPTR(enumSource, DERIVED_ENUO));
        H5Tenum_insert(ENUMSOURCEMEMORY,          "AUTOGENERATED",            CPTR(enumSource, AUTOGENERATED));

        ENUMSOLVERMEMORY = H5Tenum_create(H5T_NATIVE_INT);
        H5Tenum_insert(ENUMSOLVERMEMORY,       "FAST",                     CPTR(enumSolverRun, FAST));
        H5Tenum_insert(ENUMSOLVERMEMORY,       "STABLE",                   CPTR(enumSolverRun, STABLE));
        H5Tenum_insert(ENUMSOLVERMEMORY,       "FALLBACK_TO_STABLE",       CPTR(enumSolverRun, FALLBACK_TO_STABLE));

        ENUMSOLVERFILE = H5Tcopy(ENUMSOLVERMEMORY);

        ENUMSOLVEREXITMEMORY = H5Tenum_create(H5T_NATIVE_INT);
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "CMDINVALID",               CPTR(enumSolverExit, lsa::CMDINVALID));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "UNKNOWN",                  CPTR(enumSolverExit, lsa::UNKNOWN));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "NOOUTFILE",                CPTR(enumSolverExit, lsa::NOOUTFILE));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "NORMAL",                   CPTR(enumSolverExit, lsa::NORMAL));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "CMDLINEUSAGE",             CPTR(enumSolverExit, lsa::CMDLINEUSAGE));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "CMDLINERRRORS",            CPTR(enumSolverExit, lsa::CMDLINERRRORS));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "USERVALIDATION",           CPTR(enumSolverExit, lsa::USERVALIDATION));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "INPUTINVALID",             CPTR(enumSolverExit, lsa::INPUTINVALID));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "OUTPUTFILEFAIL",           CPTR(enumSolverExit, lsa::OUTPUTFILEFAIL));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "INPUTFILEFAIL",            CPTR(enumSolverExit, lsa::INPUTFILEFAIL));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "EARLYEXIT",                CPTR(enumSolverExit, lsa::EARLYEXIT));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "PROBLEMUNDERDETERMINED",   CPTR(enumSolverExit, lsa::PROBLEMUNDERDETERMINED));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "PROBLEMSINGULAR",          CPTR(enumSolverExit, lsa::PROBLEMSINGULAR));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "UNABLEAPRIORI",            CPTR(enumSolverExit, lsa::UNABLEAPRIORI));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "NODATA",                   CPTR(enumSolverExit, lsa::NODATA));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "NOSTATE",                  CPTR(enumSolverExit, lsa::NOSTATE));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "SINGULARCOV",              CPTR(enumSolverExit, lsa::SINGULARCOV));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "SINGULARMEASCOV",          CPTR(enumSolverExit, lsa::SINGULARMEASCOV));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "SOLUTIONSINGULAR",         CPTR(enumSolverExit, lsa::SOLUTIONSINGULAR));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "INVALIDDIRSET",            CPTR(enumSolverExit, lsa::INVALIDDIRSET));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "GEOIDFILEFAIL",            CPTR(enumSolverExit, lsa::GEOIDFILEFAIL));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "EIGENFAIL",                CPTR(enumSolverExit, lsa::EIGENFAIL));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "MEMORYALLOCATEFAIL",       CPTR(enumSolverExit, lsa::MEMORYALLOCATEFAIL));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "COMPFILEFAIL",             CPTR(enumSolverExit, lsa::COMPFILEFAIL));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "DATFILEFAIL",              CPTR(enumSolverExit, lsa::DATFILEFAIL));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "BINFILEFAIL",              CPTR(enumSolverExit, lsa::BINFILEFAIL));
        H5Tenum_insert(ENUMSOLVEREXITMEMORY,      "BINFILEOBSOLELE",          CPTR(enumSolverExit, lsa::BINFILEOBSOLELE));


        ENUMSOLVEREXITFILE = H5Tcopy(ENUMSOLVEREXITMEMORY);

        ENUMBINFILESTATUSMEMORY = H5Tenum_create(H5T_NATIVE_INT);
        H5Tenum_insert(ENUMBINFILESTATUSMEMORY,   "BIN_FILE_PARSING_FAILURE", CPTR(enumBinFileStat, BIN_FILE_PARSING_FAILURE));
        H5Tenum_insert(ENUMBINFILESTATUSMEMORY,   "BIN_FILE_STALE",           CPTR(enumBinFileStat, BIN_FILE_STALE));
        H5Tenum_insert(ENUMBINFILESTATUSMEMORY,   "BIN_FILE_FORMAT_OBSOLETE", CPTR(enumBinFileStat, BIN_FILE_FORMAT_OBSOLETE));
        H5Tenum_insert(ENUMBINFILESTATUSMEMORY,   "BIN_FILE_UNABLE_TO_OPEN",  CPTR(enumBinFileStat, BIN_FILE_UNABLE_TO_OPEN));
        H5Tenum_insert(ENUMBINFILESTATUSMEMORY,   "BIN_FILE_NOT_PARSED",      CPTR(enumBinFileStat, BIN_FILE_NOT_PARSED));
        H5Tenum_insert(ENUMBINFILESTATUSMEMORY,   "BIN_FILE_NOT_FOUND",       CPTR(enumBinFileStat, BIN_FILE_NOT_FOUND));
        H5Tenum_insert(ENUMBINFILESTATUSMEMORY,   "BIN_FILE_NO_SOLUTION",     CPTR(enumBinFileStat, BIN_FILE_NO_SOLUTION));
        H5Tenum_insert(ENUMBINFILESTATUSMEMORY,   "BIN_FILE_FOUND_SOLUTION",  CPTR(enumBinFileStat, BIN_FILE_FOUND_SOLUTION));
        H5Tenum_insert(ENUMBINFILESTATUSMEMORY,   "BIN_FILE_VALID",           CPTR(enumBinFileStat, BIN_FILE_VALID));
    }
}; // end class LSAH5File

#endif   // define LSA_OUTPUT_FILE_INCLUDE
