/*
	Copyright (c) 2015-2024 Applied Research Laboratories, The University of Texas
	at Austin (ARL:UT).
	
	SALSA is free software: you can redistribute it and/or modify it under the
	terms of the GNU General Public License version 3 (GPL-3.0-only) as published
	by the Free Software Foundation.
	
	SALSA is distributed in the hope that it will be useful, but WITHOUT ANY
	WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
	A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License along with
	SALSA.  If not, see https://www.gnu.org/licenses/.
*/
#ifndef LSA_MEAN_INCLUDE
#define LSA_MEAN_INCLUDE

#include <string>

#include "LSARecord.hpp"
#include "LSAModifier.hpp"

class LSAMean : public LSARecord {
public:
   // member data ------------------------------------------------------

   // labels
   std::string              label;  ///< label for the derived point
   std::vector<std::string> points; ///< label of points used to compute mean

   // sigma
   double      Sigma;       ///< sigma to apply
   std::string linUnits;    ///< units for linear measurements

     // UI display
   static const int NUM_UI_DISPLAY_COLUMNS;

   // member functions -------------------------------------------------

   /// constructor
   LSAMean() : LSARecord(LSAType::MEAN), label("unknown"), Sigma(0.0), linUnits("M") {}

   /// destructor
   virtual ~LSAMean() { }

      LSAMean(std::string label, double Sigma, std::string linUnits, std::vector<std::string> points) : LSARecord(LSAType::MEAN), label(label), Sigma(0.0), linUnits("M"), points(points) {}

   /// Parse a string from a single line in the LSA file.
   /// @param line single line read from LSA file
   /// @return true if successful
   virtual void fromString(const std::string& line);

   /// write the object as a string for the LSA file.
   /// param out, an ostream reference to the output filestream or stringstream
   virtual void writeLSAString(std::ostream & out) const;

   /// Get the number of columns used to display this record type in the Project Navigator
   /// @return the number of columns to display
   virtual int getNumDisplayColumns() const { return NUM_UI_DISPLAY_COLUMNS; }

   /// Get a string to display in a given column in the Project Navigator
   /// @param the column number to display
   /// @return the string to display in the UI
   virtual std::string getUIColumnData(int columnNumber) const;

   /// If this record refers to a height modifier with label oldLabel, change the reference to refer to newLabel instead
   /// @param oldLabel the old label
   /// @param newLabel the new label
   virtual void renameModifierLabel(LSAType type, std::string oldLabel, std::string newLabel) {}

   std::string  getLabel() const { return label; }
   virtual bool referencesPosition(const std::string& position) const;
   virtual void renamePosition(std::string oldLabel, std::string newLabel);

   // Note: MEAN records can never cause position estimates to be autogenerated, so return nothing here
   virtual std::vector<std::string> getReferencedPositions() const {return std::vector<std::string>();}
   void validatePositions(std::set<std::string> allPositionsIncludingAutogen, std::list<std::string> derivedPoints);

   virtual bool referencesModifier(LSAType modifierType, std::string label) const { return false; }
   virtual bool supportsModifier(ModifierKeyword keyword) const { return false; }
   virtual std::string getModifierLabel(ModifierKeyword keyword) const { return ""; }
   virtual bool vscaIsNumeric() const { return false; }

   bool hasValidCovariance() const { return true; }
   virtual LSAModifier* getModifiers() { return NULL; }

   std::string getSingleDATString() const;

private:
   /// Output as a string (one line) to display in the UI. Pure virtual
   /// @return a string to display in the UI
   virtual std::string getUIName() const;

   /// Output as a string (one line) to display in the UI. Pure virtual
   /// @return a string to display in the UI
   virtual std::string getUIDetails() const;

}; // end class LSAMean

#endif   // LSA_MEAN_INCLUDE
