/*
	Copyright (c) 2015-2024 Applied Research Laboratories, The University of Texas
	at Austin (ARL:UT).
	
	SALSA is free software: you can redistribute it and/or modify it under the
	terms of the GNU General Public License version 3 (GPL-3.0-only) as published
	by the Free Software Foundation.
	
	SALSA is distributed in the hope that it will be useful, but WITHOUT ANY
	WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
	A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License along with
	SALSA.  If not, see https://www.gnu.org/licenses/.
*/
/// @file LSAPoint.cpp  Class LSAPoint, data for the *.LSA file record POS
///                     3-D XYZ coordinate position

#include <string>
#include <ostream>
#include <set>
#include <stdexcept>
#include <iterator>

#include "StringUtils.hpp"
#include "stl_helpers.hpp"
#include "Position.hpp"

#include "lsaUtils.hpp"
#include "LSAPosG.hpp"

// gnsstk
#include "Vector.hpp"
#include "Matrix.hpp"
#include "Position.hpp"

using namespace std;
using namespace gnsstk;
using namespace gnsstk::StringUtils;

// CONSTANTS
const int LSAPosG::NUM_UI_DISPLAY_COLUMNS = 5;

void LSAPosG::setCovariance(double cnn, double cne, double cnu, double cee, double ceu, double cuu)
{
    covnn = cnn;
    covne = cne;
    covnu = cnu;
    covee = cee;
    coveu = ceu;
    covuu = cuu;

    hasCovariance = true;

    fixedState = LSAFixedState::CONSTRAINED;

}

//------------------------------------------------------------------------------------
// Parse a string from a single line in the LSA file.
// param line single line read from LSA file
// return true if successful
void LSAPosG::fromString(const string& line)
{
    if (line.empty()) return;

    modifiers.clearModifiers();

    int n, index;
    vector<string> F;

    std::deque<std::string> optionalParms;

    string str(line);                // copy const line
    stripTrailing(str,"\n");
    stripTrailing(str,"\r");
    stripTrailing(str," ");
    stripLeading(str," ");

    // Steal the General Notes before continuing.
    textNotes = QString::fromStdString(extractXMLFromString(str, RecordTags::TextNotes, true));
    // split into fields
    F = splitWithDoubleQuotes(str,' ');
    n = F.size();

    bool goodParse= true;

    //handle legacy AutogeneratedPoints.lsa file from v1.0.0 to 1.1.2
    vector<string>::iterator autogenKeywordIndex = std::find( F.begin(), F.end(), string("AUTOGEN") );
    if(autogenKeywordIndex!=F.end())
    {
        parseWarnings.push_back("Saving AUTOGEN POSG files to .lsa files is no longer supported.");
        F.pop_back();
    }
    vector<string>::iterator vscaKeywordIndex = std::find( F.begin(), F.end(), string("VSCA") );
    if(vscaKeywordIndex!=F.end())
    {
        index = vscaKeywordIndex-F.begin();

        std::string secondParm = F.at(index+1); // make a copy so upperCase won't change the value in F
        bool vscaValueUsed = (gnsstk::StringUtils::upperCase(secondParm) == "VALUE");


        if ( !vscaValueUsed )
        {
            optionalParms.push_back(F.at(index));
            optionalParms.push_back(F.at(index+1));

            F.pop_back();
            F.pop_back();
        }
        else
        {
            optionalParms.push_back(F.at(index));
            optionalParms.push_back(F.at(index+1));
            optionalParms.push_back(F.at(index+2));

            F.pop_back();
            F.pop_back();
            F.pop_back();
        }

        n = F.size();
    }
    if(optionalParms.size()>0)
    {
        goodParse = modifiers.parseOptionalParms(optionalParms, LSAType::POSG, label, &parseWarnings);
    }


    if(n < 4 )
    {
        addNumFieldsWarning(LSAType::POSC, label);
        return;
    }

    // Search for optional constraint modifiers and remove them from F
    std::string valueFltConFix;
    std::string valueNEU;

    if (isFltConFix(F[2]) && isNEU(F[3]) )
    {
        valueNEU = F.at(3);
        F.erase(F.begin() + 3);

        valueFltConFix = F.at(2);
        F.erase(F.begin() + 2);
    }
    else if (isFltConFix(F[2]))
    {
        valueFltConFix = F.at(2);
        F.erase(F.begin() + 2);
    }
    else if (isNEU(F[2]))
    {
        valueNEU = F.at(2);
        F.erase(F.begin() + 2);
    }
    n = F.size();
    // Note values for fixConFlt are set below after hasCovariance is parsed

    if (!valueNEU.empty())
    {
        validateString(valueNEU, LSAFieldType::FIXED_STATE, "n,e,u,ne,nu,eu,en,ue,un,neu,nue,enu,eun,uen,une");
    }
    if (!valueFltConFix.empty())
    {
        validateString(valueFltConFix, LSAFieldType::FIXED_STATE, "flt,con,fix");
    }
    setFixedConstraints(valueNEU);

    label = F[1];
    n = F.size();

    // Search the contents of the file line after the station name to see if the "ortho" flag
    // exists.
    vector<string>::const_iterator orthoIterator = std::find(std::next(F.begin(), 2),
                                                             F.end(), lsa::FLAG_ORTHOMETRIC);
    bool isOrthometric = false;
    unsigned int offsetVal;
    if(orthoIterator != F.end())
    {
        isOrthometric = true;
        heightIsEllipsoidal = false;
        offsetVal = 1;
    }

    else
    {
        offsetVal = 0;
    }

    if( (n == 8 && !isOrthometric) || (n==9 && isOrthometric) ) // decimal lat lon without covariance
    {
        useDecimalDegrees = true;
        latDecDeg = validateDoubleMinMax( F[2], LSAFieldType::LAT_DEC_DEG , -90, 90);
        latDir = validateString(          F[3], LSAFieldType::LAT_DIR,      "N,S,n,s" );
        lonDecDeg = validateDoubleMinMax( F[4], LSAFieldType::LAT_DEC_DEG,  -360, 360, true, true );
        lonDir = validateString(          F[5], LSAFieldType::LON_DIR,      "W,E,w,e" );

        height = validateDouble(          F[6], LSAFieldType::HEIGHT);
        heightUnits = validateString(     F[7], LSAFieldType::HEIGHT_UNITS, "cm,m,ft") ;

        hasCovariance = false;
    }
    else if( (n == 14 && !isOrthometric) || (n == 15 && isOrthometric) ) // decimal lat lon with covariance
    {
        useDecimalDegrees = true;
        latDecDeg = validateDoubleMinMax( F[2], LSAFieldType::LAT_DEC_DEG, -90, 90 );
        latDir = validateString(          F[3], LSAFieldType::LAT_DIR,     "N,S,n,s" );
        lonDecDeg = validateDoubleMinMax( F[4], LSAFieldType::LAT_DEC_DEG, -360, 360, true, true );
        lonDir = validateString(          F[5], LSAFieldType::LON_DIR,     "W,E,w,e" );

        height = validateDouble(          F[6], LSAFieldType::HEIGHT);
        heightUnits = validateString(     F[7], LSAFieldType::HEIGHT_UNITS, "cm,m,ft") ;

        hasCovariance = true;
        covnn = validateDouble( F[8 + offsetVal],  LSAFieldType::COVARIANCE );
        covne = validateDouble( F[9 + offsetVal],  LSAFieldType::COVARIANCE );
        covnu = validateDouble( F[10 + offsetVal], LSAFieldType::COVARIANCE );
        covee = validateDouble( F[11 + offsetVal], LSAFieldType::COVARIANCE );
        coveu = validateDouble( F[12 + offsetVal], LSAFieldType::COVARIANCE );
        covuu = validateDouble( F[13 + offsetVal], LSAFieldType::COVARIANCE );
    }
    else if( (n == 12 && !isOrthometric) || (n == 13 && isOrthometric) ) // DMS lat lon without covariance
    {
        useDecimalDegrees = false;
        latDeg = validateIntBool( latDMSIsNeg, F[2], LSAFieldType::LAT_DEG, -90,   90 );
        latMin = validateIntMinMax(    F[3], LSAFieldType::LAT_MIN,   0,   59 );
        latSec = validateDoubleMinMax( F[4], LSAFieldType::LAT_SEC, 0.0, 60.0, false, true);
        //don't allow 90 1' 1" (which will pass the above validation) - Fix to Bug #1212
//        validateDMSBool(latDMSIsNeg,latDeg,latMin,latSec,LSAFieldType::DMS,-90,90,false,false);
        LSARecord::validateDMSBool(latDMSIsNeg,latDeg,latMin,latSec,-90.0,90.0, &parseWarnings);
        latDir = validateString(       F[5], LSAFieldType::LAT_DIR, "n,s" );

        lonDeg = validateIntBool( lonDMSIsNeg, F[6], LSAFieldType::LON_DEG,  -359,  359 );
        lonMin = validateIntMinMax(    F[7], LSAFieldType::LON_DEG,    0,   59 );
        lonSec = validateDoubleMinMax( F[8], LSAFieldType::LON_SEC,  0.0, 60.0, false, true);
        lonDir = validateString(       F[9], LSAFieldType::LON_DIR, "w,e" );

        height = validateDouble(       F[10], LSAFieldType::HEIGHT);
        heightUnits = validateString(  F[11], LSAFieldType::HEIGHT_UNITS, "cm,m,ft") ;

        hasCovariance = false;
    }
    else if( (n == 18 && !isOrthometric) || (n==19 && isOrthometric) ) // DMS lat lon with covariance
    {
        useDecimalDegrees = false;

        latDeg = validateIntBool( latDMSIsNeg, F[2], LSAFieldType::LAT_DEG,   -90,   90 );
        latMin = validateIntMinMax(    F[3], LSAFieldType::LAT_MIN,   0,   59 );
        latSec = validateDoubleMinMax( F[4], LSAFieldType::LAT_SEC, 0.0, 60.0, false, true);
        //don't allow 90 1' 1" (which will pass the above validation) - Fix to Bug #1212
//        validateDMSBool(latDMSIsNeg,latDeg,latMin,latSec,LSAFieldType::DMS,-90,90,false,false);
        LSARecord::validateDMSBool(latDMSIsNeg,latDeg,latMin,latSec,-90.0,90.0, &parseWarnings);
        latDir = validateString(       F[5], LSAFieldType::LAT_DIR, "n,s" );

        lonDeg = validateIntBool( lonDMSIsNeg, F[6], LSAFieldType::LON_DEG,    -359,  359 );
        lonMin = validateIntMinMax(    F[7], LSAFieldType::LON_DEG,    0,   59 );
        lonSec = validateDoubleMinMax( F[8], LSAFieldType::LON_SEC,  0.0, 60.0, false, true);
        lonDir = validateString(       F[9], LSAFieldType::LON_DIR, "w,e" );

        height = validateDouble(       F[10], LSAFieldType::HEIGHT);
        heightUnits = validateString(  F[11], LSAFieldType::HEIGHT_UNITS, "cm,m,ft") ;

        hasCovariance = true;
        covnn = validateDouble(F[12 + offsetVal], LSAFieldType::COVARIANCE);
        covne = validateDouble(F[13 + offsetVal], LSAFieldType::COVARIANCE);
        covnu = validateDouble(F[14 + offsetVal], LSAFieldType::COVARIANCE);
        covee = validateDouble(F[15 + offsetVal], LSAFieldType::COVARIANCE);
        coveu = validateDouble(F[16 + offsetVal], LSAFieldType::COVARIANCE);
        covuu = validateDouble(F[17 + offsetVal], LSAFieldType::COVARIANCE);
    }
    else
    {
        addNumFieldsWarning(LSAType::POSG, label);
    }

    // set fixedState
    valueFltConFix = gnsstk::StringUtils::upperCase(valueFltConFix);
    if (valueFltConFix.empty() && hasCovariance)
    {
        fixedState = LSAFixedState::CONSTRAINED;
    }
    else if (valueFltConFix == "FLT")
    {
        fixedState = LSAFixedState::FLOATING;
    }
    else if (valueFltConFix == "CON")
    {
        fixedState = LSAFixedState::CONSTRAINED;
    }
    else if (valueFltConFix == "FIX")
    {
        fixedState = LSAFixedState::FIXED;
    }

    return;
}

//------------------------------------------------------------------------------------
// Set the constraints
// @param input any combination of E | N | U to indicate constrained axes
void LSAPosG::setFixedConstraints(string input)
{
    input = gnsstk::StringUtils::upperCase(input);

    // Reset constraints
    isNorthFixed = isEastFixed = isUpFixed = false;

    if ( input.find("N") !=std::string::npos )
    {
        isNorthFixed = true;
    }
    if ( input.find("E") !=std::string::npos )
    {
        isEastFixed = true;
    }
    if ( input.find("U") !=std::string::npos )
    {
        isUpFixed = true;
    }

    return;
}


//------------------------------------------------------------------------------------
// Output as a string for the LSA file.
// param out, an ostream reference to the output filestream or stringstream
void LSAPosG::writeLSAString(std::ostream & out) const
{
    std::string comment = isCommented ? "#" : "";

    out << comment << "POSG " << addQuotes(label);

    // FLT-CON-FIX
    if (isNorthFixed && isEastFixed && isUpFixed)
    {
        out << " Fix";
    }
    else if (fixedState == LSAFixedState::FLOATING)
    {
        out << " Flt";
    }
    else if (fixedState == LSAFixedState::CONSTRAINED)
    {
        out << " Con";
    }
    else if (fixedState == LSAFixedState::FIXED)
    {
        out << " Fix";
    }

    // NEU
    std::ostringstream neuOSS;
    if (isNorthFixed)
    {
        neuOSS << "N";
    }
    if (isEastFixed)
    {
        neuOSS << "E";
    }
    if (isUpFixed)
    {
        neuOSS << "U";
    }
    if (!neuOSS.str().empty())
    {
        out << " " << neuOSS.str();
    }

    // Lat and Lon

    int anglePrecision;
    out << std::fixed;
    if (useDecimalDegrees)
    {
        anglePrecision = grabNumDigits(getRecType(), lsa::UNITS_DEG);
        out << std::setprecision(anglePrecision);
        out << " " << latDecDeg << " " << latDir << " " << lonDecDeg << " " << lonDir;
    }
    else
    {
        anglePrecision = grabNumDigits(getRecType(), lsa::UNITS_SOA);
        out << std::setprecision(anglePrecision);
        std::string latSign = latDMSIsNeg ? "-" : "";
        out << " " << latSign << latDeg << " " << latMin << " " << latSec << " " << latDir;
        std::string lonSign = lonDMSIsNeg ? "-" : "";
        out << " " << lonSign << lonDeg << " " << lonMin << " " << lonSec << " " << lonDir;
    }

    // Height
    int heightPrecision = grabNumDigits(getRecType(), heightUnits);
    out << std::setprecision(heightPrecision) << " " << height << " " << heightUnits;
    if(!heightIsEllipsoidal)
    {
        out << " " << lsa::FLAG_ORTHOMETRIC;
    }

    // covariance
    if (hasCovariance)
    {
        out << " ...\n";
        int w = 18;
        out << std::scientific << std::setprecision(lsa::NUM_DECIMALS_COVARIANCE);
        out << comment << setw(w) << covnn << " " << setw(w) << covne << " " << setw(w) << covnu << " ...\n";
        out << comment << setw(w) << ""    << " " << setw(w) << covee << " " << setw(w) << coveu << " ...\n";
        out << comment << setw(w) << ""    << " " << setw(w) << ""    << " " << setw(w) << covuu;
    }

    std::string modString = modifiers.getLSAString();
    if (!modString.empty())
    {
        out << " ...\n";
        out << comment << modString;
    }
    
    if (!textNotes.isEmpty())
    {
        out << " ...\n";
        // put the text notes at the end of the record.
        out << RecordTags::TextNotes.first + textNotes.toStdString() + RecordTags::TextNotes.second;
    }
    
    out << "\n";

   return;
}

// Get a string to display in a given column in the Project Navigator
// @param the column number to display
// @return the string to display in the UI
std::string LSAPosG::getUIColumnData(int columnNumber) const
{
    std::string retVal = "";

    switch (columnNumber)
    {
    case 0:
        retVal = asTypeString();
        break;
    case 1:
        retVal = getUIName();
        break;
    case 2:
        // SCJ TODO: vsca refactoring needed
        // retVal = gnsstk::StringUtils::asString(groupVSCA * modifiers.getVSCAValue(), 3);
        break;
    case 3:
        retVal = getUIDetails();
        break;
    case 4:
        retVal = modifiers.getUIDetails();
        break;
    }

    return retVal;
}

void LSAPosG::renameModifierLabel(LSAType lsaType, std::string oldLabel, std::string newLabel)
{
    modifiers.modifyLabel(lsaType, oldLabel, newLabel);

    return;
}

std::vector<std::string> LSAPosG::getReferencedPositions() const
{
    std::vector<std::string> returnValues;
    returnValues.push_back(label);

    return returnValues;
}

//------------------------------------------------------------------------------------
// Output as a string (one line) to display in the UI. Pure virtual
// @return a string to display in the UI
std::string LSAPosG::getUIName() const
{    
    return label;
}

//------------------------------------------------------------------------------------
// Output as a string (one line) to display in the UI. Pure virtual
// @return a string to display in the UI
std::string LSAPosG::getUIDetails() const
{
    std::ostringstream oss;

    // fixed
    if ( (isNorthFixed && isEastFixed && isUpFixed) || fixedState == LSAFixedState::FIXED )
    {
        oss << " Fix";
    }
    else
    {
        if (isNorthFixed && isEastFixed)
        {
            oss << " NE";
        }
        else if (isNorthFixed && isUpFixed)
        {
            oss << " NU";
        }
        else if (isEastFixed && isUpFixed)
        {
            oss << " EU";
        }
        else if (isNorthFixed)
        {
            oss << " N";
        }
        else if (isEastFixed)
        {
            oss << " E";
        }
        else if (isUpFixed)
        {
            oss << " U";
        }
    }

    // Lat and Lon
    if (useDecimalDegrees)
    {
        oss << std::fixed << std::setprecision(5) ;
        oss << " " << setw(10) << latDecDeg << " " << latDir;
        oss << " " << setw(10) << lonDecDeg << " " << lonDir;
    }
    else
    {   oss << std::fixed << std::setprecision(3);
        std::string latSign = latDMSIsNeg ? "-" : "";
        oss << std::right << " " << setw(3) << latSign << latDeg << " " << setw(2) << latMin << " " << setw(6) << latSec << " " << latDir;

        std::string lonSign = lonDMSIsNeg ? "-" : "";
        oss << std::right << " " << setw(3) << lonSign << lonDeg << " " << setw(2) << lonMin << " " << setw(6) << lonSec << " " << lonDir;
    }

    // Height
    oss << std::fixed << std::setprecision(3);
    oss << " " << setw(8) << height << " " << heightUnits;


    std::string debug = oss.str();
    return debug;
}


void LSAPosG::fromECEFXYZCoords(double X, double Y, double Z)
{
    gnsstk::Position position(X, Y, Z, gnsstk::Position::Cartesian);

    useDecimalDegrees = true;

    // latitude
    latDecDeg = position.getGeodeticLatitude();
    latDir = "N";

    // longitude
    lonDecDeg = position.getLongitude();
    lonDir = "E";

    // initial height
    height = position.getHeight();
    heightUnits = "m";

    return;
}

void LSAPosG::getLatLonHeight(double &lonOut, double &latOut, double &heightOut) const
{
    double lat, lon;
    if (useDecimalDegrees)
    {
        lat = latDecDeg;
        lon = lonDecDeg;
    }
    else // lat and lon in DMS
    {
        lat = (double)::abs(latDeg) + (double)latMin/60 + latSec/3600;
        if(latDeg<0) lat *= -1.;

        lon = (double)::abs(lonDeg) + (double)lonMin/60 + lonSec/3600;
        if(lonDeg<0) lon *= -1.;
    }

    // Make sure lat is N and lon is E for use in gnsstk::position
    if ( latDir.compare("S") == 0)
    {
        lat *= -1;
    }
    if ( lonDir.compare("W") == 0)
    {
        lon = 360.0 - lon;
    }

    // convert length units to meters
    static const string M("m");
    double fact = convertTo(M, 1.0, heightUnits);
/*
    gnsstk::Position position(lat, lon, fact*height, gnsstk::Position::Geodetic);
    latOut = position.getGeodeticLatitude();
    lon = position.getLongitude();
    height = position.getHeight();
*/
    lonOut = lon;
    latOut = lat;
    heightOut = height*fact;

    return;
}

bool LSAPosG::referencesModifier(LSAType modifierType, std::string label) const
{
    if      (modifierType == LSAType::VSCA)  return (modifiers.getVSCALabel() == label);
    else if (modifierType == LSAType::UNCR) return (modifiers.getUncrLabel() == label);
    else if (modifierType == LSAType::HGHT)
    {
       return ( modifiers.getHeightFromLabel() == label || modifiers.getHeightToLabel() == label);
    }

    return false;
}

bool LSAPosG::hasValidCovariance() const
{
    if (isNorthFixed && isEastFixed && isUpFixed)
    {
        return true;
    }

    if (fixedState == LSAFixedState::FLOATING)
    {
        return true;
    }
    else if( fixedState == LSAFixedState::FIXED)
    {
        return true;
    }
    else if (fixedState == LSAFixedState::CONSTRAINED && hasCovariance)
    {
        bool covIsPositiveSemiDefinite = isPositiveSemiDefinite(covnn, covne, covnu, covee, coveu, covuu);

        if (covIsPositiveSemiDefinite)
        {
            return true;
        }
        else
        {
            return false;
        }
    }

    return false;
}

double LSAPosG::giveStandardLat() const
{
    double lat;
    useDecimalDegrees ? lat = latDecDeg : lat = DMSToDeg(latDMSIsNeg, latDeg, latMin, latSec);
    if(latDir.compare("S") == 0)
    {
        lat *= -1.0;
    }

    return lat;
}

double LSAPosG::giveStandardLon(bool forcePos) const
{
    double lon;
    useDecimalDegrees ? lon = lonDecDeg : lon = DMSToDeg(lonDMSIsNeg, lonDeg, lonMin, lonSec);
    if(lonDir.compare("W") == 0)
    {
        lon *= -1.0;
    }

    if(forcePos && lon < 0.0)
    {
        lon += 360.0;
    }

    return lon;
}

//------------------------------------------------------------------------------------
//------------------------------------------------------------------------------------
