/*
	Copyright (c) 2015-2024 Applied Research Laboratories, The University of Texas
	at Austin (ARL:UT).
	
	SALSA is free software: you can redistribute it and/or modify it under the
	terms of the GNU General Public License version 3 (GPL-3.0-only) as published
	by the Free Software Foundation.
	
	SALSA is distributed in the hope that it will be useful, but WITHOUT ANY
	WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
	A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
	
	You should have received a copy of the GNU General Public License along with
	SALSA.  If not, see https://www.gnu.org/licenses/.
*/
/// @file LSARecord.hpp Pure virtual base class encapsulating records in LSA *.lsa
///    files. Includes record type, input from string and output strings.
#ifndef LSA_RECORD_INCLUDE
#define LSA_RECORD_INCLUDE


// disable some MSVC compiler warnings
#pragma warning(disable:4290)


#include <string>
#include <sstream>
#include <vector>
#include <set>
#include <map>

#include <lsaUtils.hpp>
#include <LSAModifier.hpp>
#include "LSAType.hpp"
#include "LSAFieldType.hpp"
#include "LSAFixedState.hpp"
#include "StringUtils.hpp"
#include "LSAConstants.hpp"

// configure windows to only use two digit exponents when possible
static void formatExponent()
{
#ifdef _WIN32
    #if (_MSC_VER < 1900)//Visual Studio 2015
        _set_output_format(_TWO_DIGIT_EXPONENT);
    #endif
#endif
}

namespace RecordTags
{
    const std::pair<std::string, std::string> TextNotes = {"<TXNS>", "</TXNS>"};
};

/// Virtual base class encapsulating records in *.lsa files.
/// Only data members are is the record type and unique identifier.
/// Declares an interface that includes input from a string (from *.lsa files),
/// output to a (*.lsa file) string, and output to a human-readable string.
/// It also declares boolean functions that determine the kind of record.
class LSARecord {

public:

    bool isCommented;
    bool isAutogenerated; ///< true for include file used to store autogenerated POSG records.  If true, file will not be saved.

    std::vector<std::string> parseWarnings;

    /// used to present warnings to the user.  Rarely cleared.
    std::set<std::string> warningMessages_persistent;

    /// used to present warnings to the user in the gui.
    /// Contents are frequently cleared and regenerated in GuiModel::checkForMissingAndDisabledReferences
    std::set<std::string> warningMessages_generated;

    /// Constructor
    LSARecord(LSAType lsaType = LSAType::Unknown) : type(lsaType), isCommented(false), isAutogenerated(false) { warningMessages_generated.clear(); }
    LSARecord(bool isAutogen, LSAType lsaType) : type(lsaType), isCommented(false), isAutogenerated(isAutogen) { warningMessages_generated.clear(); }

    /// Destructor
    virtual ~LSARecord() {}

    /// Assignment operator
    LSARecord& operator=(const LSARecord& rhs)
    {
        if(this != &rhs)
        {
          type = rhs.type;
          isCommented = rhs.isCommented;
          isAutogenerated = rhs.isAutogenerated;
          parseWarnings = rhs.parseWarnings;
          warningMessages_persistent = rhs.warningMessages_persistent;
          warningMessages_generated = rhs.warningMessages_generated;
        }

        return *this;

    }

    bool hasParseWarnings() const { return parseWarnings.size() > 0; }

    /// Return the record type
    LSAType getRecType(void) const
      { return type; }

    /// Return the record type as a string
    std::string asTypeString(void) const
      { return type.asString(); }

    /// Parse a string from a single line in the LSA file. Pure virtual
    /// @return true if successful
    virtual void fromString(const std::string& line) = 0;

    /// Output as a string (one line) for the LSA file. Pure virtual
    /// @param out an ostream for the output lsa file
    virtual void writeLSAString(std::ostream & out) const = 0;

    /// Get the single line string representation of this LSARecord
    /// @return the contents of writeLSAString with all "..." and line feeds removed
    std::string getSingleLSAString() const;

    void setIsAutogenerated(bool isAutogen) {isAutogenerated = isAutogen;}

    /// Output as a string (one line) to display in the UI. Pure virtual
    /// @return a string to display in the UI
    virtual std::string getUIName() const = 0;

    /// Output as a string (one line) to display in the UI. Pure virtual
    /// @return a string to display in the UI
    virtual std::string getUIDetails() const = 0;

    /// Get the number of columns used to display this record type in the Project Navigator
    /// @return the number of columns to display
    virtual int getNumDisplayColumns() const = 0;

    /// Get a string to display in a given column in the Project Navigator
    /// @param the column number to display
    /// @return the string to display in the UI
    virtual std::string getUIColumnData(int columnNumber) const = 0;

    /// If this record refers to a height modifier with label oldLabel, change the reference to refer to newLabel instead
    /// @param oldLabel the old label
    /// @param newLabel the new label
    virtual void renameModifierLabel(LSAType lsaType, std::string oldLabel, std::string newLabel) = 0;

    virtual bool vscaIsNumeric() const = 0;

    /// Get the label for this lsaRecord
    /// @return the label for POSG POSC HGHT UNCR VSCA DGRP records, otherwise return empty string
    virtual std::string getLabel() const = 0;

    /// Returns true if this references the position indicated by label
    /// @param positionLabel the label of the position
    /// @return true if the record references the position
    virtual bool referencesPosition(const std::string& positionLabel) const = 0;
    virtual void renamePosition(std::string oldLabel, std::string newLabel) = 0;
    virtual std::vector<std::string> getReferencedPositions() const = 0;

    /// Returns true if this LSARecord references the modifier indicated by label
    /// @param label the label of the modifier
    /// @param modifierType the LSAType of the modifier
    /// @return true if the record references the modifier
    virtual bool referencesModifier(LSAType modifierType, std::string label) const = 0;

    /// Returns true if this LSARecord supports the modifier type indicated by keyword
    /// @param keyword ModifierKeyword for the control type of interest
    /// @return true if the record supports the modifier type
    virtual bool supportsModifier(ModifierKeyword keyword) const = 0;

    /// Returns the label for the modifier specified by keyword
    /// @param keyword ModifierKeyword indicating modifier type
    /// @return the label for the indicated type, empty string if no label exists for that type
    virtual std::string getModifierLabel(ModifierKeyword keyword) const = 0;

    bool hasRefractionCorrection();
    bool isReducedToEllipsoid();
    bool getCurvCorr();
    bool getOHC();

    /// If the record supports a covariance matrix, checks that the covariance is positive definite
    /// @return false if the record supports covariance and the covariance is invalid
    virtual bool hasValidCovariance() const = 0;

    virtual LSAModifier* getModifiers() = 0;

    // Note: methods to validate VSCA, HFROM/HTO and REFRACT values are static because of the how LSAModifier and LSARecord are related
    // Ideally, LSARecord would be refactored to inherit LSAModifier, but that is a lot of work.  Fornow, we will use static special case
    // validator methods instead.
    static double validateVSCA(std::string value, LSAType lsaType, std::string recordLabel, std::vector<std::string> *warningsVector);
    static double validateHFROM(std::string value, LSAType lsaType, std::string recordLabel, std::vector<std::string> *warningsVector);
    static double validateHTO(std::string value, LSAType lsaType, std::string recordLabel, std::vector<std::string> *warningsVector);
    static double validateRefract(std::string input, LSAType lsaType, std::string recordLabel, std::vector<std::string> *warningsVector);
    static bool validateDMSBool(bool isNegative, int Deg, int Min, double Sec, double minValue, double maxValue, std::vector<std::string> *warningsVector = NULL);

    bool checkInt(std::string value)
    {
        if (!isInteger(value))
        {
            parseWarnings.push_back(validationMessageStart + " is not an integer.");
            return false;
        }

        return true;
    }
    
    // general notes attached to record.
    QString textNotes = "";

protected:
   // member data
   LSAType   type;

   // Validation
   typedef std::vector<std::string> AllowedStrings;
   std::string validationMessageStart;
   void updateValidationMessage(std::string value, LSAFieldType fieldType);

   int validateInt(            std::string value, LSAFieldType fieldType);
   int validateIntMin(         std::string value, LSAFieldType fieldType, int minValue, bool minIsExclusive = false);
   int validateIntMax(         std::string value, LSAFieldType fieldType, int maxValue, bool maxIsExclusive = false);
   int validateIntMinMax(      std::string value, LSAFieldType fieldType, int minValue, int maxValue, bool minIsExclusive = false, bool maxIsExclusive = false);
   int validateIntBool(bool & isNegative, std::string value, LSAFieldType fieldType, int minValue, int maxValue, bool minIsExclusive = false, bool maxIsExclusive = false);
//   bool validateDMSBool(bool isNegative, int Deg, int Min, double Sec, LSAFieldType fieldType, int minValue, int maxValue, bool minIsExclusive = false, bool maxIsExclusive = false);

   double validateDouble(      std::string value, LSAFieldType fieldType);
   double validateDoubleMin(   std::string value, LSAFieldType fieldType, double minValue, bool minIsExclusive = false);
   double validateDoubleMax(   std::string value, LSAFieldType fieldType, double maxValue, bool maxIsExclusive = false);
   double validateDoubleMinMax(std::string value, LSAFieldType fieldType, double minValue, double maxValue, bool minIsExclusive = false, bool maxIsExclusive = false);

   std::string validateString(std::string value, LSAFieldType fieldType, std::string allowedValues);
   bool validateCovariance(double aa, double ab, double ac, double bb, double bc, double cc);
   void addNumFieldsWarning(LSAType lsaType, std::string label);

   bool checkDouble(std::string input)
   {
       bool isDouble;
       QString doubleString = QString::fromStdString(input);
       double value = doubleString.toDouble(&isDouble);

       if (!isDouble)
       {
           parseWarnings.push_back(validationMessageStart + " is not a number.");
           return false;
       }

       return true;
   }

   template<typename T>
   void checkMin(T value, T minValue, bool isExclusive)
   {
       if (isExclusive && value <= minValue)
           parseWarnings.push_back(validationMessageStart + " must be greater than " + gnsstk::StringUtils::asString(minValue) + ".");
       else if (value < minValue)
           parseWarnings.push_back(validationMessageStart + " must be greater than or equal to " + gnsstk::StringUtils::asString(minValue) + ".");
   }

  template<typename T>
  void checkMax(T value, T maxValue, bool isExclusive)
  {
      if (isExclusive && value >= maxValue)
          parseWarnings.push_back(validationMessageStart + " must be less than " + gnsstk::StringUtils::asString(maxValue) + ".");
      else if (value > maxValue)
          parseWarnings.push_back(validationMessageStart + " must be less than or equal to " + gnsstk::StringUtils::asString(maxValue) + ".");
  }

}; // end class LSArecord


typedef std::map<std::string, LSARecord*> LSARecordMap;


#endif   // LSA_RECORD_INCLUDE
