#ifndef LSAVERSION_HPP
#define LSAVERSION_HPP

#include <string>
#include <sstream>

// THIS FILE IS AUTOGENERATED by lsa/scripts/build/versions.py when cmake builds the project.  Manual edits to this file will be lost.

const std::string GIT_SHA =  "2bd3d9004";
const std::string LSAVERSION_MAJOR = "1";
const std::string LSAVERSION_MINOR = "17";
const std::string LSAVERSION_PATCH = "0";
const std::string LSAVERSION_BUILD_DATE = "Apr 24 2025";
const std::string LSAVERSION_BUILD_TIME = "09:35:18";
const std::string LSAVERSION_MAJOR_MINOR_PATCH = LSAVERSION_MAJOR + "." + LSAVERSION_MINOR + "." + LSAVERSION_PATCH;
const std::string LSAVERSION = LSAVERSION_MAJOR + "." + LSAVERSION_MINOR + "." + LSAVERSION_PATCH + " " + LSAVERSION_BUILD_DATE + " " + LSAVERSION_BUILD_TIME;
const std::string LSARELEASE_TYPE = "";
const std::string LSABUILD_TYPE = "";
const std::string LSAADDENDUM = "";
const std::string LSACOPYRIGHT = "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">SALSA Copyright</span></p><p>Copyright (c) 2015-2024 Applied Research Laboratories, The University of Texas at Austin (ARL:UT).<br></p>\n<p><span style=\" font-size:12pt; font-weight:600;\">3rd Party Library Copyrights</span></p>\n<p>GNSSTk Copyright 2024, The University of Texas at Austin.<br>\nHDF5 Copyright 2006-2016 by The HDF Group.<br>\nMarble Program Copyright, 2005-2007 Torsten Rahn (rahn kde.org).<br>\nOpenSSL Copyright (c) 1998-2019 The OpenSSL Project.  All rights reserved.<br>\nPython Copyright (c) 2001-2024 Python Software Foundation; All Rights Reserved.<br>\nQuaZIP Copyright (c) 2005-2020 Sergey A. Tachenov and contributors<br>\nQt Toolkit Copyright (c) 2015 The Qt Company Ltd.<br></p></body></html>\n";
const std::string LSALICENSENOTICE = "<html><body><p><span style=\" font-size:12pt; font-weight:600;\">License and Disclaimer</span></p><p>\nSALSA is free software: you can redistribute it and/or modify it under the terms of the GNU General<br>Public License version 3 (GPL-3.0-only) as published by the Free Software Foundation.</p><p>\nSALSA is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the<br>implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General<br>Public License for more details.</p><p>You should have received a copy of the GNU General Public License along with SALSA.  If not, see<br>https://www.gnu.org/licenses/.</p></body></html>\n";
const std::string LSAPUBLICRELEASE = "<html><head/><body><p>Approved for public release by the National Geospatial-Intelligence Agency, case NGA-U-2025-01219<br></p>\n";

#endif // LSAVERSION_HPP
