const points = [
  {id:"CP01",type:"Fixed control",n:4216308.442,e:1548220.105,z:812.430,constraint:"Fixed XYZ",status:"Control",fixed:true,description:"Horizontal and vertical control"},
  {id:"CP02",type:"Fixed control",n:4216460.183,e:1548498.663,z:818.227,constraint:"Fixed XYZ",status:"Control",fixed:true,description:"Horizontal and vertical control"},
  {id:"P103",type:"Adjusted",n:4216197.562,e:1548346.810,z:806.185,constraint:"Free XYZ",status:"Ready",fixed:false,description:"Adjusted network point"},
  {id:"P104",type:"Adjusted",n:4216258.996,e:1548702.430,z:809.670,constraint:"Free XYZ",status:"Ready",fixed:false,description:"Adjusted network point"},
  {id:"P105",type:"Adjusted",n:4216044.238,e:1548550.771,z:798.365,constraint:"Free XYZ",status:"Ready",fixed:false,description:"Adjusted network point"},
  {id:"P106",type:"Adjusted",n:4216109.725,e:1548904.115,z:802.944,constraint:"Free XYZ",status:"Ready",fixed:false,description:"Adjusted network point"},
  {id:"P107",type:"Adjusted",n:4216411.905,e:1549091.388,z:815.061,constraint:"Free XYZ",status:"Review",fixed:false,description:"Adjusted network point"},
  {id:"P108",type:"Adjusted",n:4215988.407,e:1549018.226,z:793.552,constraint:"Free XYZ",status:"Ready",fixed:false,description:"Adjusted network point"}
];
const observations = [
  {from:"CP01",to:"CP02",kind:"Horizontal distance",value:"323.91 ft",sigma:"0.010 ft",status:"Ready"},
  {from:"CP01",to:"P103",kind:"Horizontal distance",value:"143.88 ft",sigma:"0.010 ft",status:"Ready"},
  {from:"CP02",to:"P104",kind:"Horizontal distance",value:"285.42 ft",sigma:"0.010 ft",status:"Ready"},
  {from:"P103",to:"P104",kind:"Horizontal distance",value:"366.21 ft",sigma:"0.010 ft",status:"Ready"},
  {from:"P103",to:"P105",kind:"Horizontal distance",value:"228.04 ft",sigma:"0.010 ft",status:"Ready"},
  {from:"P104",to:"P106",kind:"Horizontal distance",value:"261.44 ft",sigma:"0.010 ft",status:"Ready"},
  {from:"P105",to:"P106",kind:"Horizontal distance",value:"252.73 ft",sigma:"0.010 ft",status:"Ready"},
  {from:"P106",to:"P107",kind:"Horizontal distance",value:"190.33 ft",sigma:"0.010 ft",status:"Review"},
  {from:"P104",to:"P107",kind:"Horizontal distance",value:"319.08 ft",sigma:"0.010 ft",status:"Ready"},
  {from:"P106",to:"P108",kind:"Horizontal distance",value:"146.91 ft",sigma:"0.010 ft",status:"Ready"},
  {from:"P105",to:"P108",kind:"Horizontal distance",value:"301.18 ft",sigma:"0.010 ft",status:"Ready"},
  {from:"P107",to:"P108",kind:"Horizontal distance",value:"237.02 ft",sigma:"0.010 ft",status:"Ready"}
];
const state = {view:"project",table:"points",selected:"CP01",zoom:1,adjusted:false,search:""};
const $ = (id) => document.getElementById(id);
const fmt = (v) => v.toLocaleString("en-US",{minimumFractionDigits:3,maximumFractionDigits:3});
let toastTimer;
function toast(message){const el=$("toast");el.textContent=message;el.classList.add("visible");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("visible"),2800)}
function currentPoint(){return points.find(p=>p.id===state.selected)||points[0]}
function setView(view){state.view=view;document.querySelectorAll("[data-view]").forEach(el=>el.classList.toggle("active",el.classList.contains("tool-button")&&el.dataset.view===view));document.querySelectorAll(".tree-item").forEach(el=>el.classList.toggle("selected",el.dataset.view===view));const titles={project:["Network adjustment","Review your survey network, observations, and adjustment quality in one place."],points:["Points","Inspect control constraints and coordinate values across the network."],observations:["Observations","Review measured relationships and the values prepared for adjustment."],results:["Adjustment results","Review the adjustment summary and quality checks when connected to the solver."]};$("page-title").textContent=titles[view][0];$("page-subtitle").textContent=titles[view][1];if(view==="observations")setTable("observations");else if(view==="points"||view==="project")setTable("points");else setTable("checks")}
function setTable(table){state.table=table;document.querySelectorAll("[data-table]").forEach(el=>el.classList.toggle("active",el.dataset.table===table));$("table-search").placeholder=table==="observations"?"Search observations…":"Search points…";renderTable()}
function renderTable(){const body=$("table-body");body.innerHTML="";const query=state.search.toLowerCase();let rows=[];
 if(state.table==="points"){rows=points.filter(p=>[p.id,p.type,p.constraint,p.status].join(" ").toLowerCase().includes(query));$("data-table").innerHTML='<thead><tr><th>Point ID</th><th>Type</th><th>Northing (ft)</th><th>Easting (ft)</th><th>Elevation (ft)</th><th>Status</th></tr></thead><tbody id="table-body"></tbody>';const newBody=$("table-body");rows.forEach(p=>{const tr=document.createElement("tr");tr.className=p.id===state.selected?"selected-row":"";tr.innerHTML='<td>'+p.id+'</td><td><span class="type-badge '+(p.fixed?"fixed":"adjusted")+'">'+(p.fixed?"Fixed control":"Adjusted")+'</span></td><td>'+fmt(p.n)+'</td><td>'+fmt(p.e)+'</td><td>'+fmt(p.z)+'</td><td><span class="status-badge '+(p.status==="Review"?"review":"ready")+'">'+p.status+'</span></td>';tr.addEventListener("click",()=>selectPoint(p.id));newBody.appendChild(tr)});$("table-summary").textContent="Showing "+rows.length+" of "+points.length+" points";
 }else if(state.table==="observations"){rows=observations.filter(o=>[o.from,o.to,o.kind,o.status].join(" ").toLowerCase().includes(query));$("data-table").innerHTML='<thead><tr><th>From</th><th>To</th><th>Observation type</th><th>Observed value</th><th>Std. error</th><th>Status</th></tr></thead><tbody id="table-body"></tbody>';const newBody=$("table-body");rows.forEach(o=>{const tr=document.createElement("tr");tr.innerHTML='<td>'+o.from+'</td><td>'+o.to+'</td><td>'+o.kind+'</td><td>'+o.value+'</td><td>'+o.sigma+'</td><td><span class="status-badge '+(o.status==="Review"?"review":"ready")+'">'+o.status+'</span></td>';tr.addEventListener("click",()=>{selectPoint(o.from);toast("Observation "+o.from+" → "+o.to+" selected (sample data).")});newBody.appendChild(tr)});$("table-summary").textContent="Showing "+rows.length+" of "+observations.length+" observations";
 }else{const checks=[["Network connectivity","8 points linked across 12 observations","Ready"],["Control constraints","2 fixed control points","Ready"],["Observation review","1 sample observation flagged for review","Review"],["Solver integration","Not connected in this prototype","Pending"]].filter(r=>r.join(" ").toLowerCase().includes(query));$("data-table").innerHTML='<thead><tr><th>Check</th><th>Details</th><th>Status</th></tr></thead><tbody id="table-body"></tbody>';const newBody=$("table-body");checks.forEach(c=>{const tr=document.createElement("tr");tr.innerHTML='<td>'+c[0]+'</td><td>'+c[1]+'</td><td><span class="status-badge '+(c[2]==="Review"?"review":"ready")+'">'+c[2]+'</span></td>';newBody.appendChild(tr)});$("table-summary").textContent="Showing "+checks.length+" quality checks"}
 if(rows.length===0){const tr=document.createElement("tr");tr.innerHTML='<td class="empty-row" colspan="6">No matching records</td>';body.appendChild(tr)}}
function selectPoint(id){state.selected=id;const p=currentPoint();$("selected-point-name").textContent=p.id;$("selected-point-description").textContent=p.description;$("selected-point-type").textContent=p.fixed?"FIXED":"ADJUSTED";$("selected-point-type").classList.toggle("adjusted",!p.fixed);$("selected-point-symbol").textContent=p.fixed?"CP":"PT";$("selected-point-symbol").classList.toggle("adjusted",!p.fixed);$("point-details").innerHTML='<div><span>Northing</span><strong>'+fmt(p.n)+' ft</strong></div><div><span>Easting</span><strong>'+fmt(p.e)+' ft</strong></div><div><span>Elevation</span><strong>'+fmt(p.z)+' ft</strong></div><div><span>Constraint</span><strong>'+p.constraint+'</strong></div><div><span>Standard error</span><strong>'+(state.adjusted?"Not computed":"—")+'</strong></div>';$("point-details").nextElementSibling.innerHTML='<span class="info-icon">i</span><span>Illustrative values only. '+(state.adjusted?"The demo state is not a solver result.":"No least-squares computation has been performed.")+'</span>';document.querySelectorAll(".node").forEach(n=>n.classList.toggle("selected",n.dataset.point===id));renderTable()}
document.querySelectorAll("[data-view]").forEach(el=>el.addEventListener("click",()=>setView(el.dataset.view)));
document.querySelectorAll("[data-table]").forEach(el=>el.addEventListener("click",()=>setTable(el.dataset.table)));
$("table-search").addEventListener("input",e=>{state.search=e.target.value;renderTable()});
$("fit-network").addEventListener("click",()=>{state.zoom=1;$("network-svg").style.transform="scale(1)";toast("Network view fitted to sample extent.")});
$("zoom-in").addEventListener("click",()=>{state.zoom=Math.min(1.6,state.zoom+.15);$("network-svg").style.transform="scale("+state.zoom+")"});
$("zoom-out").addEventListener("click",()=>{state.zoom=Math.max(.65,state.zoom-.15);$("network-svg").style.transform="scale("+state.zoom+")"});
$("map-reset").addEventListener("click",()=>{state.zoom=1;$("network-svg").style.transform="scale(1)";selectPoint("CP01")});
document.querySelectorAll(".node").forEach(n=>n.addEventListener("click",()=>selectPoint(n.dataset.point)));
$("view-point").addEventListener("click",()=>{setView("points");setTable("points");$("table-search").value=state.selected;state.search=state.selected;renderTable();toast("Filtered the points table to "+state.selected+".")});
$("filter-button").addEventListener("click",()=>toast("Filter presets will be added with the live data model integration."));
$("open-project").addEventListener("click",()=>toast("File import is not wired in this UI milestone. SALSA data adapter comes next."));
$("export-report").addEventListener("click",()=>{const csv="Point ID,Type,Northing (ft),Easting (ft),Elevation (ft),Constraint\n"+points.map(p=>[p.id,p.type,p.n,p.e,p.z,p.constraint].join(",")).join("\n");const blob=new Blob([csv],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="salsa-surveyor-sample-points.csv";a.click();URL.revokeObjectURL(url);toast("Exported illustrative sample point data as CSV.")});
$("run-adjustment").addEventListener("click",()=>{toast("No adjustment run: the SALSA solver is not connected to this prototype.");$("run-status-text").textContent="Solver not connected";$("last-run-value").textContent="Not run"});
selectPoint("CP01");setTable("points");